/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationCompetitionsManagedAnnouncementListResponseFromDiscriminatorValue, createNoCTFAPIEndpointsNotificationsNotificationResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAdministrationCompetitionsCreateCompetitionAnnouncementRequest, serializeNoCTFAPIEndpointsNotificationsNotificationResponse, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationCompetitionsCreateCompetitionAnnouncementRequest, type NoCTFAPIEndpointsAdministrationCompetitionsManagedAnnouncementListResponse, type NoCTFAPIEndpointsNotificationsNotificationResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type WithAnnouncementItemRequestBuilder, WithAnnouncementItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/announcements
 */
export interface AnnouncementsRequestBuilder extends BaseRequestBuilder<AnnouncementsRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.admin.competitions.item.announcements.item collection
     * @param announcementId Unique identifier of the item
     * @returns {WithAnnouncementItemRequestBuilder}
     */
     byAnnouncementId(announcementId: Guid) : WithAnnouncementItemRequestBuilder;
    /**
     * Returns current announcement content and withdrawal state to authorized observers with offset pagination.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationCompetitionsManagedAnnouncementListResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<AnnouncementsRequestBuilderGetQueryParameters> | undefined) : Promise<NoCTFAPIEndpointsAdministrationCompetitionsManagedAnnouncementListResponse | undefined>;
    /**
     * Management announcements default to collaborators; participant visibility must be explicit.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsNotificationsNotificationResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: NoCTFAPIEndpointsAdministrationCompetitionsCreateCompetitionAnnouncementRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsNotificationsNotificationResponse | undefined>;
    /**
     * Returns current announcement content and withdrawal state to authorized observers with offset pagination.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<AnnouncementsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Management announcements default to collaborators; participant visibility must be explicit.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsAdministrationCompetitionsCreateCompetitionAnnouncementRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Returns current announcement content and withdrawal state to authorized observers with offset pagination.
 */
export interface AnnouncementsRequestBuilderGetQueryParameters {
    desc?: boolean;
    includeWithdrawn?: boolean;
    limit?: number;
    offset?: number;
}
/**
 * Uri template for the request builder.
 */
export const AnnouncementsRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/announcements?desc={desc}&includeWithdrawn={includeWithdrawn}&limit={limit}&offset={offset}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AnnouncementsRequestBuilderNavigationMetadata: Record<Exclude<keyof AnnouncementsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byAnnouncementId: {
        requestsMetadata: WithAnnouncementItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["announcementId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AnnouncementsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AnnouncementsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationCompetitionsManagedAnnouncementListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: AnnouncementsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsNotificationsNotificationResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAdministrationCompetitionsCreateCompetitionAnnouncementRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
