/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsGameplayFactsAwdpParticipantStateResponseFromDiscriminatorValue, type NoCTFAPIEndpointsGameplayFactsAwdpParticipantStateResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/awdp-state
 */
export interface AwdpStateRequestBuilder extends BaseRequestBuilder<AwdpStateRequestBuilder> {
    /**
     * Returns the current attack Runtime, Break activation, one-shot Fix progress, authoritative Fix attempt limits and defense activation.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsGameplayFactsAwdpParticipantStateResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsGameplayFactsAwdpParticipantStateResponse | undefined>;
    /**
     * Returns the current attack Runtime, Break activation, one-shot Fix progress, authoritative Fix attempt limits and defense activation.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AwdpStateRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/awdp-state";
/**
 * Metadata for all the requests in the request builder.
 */
export const AwdpStateRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AwdpStateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsGameplayFactsAwdpParticipantStateResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
