/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAuthenticationCurrentUserResponseFromDiscriminatorValue, createNoCTFAPIEndpointsAuthenticationWallpaperUploadFailureResponseFromDiscriminatorValue, type MicrosoftAspNetCoreMvcProblemDetails, type NoCTFAPIEndpointsAuthenticationCurrentUserResponse, type NoCTFAPIEndpointsAuthenticationWallpaperUploadFailureResponse } from '../../../../../models/index.js';
// @ts-ignore
import { MultipartBody, serializeMultipartBody, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/me/wallpaper
 */
export interface WallpaperRequestBuilder extends BaseRequestBuilder<WallpaperRequestBuilder> {
    /**
     * Returns the current user's uploaded wallpaper.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Replaces and enables the current user's wallpaper.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationCurrentUserResponse>}
     * @throws {NoCTFAPIEndpointsAuthenticationWallpaperUploadFailureResponse} error when the service returns a 400 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 413 status code
     */
     put(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationCurrentUserResponse | undefined>;
    /**
     * Returns the current user's uploaded wallpaper.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Replaces and enables the current user's wallpaper.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WallpaperRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/me/wallpaper";
/**
 * Metadata for all the requests in the request builder.
 */
export const WallpaperRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WallpaperRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    put: {
        uriTemplate: WallpaperRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createNoCTFAPIEndpointsAuthenticationWallpaperUploadFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            413: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationCurrentUserResponseFromDiscriminatorValue,
        requestBodyContentType: "multipart/form-data",
        requestBodySerializer: serializeMultipartBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
