/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsGameplayFactsGameplayFactListResponseFromDiscriminatorValue, NoCTFAPIEndpointsGameplayFactsGameplayFactFailureCodeProtocol, NoCTFAPIEndpointsGameplayFactsGameplayFactKindProtocol, NoCTFAPIEndpointsGameplayFactsGameplayFactResultProtocol, NoCTFAPIEndpointsGameplayFactsGameplayFactStateProtocol, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsGameplayFactsGameplayFactListResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { AdjudicationDifferencesRequestBuilderRequestsMetadata, type AdjudicationDifferencesRequestBuilder } from './adjudicationDifferences/index.js';
// @ts-ignore
import { type WithGameplayFactItemRequestBuilder, WithGameplayFactItemRequestBuilderNavigationMetadata, WithGameplayFactItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { ManualAdjustmentsRequestBuilderRequestsMetadata, type ManualAdjustmentsRequestBuilder } from './manualAdjustments/index.js';
// @ts-ignore
import { QueueEvaluationRequestBuilderRequestsMetadata, type QueueEvaluationRequestBuilder } from './queueEvaluation/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/gameplay-facts
 */
export interface GameplayFactsRequestBuilder extends BaseRequestBuilder<GameplayFactsRequestBuilder> {
    /**
     * The adjudicationDifferences property
     */
    get adjudicationDifferences(): AdjudicationDifferencesRequestBuilder;
    /**
     * The manualAdjustments property
     */
    get manualAdjustments(): ManualAdjustmentsRequestBuilder;
    /**
     * The queueEvaluation property
     */
    get queueEvaluation(): QueueEvaluationRequestBuilder;
    /**
     * Gets an item from the NoCTF.api.v1.admin.competitions.item.gameplayFacts.item collection
     * @param gameplayFactId Unique identifier of the item
     * @returns {WithGameplayFactItemRequestBuilder}
     */
     byGameplayFactId(gameplayFactId: Guid) : WithGameplayFactItemRequestBuilder;
    /**
     * Returns offset-paged protected gameplay facts to authorized competition observers.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsGameplayFactsGameplayFactListResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<GameplayFactsRequestBuilderGetQueryParameters> | undefined) : Promise<NoCTFAPIEndpointsGameplayFactsGameplayFactListResponse | undefined>;
    /**
     * Returns offset-paged protected gameplay facts to authorized competition observers.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<GameplayFactsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns offset-paged protected gameplay facts to authorized competition observers.
 */
export interface GameplayFactsRequestBuilderGetQueryParameters {
    actorUserId?: Guid;
    competitionChallengeId?: Guid;
    desc?: boolean;
    failureCode?: NoCTFAPIEndpointsGameplayFactsGameplayFactFailureCodeProtocol;
    gameplayFactKind?: NoCTFAPIEndpointsGameplayFactsGameplayFactKindProtocol;
    gameplayFactResult?: NoCTFAPIEndpointsGameplayFactsGameplayFactResultProtocol;
    limit?: number;
    occurredFrom?: Date;
    occurredTo?: Date;
    offset?: number;
    referenceId?: Guid;
    referenceKind?: number;
    state?: NoCTFAPIEndpointsGameplayFactsGameplayFactStateProtocol;
    teamId?: Guid;
    value?: string;
    victimTeamId?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const GameplayFactsRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/gameplay-facts?desc={desc}&limit={limit}&offset={offset}{&actorUserId*,competitionChallengeId*,failureCode*,gameplayFactKind*,gameplayFactResult*,occurredFrom*,occurredTo*,referenceId*,referenceKind*,state*,teamId*,value*,victimTeamId*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GameplayFactsRequestBuilderNavigationMetadata: Record<Exclude<keyof GameplayFactsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byGameplayFactId: {
        requestsMetadata: WithGameplayFactItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithGameplayFactItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["gameplayFactId"],
    },
    adjudicationDifferences: {
        requestsMetadata: AdjudicationDifferencesRequestBuilderRequestsMetadata,
    },
    manualAdjustments: {
        requestsMetadata: ManualAdjustmentsRequestBuilderRequestsMetadata,
    },
    queueEvaluation: {
        requestsMetadata: QueueEvaluationRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const GameplayFactsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GameplayFactsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsGameplayFactsGameplayFactListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
