apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: noctf
  labels:
    app: redis
    app.kubernetes.io/part-of: noctf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
