/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionHardDeletePreviewResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAdministrationCompetitionsCompetitionHardDeletePreviewResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/hard-delete-preview
 */
export interface HardDeletePreviewRequestBuilder extends BaseRequestBuilder<HardDeletePreviewRequestBuilder> {
    /**
     * Reports immutable historical events and other references that prevent physical deletion. The preview does not modify the competition.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionHardDeletePreviewResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionHardDeletePreviewResponse | undefined>;
    /**
     * Reports immutable historical events and other references that prevent physical deletion. The preview does not modify the competition.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const HardDeletePreviewRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/hard-delete-preview";
/**
 * Metadata for all the requests in the request builder.
 */
export const HardDeletePreviewRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: HardDeletePreviewRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionHardDeletePreviewResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
