/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { EmailVerificationRequestBuilderNavigationMetadata, type EmailVerificationRequestBuilder } from './emailVerification/index.js';
// @ts-ignore
import { LoginRequestBuilderRequestsMetadata, type LoginRequestBuilder } from './login/index.js';
// @ts-ignore
import { LogoutRequestBuilderRequestsMetadata, type LogoutRequestBuilder } from './logout/index.js';
// @ts-ignore
import { LogoutAllRequestBuilderRequestsMetadata, type LogoutAllRequestBuilder } from './logoutAll/index.js';
// @ts-ignore
import { MeRequestBuilderNavigationMetadata, MeRequestBuilderRequestsMetadata, type MeRequestBuilder } from './me/index.js';
// @ts-ignore
import { PasswordRequestBuilderRequestsMetadata, type PasswordRequestBuilder } from './password/index.js';
// @ts-ignore
import { PasswordResetRequestBuilderNavigationMetadata, type PasswordResetRequestBuilder } from './passwordReset/index.js';
// @ts-ignore
import { RefreshRequestBuilderRequestsMetadata, type RefreshRequestBuilder } from './refresh/index.js';
// @ts-ignore
import { RegisterRequestBuilderRequestsMetadata, type RegisterRequestBuilder } from './register/index.js';
// @ts-ignore
import { SsoRequestBuilderNavigationMetadata, type SsoRequestBuilder } from './sso/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth
 */
export interface AuthRequestBuilder extends BaseRequestBuilder<AuthRequestBuilder> {
    /**
     * The emailVerification property
     */
    get emailVerification(): EmailVerificationRequestBuilder;
    /**
     * The login property
     */
    get login(): LoginRequestBuilder;
    /**
     * The logout property
     */
    get logout(): LogoutRequestBuilder;
    /**
     * The logoutAll property
     */
    get logoutAll(): LogoutAllRequestBuilder;
    /**
     * The me property
     */
    get me(): MeRequestBuilder;
    /**
     * The password property
     */
    get password(): PasswordRequestBuilder;
    /**
     * The passwordReset property
     */
    get passwordReset(): PasswordResetRequestBuilder;
    /**
     * The refresh property
     */
    get refresh(): RefreshRequestBuilder;
    /**
     * The register property
     */
    get register(): RegisterRequestBuilder;
    /**
     * The sso property
     */
    get sso(): SsoRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AuthRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuthRequestBuilderNavigationMetadata: Record<Exclude<keyof AuthRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    emailVerification: {
        navigationMetadata: EmailVerificationRequestBuilderNavigationMetadata,
    },
    login: {
        requestsMetadata: LoginRequestBuilderRequestsMetadata,
    },
    logout: {
        requestsMetadata: LogoutRequestBuilderRequestsMetadata,
    },
    logoutAll: {
        requestsMetadata: LogoutAllRequestBuilderRequestsMetadata,
    },
    me: {
        requestsMetadata: MeRequestBuilderRequestsMetadata,
        navigationMetadata: MeRequestBuilderNavigationMetadata,
    },
    password: {
        requestsMetadata: PasswordRequestBuilderRequestsMetadata,
    },
    passwordReset: {
        navigationMetadata: PasswordResetRequestBuilderNavigationMetadata,
    },
    refresh: {
        requestsMetadata: RefreshRequestBuilderRequestsMetadata,
    },
    register: {
        requestsMetadata: RegisterRequestBuilderRequestsMetadata,
    },
    sso: {
        navigationMetadata: SsoRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
