<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../NoCTF.Application/NoCTF.Application.csproj" />
    <ProjectReference Include="../NoCTF.Container.Docker/NoCTF.Container.Docker.csproj" />
    <ProjectReference Include="../NoCTF.Core/NoCTF.Core.csproj" />
    <ProjectReference Include="../NoCTF.Infrastructure/NoCTF.Infrastructure.csproj" />
    <ProjectReference Include="../NoCTF.PluginBase/NoCTF.PluginBase.csproj" />
    <ProjectReference Include="../NoCTF.Plugins.AWDP/NoCTF.Plugins.AWDP.csproj" />
    <ProjectReference Include="../NoCTF.Plugins.Penetration/NoCTF.Plugins.Penetration.csproj" />
    <ProjectReference Include="../NoCTF.Runner.Client/NoCTF.Runner.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

</Project>
