/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTestStatusResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTestStatusResponse } from '../../../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/webhooks/{targetId}/test-deliveries/{deliveryId}
 */
export interface WithDeliveryItemRequestBuilder extends BaseRequestBuilder<WithDeliveryItemRequestBuilder> {
    /**
     * Returns the current result of a competition webhook test delivery.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTestStatusResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTestStatusResponse | undefined>;
    /**
     * Returns the current result of a competition webhook test delivery.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithDeliveryItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/webhooks/{targetId}/test-deliveries/{deliveryId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithDeliveryItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithDeliveryItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTestStatusResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
