/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CheckResultsRequestBuilderRequestsMetadata, type CheckResultsRequestBuilder } from './checkResults/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/internal/v1/awd
 */
export interface AwdRequestBuilder extends BaseRequestBuilder<AwdRequestBuilder> {
    /**
     * The checkResults property
     */
    get checkResults(): CheckResultsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AwdRequestBuilderUriTemplate = "{+baseurl}/api/internal/v1/awd";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AwdRequestBuilderNavigationMetadata: Record<Exclude<keyof AwdRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    checkResults: {
        requestsMetadata: CheckResultsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
