<script setup lang="ts">
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { ArrowLeft, Bot, Eye, Plus, RefreshCw, RotateCw, Save, Send, Trash2 } from 'lucide-vue-next'
import { computed, reactive, ref, watch } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import { toast } from 'vue-sonner'
import { adminApi } from '@/api/noctf'
import { queryKeys } from '@/api/queryKeys'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { useAuthStore } from '@/stores/auth'

const events = [
  { id: 0, label: '比赛开始' }, { id: 1, label: '新题发布' }, { id: 2, label: '新增 Hint' },
  { id: 3, label: '一血' }, { id: 4, label: '二血' }, { id: 5, label: '三血' },
  { id: 6, label: '作弊处罚' }, { id: 7, label: '管理员通知' },
]
interface Rule { eventType: number; enabled: boolean; templateId?: string | null }
interface Binding { id?: string; agentId: string; groupId: string; qqGroupId: number; groupName: string; isDefault: boolean; eventTypes: number[] }
interface Config { competitionId: string; globalEnabled: boolean; hasOnlineAgent: boolean; enabled: boolean; allowMessages: boolean; allowManualNotifications: boolean; stopNormalEventsAfterFinished: boolean; mentionAll: boolean; showTeamName: boolean; showUserName: boolean; showChallengeCategory: boolean; includeCompetitionLink: boolean; includeChallengeLink: boolean; hidePenaltyDetails: boolean; eventRules: Rule[]; groupBindings: Binding[]; warnings: string[] }
interface Group { id: string; agentId: string; groupId: number; groupName: string }
interface Template { id?: string | null; competitionId?: string | null; eventType: number; name: string; content: string; isDefault: boolean; isBuiltIn: boolean; allowedVariables: string[] }
interface Log { id: string; eventType: number; source: number; qqGroupId: number; groupName: string; status: number; attemptCount: number; maxAttempts: number; messageSummary: string; createdAt: string; sentAt?: string; lastErrorCode?: string; lastErrorSummary?: string }
interface LogPage { items: Log[]; total: number }

const route = useRoute(); const competitionId = String(route.params.id); const auth = useAuthStore(); const queryClient = useQueryClient()
const form = reactive<Config>({ competitionId, globalEnabled: false, hasOnlineAgent: false, enabled: false, allowMessages: false, allowManualNotifications: false, stopNormalEventsAfterFinished: true, mentionAll: false, showTeamName: true, showUserName: false, showChallengeCategory: true, includeCompetitionLink: true, includeChallengeLink: true, hidePenaltyDetails: true, eventRules: events.map(e => ({ eventType: e.id, enabled: false })), groupBindings: [], warnings: [] })
const configQuery = useQuery({ queryKey: queryKeys.adminCompetitionQqBot(competitionId), queryFn: () => adminApi.competitionQqBot<Config>(competitionId) })
watch(() => configQuery.data.value, value => { if (value) Object.assign(form, structuredClone(value)) }, { immediate: true })
const groupsQuery = useQuery({ queryKey: ['qqbot-available-groups', competitionId], queryFn: () => adminApi.availableQqBotGroups<Group[]>(competitionId), enabled: computed(() => auth.userRole === 'Admin') })
const templatesQuery = useQuery({ queryKey: queryKeys.adminCompetitionQqBotTemplates(competitionId), queryFn: () => adminApi.competitionQqBotTemplates<Template[]>(competitionId) })
const logsQuery = useQuery({ queryKey: queryKeys.adminCompetitionQqBotLogs(competitionId), queryFn: () => adminApi.qqBotLogs<LogPage>(competitionId, { page: 1, pageSize: 50 }), refetchInterval: 15000 })
const save = useMutation({ mutationFn: () => adminApi.updateCompetitionQqBot(competitionId, { ...form, eventRules: form.eventRules, groupBindings: form.groupBindings }), onSuccess: async () => { toast.success('比赛机器人配置已保存'); await queryClient.invalidateQueries({ queryKey: queryKeys.adminCompetitionQqBot(competitionId) }) } })
const selectedGroup = ref('')
function addGroup() { const group = groupsQuery.data.value?.find(item => item.id === selectedGroup.value); if (!group || form.groupBindings.some(item => item.groupId === group.id)) return; form.groupBindings.push({ agentId: group.agentId, groupId: group.id, qqGroupId: group.groupId, groupName: group.groupName, isDefault: form.groupBindings.length === 0, eventTypes: [] }); selectedGroup.value = '' }
function toggleBindingEvent(binding: Binding, eventType: number) { binding.eventTypes = binding.eventTypes.includes(eventType) ? binding.eventTypes.filter(item => item !== eventType) : [...binding.eventTypes, eventType] }

const templateForm = reactive({ id: undefined as string | undefined, competitionId, eventType: 7, name: '比赛通知', content: '📢 {announcement_title}\n{announcement_content}\n{occurred_at}', isDefault: false })
const announcement = reactive({ title: '', content: '', groupIds: [] as string[], templateId: undefined as string | undefined, isTest: true })
const preview = ref(''); const previewMutation = useMutation({ mutationFn: () => adminApi.previewQqBot<{ renderedText: string }>(competitionId, { competitionId, eventType: templateForm.eventType, templateId: templateForm.id, announcementTitle: announcement.title, announcementContent: announcement.content }), onSuccess: data => { preview.value = data.renderedText } })
const saveTemplate = useMutation({ mutationFn: () => adminApi.upsertCompetitionQqBotTemplate(competitionId, templateForm), onSuccess: async () => { toast.success('模板已保存'); await queryClient.invalidateQueries({ queryKey: queryKeys.adminCompetitionQqBotTemplates(competitionId) }) } })
function editTemplate(template: Template) { if (template.isBuiltIn) { templateForm.id = undefined; templateForm.name = `${events.find(e => e.id === template.eventType)?.label} 自定义`; } else { templateForm.id = template.id || undefined; templateForm.name = template.name } templateForm.eventType = template.eventType; templateForm.content = template.content; templateForm.isDefault = template.isDefault }

watch(() => form.groupBindings, bindings => { announcement.groupIds = bindings.map(item => item.groupId) }, { deep: true, immediate: true })
const sendNotification = useMutation({ mutationFn: () => adminApi.sendQqBotNotification(competitionId, { competitionId, ...announcement }), onSuccess: async () => { toast.success(announcement.isTest ? '测试消息已进入队列' : '正式通知已进入队列'); announcement.title = ''; announcement.content = ''; await queryClient.invalidateQueries({ queryKey: queryKeys.adminCompetitionQqBotLogs(competitionId) }) } })
const retry = useMutation({ mutationFn: (id: string) => adminApi.retryQqBotDelivery(competitionId, id), onSuccess: () => { toast.success('已创建人工重试任务'); queryClient.invalidateQueries({ queryKey: queryKeys.adminCompetitionQqBotLogs(competitionId) }) } })
const statusLabel = (value: number) => ['待发送', '已租用', '等待重试', '成功', '失败', '已取消'][value] || `状态 ${value}`
const toggleItems = [
  ['enabled','启用机器人'],['allowMessages','允许发送'],['allowManualNotifications','允许人工通知'],['stopNormalEventsAfterFinished','结束后停止普通事件'],['mentionAll','@全体成员（默认关闭）'],['showTeamName','显示队伍名'],['showUserName','显示选手名'],['showChallengeCategory','显示题目分类'],['includeCompetitionLink','附比赛链接'],['includeChallengeLink','附题目链接'],['hidePenaltyDetails','隐藏处罚敏感细节'],
] as const
function booleanValue(key: string) { return Boolean((form as unknown as Record<string, unknown>)[key]) }
function setBoolean(key: string, event: Event) { (form as unknown as Record<string, unknown>)[key] = (event.target as HTMLInputElement).checked }
</script>

<template>
  <div class="noctf-admin-page space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Button variant="ghost" size="sm" as-child class="mb-2"><RouterLink :to="`/admin/competitions/${competitionId}`"><ArrowLeft class="mr-2 size-4" />返回比赛</RouterLink></Button><div class="flex items-center gap-2"><Bot class="size-6 text-primary" /><h2 class="text-2xl font-bold tracking-tight">比赛 QQ 机器人</h2></div><p class="mt-1 text-sm text-muted-foreground">事件、群聊、模板和人工通知均仅对当前比赛生效。</p></div><Button :disabled="save.isPending.value" @click="save.mutate()"><Save class="mr-2 size-4" />保存全部配置</Button></div>

    <div v-if="form.warnings.length" class="rounded-md border border-warning/30 bg-warning/5 p-4 text-sm"><div v-for="warning in form.warnings" :key="warning">{{ warning }}</div></div>

    <section class="noctf-workbench p-5"><h3 class="font-semibold">比赛级开关</h3><div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label v-for="item in toggleItems" :key="item[0]" class="flex items-center gap-3 rounded-md border p-3"><input :checked="booleanValue(item[0])" type="checkbox" class="size-4" @change="setBoolean(item[0], $event)" /><span class="text-sm">{{ item[1] }}</span></label></div></section>

    <section class="noctf-workbench p-5"><h3 class="font-semibold">事件开关与模板</h3><div class="mt-4 grid gap-3 md:grid-cols-2"><div v-for="event in events" :key="event.id" class="flex items-center gap-3 rounded-md border p-3"><input v-model="form.eventRules.find(r => r.eventType === event.id)!.enabled" type="checkbox" class="size-4" /><span class="min-w-28 text-sm font-medium">{{ event.label }}</span><select v-model="form.eventRules.find(r => r.eventType === event.id)!.templateId" class="h-9 min-w-0 flex-1 rounded-md border bg-background px-2 text-xs"><option :value="null">默认模板</option><option v-for="template in templatesQuery.data.value?.filter(t => t.eventType === event.id && !t.isBuiltIn)" :key="template.id!" :value="template.id">{{ template.name }}</option></select></div></div></section>

    <section class="noctf-workbench p-5"><div class="flex items-end justify-between"><div><h3 class="font-semibold">群聊绑定</h3><p class="text-xs text-muted-foreground">管理员先在全局页面授权群聊；比赛管理员只能管理已经绑定的群。</p></div></div><div v-if="auth.userRole === 'Admin'" class="mt-4 flex gap-2"><select v-model="selectedGroup" class="h-10 flex-1 rounded-md border bg-background px-3 text-sm"><option value="">选择已授权群</option><option v-for="group in groupsQuery.data.value" :key="group.id" :value="group.id">{{ group.groupName }} · {{ group.groupId }}</option></select><Button variant="outline" @click="addGroup"><Plus class="mr-2 size-4" />绑定</Button></div><div class="mt-4 space-y-3"><div v-for="(binding, index) in form.groupBindings" :key="binding.groupId" class="rounded-md border p-4"><div class="flex items-center justify-between"><div><span class="font-semibold">{{ binding.groupName }}</span><span class="ml-2 font-mono text-xs text-muted-foreground">{{ binding.qqGroupId }}</span></div><Button size="icon" variant="ghost" @click="form.groupBindings.splice(index, 1)"><Trash2 class="size-4" /></Button></div><div class="mt-3 flex flex-wrap gap-2"><label class="flex items-center gap-2 text-xs"><input v-model="binding.isDefault" type="checkbox" />默认群</label><button v-for="event in events" :key="event.id" type="button" class="rounded border px-2 py-1 text-xs" :class="binding.eventTypes.includes(event.id) ? 'border-primary bg-primary/10 text-primary' : 'text-muted-foreground'" @click="toggleBindingEvent(binding, event.id)">{{ event.label }}</button></div></div><div v-if="!form.groupBindings.length" class="noctf-state-box py-10">尚未绑定群聊</div></div></section>

    <section class="noctf-workbench p-5"><h3 class="font-semibold">安全模板编辑与预览</h3><p class="text-xs text-muted-foreground">仅支持白名单变量，不支持表达式、对象属性、include 或代码执行。</p><div class="mt-4 grid gap-4 lg:grid-cols-[220px_1fr]"><div class="space-y-2"><button v-for="template in templatesQuery.data.value" :key="`${template.id}-${template.eventType}-${template.isBuiltIn}`" class="w-full rounded-md border p-2 text-left text-xs hover:bg-muted" @click="editTemplate(template)"><div class="font-semibold">{{ template.name }}</div><div class="text-muted-foreground">{{ events.find(e => e.id === template.eventType)?.label }}{{ template.isBuiltIn ? ' · 内置' : '' }}</div></button></div><div class="space-y-3"><div class="grid gap-3 md:grid-cols-2"><div><Label>名称</Label><Input v-model="templateForm.name" maxlength="80" /></div><div><Label>事件</Label><select v-model.number="templateForm.eventType" class="h-10 w-full rounded-md border bg-background px-3 text-sm"><option v-for="event in events" :key="event.id" :value="event.id">{{ event.label }}</option></select></div></div><Textarea v-model="templateForm.content" class="min-h-36 font-mono text-sm" /><div class="text-xs text-muted-foreground">可用变量：{{ templatesQuery.data.value?.find(t => t.eventType === templateForm.eventType)?.allowedVariables.join(' · ') }}</div><div class="flex gap-2"><Button variant="outline" @click="previewMutation.mutate()"><Eye class="mr-2 size-4" />预览</Button><Button @click="saveTemplate.mutate()"><Save class="mr-2 size-4" />保存比赛模板</Button></div><pre v-if="preview" class="whitespace-pre-wrap rounded-md border bg-muted/30 p-4 text-sm">{{ preview }}</pre></div></div></section>

    <section class="noctf-workbench p-5"><h3 class="font-semibold">管理员通知与测试发送</h3><div class="mt-4 grid gap-4 md:grid-cols-2"><div><Label>标题</Label><Input v-model="announcement.title" maxlength="120" /></div><div class="flex items-end"><label class="flex h-10 items-center gap-2 rounded-md border px-3"><input v-model="announcement.isTest" type="checkbox" /><span class="text-sm">测试发送（与正式通知分开审计）</span></label></div><div class="md:col-span-2"><Label>正文</Label><Textarea v-model="announcement.content" class="min-h-32" maxlength="1800" /></div></div><div class="mt-3 flex flex-wrap gap-3"><label v-for="binding in form.groupBindings" :key="binding.groupId" class="flex items-center gap-2 rounded-md border px-3 py-2 text-xs"><input v-model="announcement.groupIds" type="checkbox" :value="binding.groupId" />{{ binding.groupName }}</label></div><div class="mt-4 flex justify-end"><Button :disabled="!announcement.title || !announcement.content || !announcement.groupIds.length || sendNotification.isPending.value" @click="sendNotification.mutate()"><Send class="mr-2 size-4" />{{ announcement.isTest ? '测试发送' : '正式发送' }}</Button></div></section>

    <section class="noctf-workbench overflow-hidden"><div class="flex items-center justify-between border-b p-5"><div><h3 class="font-semibold">发送日志</h3><p class="text-xs text-muted-foreground">消息正文仅展示摘要；Token、签名和鉴权头不会记录。</p></div><Button size="sm" variant="outline" @click="logsQuery.refetch()"><RefreshCw class="mr-2 size-4" />刷新</Button></div><div v-if="!logsQuery.data.value?.items.length" class="noctf-state-box py-12">暂无发送记录</div><div v-for="log in logsQuery.data.value?.items" :key="log.id" class="grid gap-3 border-b p-4 lg:grid-cols-[1fr_auto]"><div><div class="flex items-center gap-2"><Badge :variant="log.status === 3 ? 'success' : log.status === 4 ? 'destructive' : 'neutral'">{{ statusLabel(log.status) }}</Badge><span class="font-semibold">{{ events.find(e => e.id === log.eventType)?.label }}</span><span class="font-mono text-xs text-muted-foreground">{{ log.groupName }} · {{ log.qqGroupId }}</span></div><p class="mt-2 text-sm">{{ log.messageSummary }}</p><p v-if="log.lastErrorCode" class="mt-1 text-xs text-destructive">{{ log.lastErrorCode }} · {{ log.lastErrorSummary }}</p></div><div class="flex items-center gap-3 text-xs text-muted-foreground"><span>{{ log.attemptCount }}/{{ log.maxAttempts }}</span><Button v-if="log.status === 4 || log.status === 5" size="sm" variant="outline" :disabled="retry.isPending.value" @click="retry.mutate(log.id)"><RotateCw class="mr-2 size-3" />人工重试</Button></div></div></section>
  </div>
</template>
