/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsCompetitionsCompetitionListResponseFromDiscriminatorValue, type NoCTFAPIEndpointsCompetitionsCompetitionListResponse } from '../../../models/index.js';
// @ts-ignore
import { type WithCompetitionItemRequestBuilder, WithCompetitionItemRequestBuilderNavigationMetadata, WithCompetitionItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions
 */
export interface CompetitionsRequestBuilder extends BaseRequestBuilder<CompetitionsRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.competitions.item collection
     * @param competitionId Unique identifier of the item
     * @returns {WithCompetitionItemRequestBuilder}
     */
     byCompetitionId(competitionId: Guid) : WithCompetitionItemRequestBuilder;
    /**
     * Lists competitions visible to the caller using cursor pagination.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsCompetitionsCompetitionListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsCompetitionsCompetitionListResponse | undefined>;
    /**
     * Lists competitions visible to the caller using cursor pagination.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CompetitionsRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CompetitionsRequestBuilderNavigationMetadata: Record<Exclude<keyof CompetitionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCompetitionId: {
        requestsMetadata: WithCompetitionItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithCompetitionItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["competitionId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CompetitionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CompetitionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsCompetitionsCompetitionListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
