/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAuthenticationSsoFlowStatusResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAuthenticationSsoFlowStatusResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { CompleteLoginRequestBuilderRequestsMetadata, type CompleteLoginRequestBuilder } from './completeLogin/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/sso/flows/{flowId}
 */
export interface WithFlowItemRequestBuilder extends BaseRequestBuilder<WithFlowItemRequestBuilder> {
    /**
     * The completeLogin property
     */
    get completeLogin(): CompleteLoginRequestBuilder;
    /**
     * Returns browser-bound SSO flow status and a safe identity summary.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationSsoFlowStatusResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationSsoFlowStatusResponse | undefined>;
    /**
     * Returns browser-bound SSO flow status and a safe identity summary.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithFlowItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/sso/flows/{flowId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithFlowItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithFlowItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    completeLogin: {
        requestsMetadata: CompleteLoginRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithFlowItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithFlowItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationSsoFlowStatusResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
