/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type UnlockRequestBuilder, UnlockRequestBuilderRequestsMetadata } from './unlock/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/hints/{hintId}
 */
export interface WithHintItemRequestBuilder extends BaseRequestBuilder<WithHintItemRequestBuilder> {
    /**
     * The unlock property
     */
    get unlock(): UnlockRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithHintItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/hints/{hintId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithHintItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithHintItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    unlock: {
        requestsMetadata: UnlockRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
