/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionFailureResponseFromDiscriminatorValue, createNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsChallengesQuestionsAddCompetitionQuestionMessageRequest, serializeNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponse, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsChallengesQuestionsAddCompetitionQuestionMessageRequest, type NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionFailureResponse, type NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/questions/{threadRootId}/messages
 */
export interface MessagesRequestBuilder extends BaseRequestBuilder<MessagesRequestBuilder> {
    /**
     * Asker follow-ups return Replied or Resolved questions to Pending; handler replies move Pending questions to Replied. Closed questions are terminal.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionFailureResponse} error when the service returns a 409 status code
     */
     post(body: NoCTFAPIEndpointsChallengesQuestionsAddCompetitionQuestionMessageRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponse | undefined>;
    /**
     * Asker follow-ups return Replied or Resolved questions to Pending; handler replies move Pending questions to Replied. Closed questions are terminal.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsChallengesQuestionsAddCompetitionQuestionMessageRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MessagesRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/questions/{threadRootId}/messages";
/**
 * Metadata for all the requests in the request builder.
 */
export const MessagesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MessagesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsChallengesQuestionsAddCompetitionQuestionMessageRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
