/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAdministrationPlatformPatchSsoConfigurationRequest, serializeNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationPlatformPatchSsoConfigurationRequest, type NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse } from '../../../../../models/index.js';
// @ts-ignore
import { ProvidersRequestBuilderNavigationMetadata, ProvidersRequestBuilderRequestsMetadata, type ProvidersRequestBuilder } from './providers/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/platform/sso
 */
export interface SsoRequestBuilder extends BaseRequestBuilder<SsoRequestBuilder> {
    /**
     * The providers property
     */
    get providers(): ProvidersRequestBuilder;
    /**
     * Returns SSO configuration without provider secrets.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse | undefined>;
    /**
     * Updates the global SSO switch and public base URL.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     patch(body: NoCTFAPIEndpointsAdministrationPlatformPatchSsoConfigurationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse | undefined>;
    /**
     * Returns SSO configuration without provider secrets.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates the global SSO switch and public base URL.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: NoCTFAPIEndpointsAdministrationPlatformPatchSsoConfigurationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SsoRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/platform/sso";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SsoRequestBuilderNavigationMetadata: Record<Exclude<keyof SsoRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    providers: {
        requestsMetadata: ProvidersRequestBuilderRequestsMetadata,
        navigationMetadata: ProvidersRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SsoRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SsoRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponseFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: SsoRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAdministrationPlatformPatchSsoConfigurationRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
