/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithGameplayFactItemRequestBuilder, WithGameplayFactItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/internal/v1/awdp/fix-archives
 */
export interface FixArchivesRequestBuilder extends BaseRequestBuilder<FixArchivesRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.internal.v1.awdp.fixArchives.item collection
     * @param gameplayFactId Unique identifier of the item
     * @returns {WithGameplayFactItemRequestBuilder}
     */
     byGameplayFactId(gameplayFactId: string) : WithGameplayFactItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const FixArchivesRequestBuilderUriTemplate = "{+baseurl}/api/internal/v1/awdp/fix-archives";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FixArchivesRequestBuilderNavigationMetadata: Record<Exclude<keyof FixArchivesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byGameplayFactId: {
        requestsMetadata: WithGameplayFactItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["gameplayFactId"],
    },
};
/* tslint:enable */
/* eslint-enable */
