/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsGameplayFactsPatchVerificationTargetFailureResponseFromDiscriminatorValue, createNoCTFAPIEndpointsGameplayFactsRequestPatchVerificationTargetResponseFromDiscriminatorValue, type MicrosoftAspNetCoreMvcProblemDetails, type NoCTFAPIEndpointsGameplayFactsPatchVerificationTargetFailureResponse, type NoCTFAPIEndpointsGameplayFactsRequestPatchVerificationTargetResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { type WithRuntimeInstanceItemRequestBuilder, WithRuntimeInstanceItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/patch-verification-targets
 */
export interface PatchVerificationTargetsRequestBuilder extends BaseRequestBuilder<PatchVerificationTargetsRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.competitions.item.challenges.item.patchVerificationTargets.item collection
     * @param runtimeInstanceId Unique identifier of the item
     * @returns {WithRuntimeInstanceItemRequestBuilder}
     */
     byRuntimeInstanceId(runtimeInstanceId: Guid) : WithRuntimeInstanceItemRequestBuilder;
    /**
     * Creates one isolated target for one team and challenge.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsGameplayFactsRequestPatchVerificationTargetResponse>}
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 403 status code
     * @throws {NoCTFAPIEndpointsGameplayFactsPatchVerificationTargetFailureResponse} error when the service returns a 409 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 503 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsGameplayFactsRequestPatchVerificationTargetResponse | undefined>;
    /**
     * Creates one isolated target for one team and challenge.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PatchVerificationTargetsRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/patch-verification-targets";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PatchVerificationTargetsRequestBuilderNavigationMetadata: Record<Exclude<keyof PatchVerificationTargetsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byRuntimeInstanceId: {
        navigationMetadata: WithRuntimeInstanceItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["runtimeInstanceId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PatchVerificationTargetsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PatchVerificationTargetsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            403: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsGameplayFactsPatchVerificationTargetFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            503: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsGameplayFactsRequestPatchVerificationTargetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
