/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsTeamsTeamMembershipFailureResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsTeamsJoinTeamByInvitationRequest, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsTeamsJoinTeamByInvitationRequest, type NoCTFAPIEndpointsTeamsTeamMembershipFailureResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/teams/join
 */
export interface JoinRequestBuilder extends BaseRequestBuilder<JoinRequestBuilder> {
    /**
     * Joins the team identified by its current invitation token.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {NoCTFAPIEndpointsTeamsTeamMembershipFailureResponse} error when the service returns a 409 status code
     */
     post(body: NoCTFAPIEndpointsTeamsJoinTeamByInvitationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Joins the team identified by its current invitation token.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsTeamsJoinTeamByInvitationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const JoinRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/teams/join";
/**
 * Metadata for all the requests in the request builder.
 */
export const JoinRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: JoinRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, application/problem+json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsTeamsTeamMembershipFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsTeamsJoinTeamByInvitationRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
