/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse, serializeNoCTFAPIEndpointsAdministrationPlatformUpdateSsoProviderRequest, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse, type NoCTFAPIEndpointsAdministrationPlatformUpdateSsoProviderRequest } from '../../../../../../../models/index.js';
// @ts-ignore
import { AuthenticationTestsRequestBuilderRequestsMetadata, type AuthenticationTestsRequestBuilder } from './authenticationTests/index.js';
// @ts-ignore
import { ConnectionTestsRequestBuilderRequestsMetadata, type ConnectionTestsRequestBuilder } from './connectionTests/index.js';
// @ts-ignore
import { SecretRequestBuilderRequestsMetadata, type SecretRequestBuilder } from './secret/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/platform/sso/providers/{providerId}
 */
export interface WithProviderItemRequestBuilder extends BaseRequestBuilder<WithProviderItemRequestBuilder> {
    /**
     * The authenticationTests property
     */
    get authenticationTests(): AuthenticationTestsRequestBuilder;
    /**
     * The connectionTests property
     */
    get connectionTests(): ConnectionTestsRequestBuilder;
    /**
     * The secret property
     */
    get secret(): SecretRequestBuilder;
    /**
     * Updates a provider without exposing or replacing its secret.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     put(body: NoCTFAPIEndpointsAdministrationPlatformUpdateSsoProviderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse | undefined>;
    /**
     * Updates a provider without exposing or replacing its secret.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: NoCTFAPIEndpointsAdministrationPlatformUpdateSsoProviderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithProviderItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/platform/sso/providers/{providerId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithProviderItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithProviderItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    authenticationTests: {
        requestsMetadata: AuthenticationTestsRequestBuilderRequestsMetadata,
    },
    connectionTests: {
        requestsMetadata: ConnectionTestsRequestBuilderRequestsMetadata,
    },
    secret: {
        requestsMetadata: SecretRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithProviderItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: WithProviderItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAdministrationPlatformUpdateSsoProviderRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
