apiVersion: v1
kind: ConfigMap
metadata:
  name: noctf-config
  namespace: noctf
  labels:
    app.kubernetes.io/part-of: noctf
data:
  ASPNETCORE_URLS: "http://+:8080"
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__Redis: "redis:6379"
  JwtSettings__Issuer: "NoCTF"
  JwtSettings__Audience: "NoCTF"
  JwtSettings__ExpiryMinutes: "60"
  StorageProvider__Type: "S3"
  StorageProvider__S3__Endpoint: "http://minio:9000"
  StorageProvider__S3__Bucket: "noctf"
  StorageProvider__S3__Region: "us-east-1"
  StorageProvider__PublicBaseUrl: "http://minio.noctf.local"
  Runner__BaseUrl: "http://runner:8080"
  Runner__Provider: "Kubernetes"
  Runner__AllowedRegistries: "docker.io,ghcr.io,quay.io,registry.k8s.io,localhost"
  K8s__NamespacePrefix: "noctf-inst"
  K8s__DefaultExposure: "NodePort"
  K8s__NetworkMode: "Isolated"
  K8s__PublicEntry: "noctf.local"
  K8s__IngressBaseDomain: "challenges.noctf.local"
