apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: noctf
  labels:
    app: minio-init
    app.kubernetes.io/part-of: noctf
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        app: minio-init
    spec:
      restartPolicy: OnFailure
      automountServiceAccountToken: false
      containers:
        - name: minio-init
          image: minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1@sha256:95b5f3f7969a5c5a9f3a700ba72d5c84172819e13385aaf916e237cf111ab868
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              until mc alias set noctf http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do sleep 2; done
              mc mb --ignore-existing noctf/noctf
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: noctf-secrets
                  key: minio-access-key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: noctf-secrets
                  key: minio-secret-key
