apiVersion: v1
kind: Secret
metadata:
  name: noctf-secrets
  namespace: noctf
  labels:
    app.kubernetes.io/part-of: noctf
type: Opaque
stringData:
  jwt-secret: "replace-with-at-least-32-characters"
  db-password: "replace-with-db-password"
  seed-admin-password: "replace-with-initial-admin-password"
  runner-api-key: "replace-with-runner-api-key"
  minio-access-key: "replace-with-minio-access-key"
  minio-secret-key: "replace-with-minio-secret-key"
