<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="TngTech.ArchUnitNET" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="TUnit.Assertions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/NoCTF.API/NoCTF.API.csproj" />
    <ProjectReference Include="../../src/NoCTF.Application/NoCTF.Application.csproj" />
    <ProjectReference Include="../../src/NoCTF.Domain/NoCTF.Domain.csproj" />
    <ProjectReference Include="../../src/NoCTF.GameModes/NoCTF.GameModes.csproj" />
    <ProjectReference Include="../../src/NoCTF.Infrastructure/NoCTF.Infrastructure.csproj" />
    <ProjectReference Include="../../src/NoCTF.Integrations.QQBot/NoCTF.Integrations.QQBot.csproj" />
    <ProjectReference Include="../../src/NoCTF.Runtime.Docker/NoCTF.Runtime.Docker.csproj" />
    <ProjectReference Include="../../src/NoCTF.Runtime.Kubernetes/NoCTF.Runtime.Kubernetes.csproj" />
    <ProjectReference Include="../../src/NoCTF.Runner/NoCTF.Runner.csproj" />
  </ItemGroup>
</Project>
