/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { FixArchivesRequestBuilderNavigationMetadata, type FixArchivesRequestBuilder } from './fixArchives/index.js';
// @ts-ignore
import { FixResultsRequestBuilderRequestsMetadata, type FixResultsRequestBuilder } from './fixResults/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/internal/v1/awdp
 */
export interface AwdpRequestBuilder extends BaseRequestBuilder<AwdpRequestBuilder> {
    /**
     * The fixArchives property
     */
    get fixArchives(): FixArchivesRequestBuilder;
    /**
     * The fixResults property
     */
    get fixResults(): FixResultsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AwdpRequestBuilderUriTemplate = "{+baseurl}/api/internal/v1/awdp";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AwdpRequestBuilderNavigationMetadata: Record<Exclude<keyof AwdpRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    fixArchives: {
        navigationMetadata: FixArchivesRequestBuilderNavigationMetadata,
    },
    fixResults: {
        requestsMetadata: FixResultsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
