/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAdministrationRuntimeRuntimeTrafficCaptureConflictResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAdministrationRuntimeRuntimeTrafficCaptureConflictResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { FileRequestBuilderRequestsMetadata, type FileRequestBuilder } from './file/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/traffic-captures/{runtimeInstanceId}
 */
export interface WithRuntimeInstanceItemRequestBuilder extends BaseRequestBuilder<WithRuntimeInstanceItemRequestBuilder> {
    /**
     * The file property
     */
    get file(): FileRequestBuilder;
    /**
     * Deletes one terminal Runtime capture.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {NoCTFAPIEndpointsAdministrationRuntimeRuntimeTrafficCaptureConflictResponse} error when the service returns a 409 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Deletes one terminal Runtime capture.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithRuntimeInstanceItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/traffic-captures/{runtimeInstanceId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithRuntimeInstanceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithRuntimeInstanceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    file: {
        requestsMetadata: FileRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithRuntimeInstanceItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithRuntimeInstanceItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            409: createNoCTFAPIEndpointsAdministrationRuntimeRuntimeTrafficCaptureConflictResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
};
/* tslint:enable */
/* eslint-enable */
