/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsRuntimeRuntimeTargetListResponseFromDiscriminatorValue, type NoCTFAPIEndpointsRuntimeRuntimeTargetListResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/targets
 */
export interface TargetsRequestBuilder extends BaseRequestBuilder<TargetsRequestBuilder> {
    /**
     * During hardening only the caller's team is returned; afterwards every eligible team is retained even when it has no running URLs.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsRuntimeRuntimeTargetListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsRuntimeRuntimeTargetListResponse | undefined>;
    /**
     * During hardening only the caller's team is returned; afterwards every eligible team is retained even when it has no running URLs.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TargetsRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/targets";
/**
 * Metadata for all the requests in the request builder.
 */
export const TargetsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TargetsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsRuntimeRuntimeTargetListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
