/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAuthenticationAvatarUploadFailureResponseFromDiscriminatorValue, createNoCTFAPIEndpointsAuthenticationCurrentUserResponseFromDiscriminatorValue, type MicrosoftAspNetCoreMvcProblemDetails, type NoCTFAPIEndpointsAuthenticationAvatarUploadFailureResponse, type NoCTFAPIEndpointsAuthenticationCurrentUserResponse } from '../../../../../models/index.js';
// @ts-ignore
import { MultipartBody, serializeMultipartBody, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/me/avatar
 */
export interface AvatarRequestBuilder extends BaseRequestBuilder<AvatarRequestBuilder> {
    /**
     * Replaces the current user's cropped avatar.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationCurrentUserResponse>}
     * @throws {NoCTFAPIEndpointsAuthenticationAvatarUploadFailureResponse} error when the service returns a 400 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 413 status code
     */
     put(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationCurrentUserResponse | undefined>;
    /**
     * Replaces the current user's cropped avatar.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AvatarRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/me/avatar";
/**
 * Metadata for all the requests in the request builder.
 */
export const AvatarRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: AvatarRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createNoCTFAPIEndpointsAuthenticationAvatarUploadFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            413: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationCurrentUserResponseFromDiscriminatorValue,
        requestBodyContentType: "multipart/form-data",
        requestBodySerializer: serializeMultipartBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
