/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithProviderItemRequestBuilder, WithProviderItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/sso/callback/oidc
 */
export interface OidcRequestBuilder extends BaseRequestBuilder<OidcRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.auth.sso.callback.oidc.item collection
     * @param providerId Unique identifier of the item
     * @returns {WithProviderItemRequestBuilder}
     */
     byProviderId(providerId: Guid) : WithProviderItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OidcRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/sso/callback/oidc";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OidcRequestBuilderNavigationMetadata: Record<Exclude<keyof OidcRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byProviderId: {
        requestsMetadata: WithProviderItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["providerId"],
    },
};
/* tslint:enable */
/* eslint-enable */
