/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsNotificationsNotificationFeedResponseFromDiscriminatorValue, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsNotificationsNotificationFeedResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/notifications/feed
 */
export interface FeedRequestBuilder extends BaseRequestBuilder<FeedRequestBuilder> {
    /**
     * The first request returns an empty safe checkpoint. Later requests return events in ascending creation order.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsNotificationsNotificationFeedResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<FeedRequestBuilderGetQueryParameters> | undefined) : Promise<NoCTFAPIEndpointsNotificationsNotificationFeedResponse | undefined>;
    /**
     * The first request returns an empty safe checkpoint. Later requests return events in ascending creation order.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<FeedRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * The first request returns an empty safe checkpoint. Later requests return events in ascending creation order.
 */
export interface FeedRequestBuilderGetQueryParameters {
    cursor?: string;
    limit?: number;
}
/**
 * Uri template for the request builder.
 */
export const FeedRequestBuilderUriTemplate = "{+baseurl}/api/v1/notifications/feed?limit={limit}{&cursor*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const FeedRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FeedRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsNotificationsNotificationFeedResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
