import { assertThemeTokenCoverage, type ThemePackage } from './theme-package'

const pixelTokens = {
  '--radius': '0',
  '--background': '#e4e4e4',
  '--foreground': '#242424',
  '--card': '#eeeeee',
  '--card-foreground': '#242424',
  '--popover': '#ededed',
  '--popover-foreground': '#242424',
  '--primary': '#2f2f2f',
  '--primary-foreground': '#f5f5f5',
  '--secondary': '#d6d6d6',
  '--secondary-foreground': '#242424',
  '--muted': '#dddddd',
  '--muted-foreground': '#5a5a5a',
  '--accent': '#cdcdcd',
  '--accent-foreground': '#1f1f1f',
  '--destructive': '#a13e34',
  '--border': '#8b8b8b',
  '--input': '#a2a2a2',
  '--ring': '#3a3a3a',
  '--chart-1': '#3d3d3d',
  '--chart-2': '#737373',
  '--chart-3': '#9d9d9d',
  '--chart-4': '#5a5a5a',
  '--chart-5': '#b7b7b7',
  '--neon-web': '#ff9e42',
  '--neon-pwn': '#ff5e36',
  '--neon-misc': '#c47aff',
  '--neon-reverse': '#66ccff',
  '--neon-mobile': '#f06eff',
  '--neon-crypto': '#ffe14d',
  '--neon-forensics': '#ffb86c',
  '--neon-ai': '#4deaff',
  '--neon-blockchain': '#ff7ec7',
  '--neon-hardware': '#ff8c42',
  '--neon-osint': '#ff9f7a',
  '--neon-cloud': '#7ab8ff',
  '--neon-default': 'var(--neon-misc)',
  '--neon-foreground': '#171717',
  '--sidebar': '#c9c9c9',
  '--sidebar-foreground': '#242424',
  '--sidebar-primary': '#2f2f2f',
  '--sidebar-primary-foreground': '#f5f5f5',
  '--sidebar-accent': '#bdbdbd',
  '--sidebar-accent-foreground': '#242424',
  '--sidebar-border': '#8b8b8b',
  '--sidebar-ring': '#3a3a3a',
  '--card-border-color': '#8b8b8b',
  '--card-shadow': '2px 2px 0 #bdbdbd',
  '--panel-shadow': '4px 4px 0 #d4d4d4',
  '--panel-shadow-dark': '6px 6px 0 #7d7d7d',
  '--float-shadow': '6px 6px 0 #bdbdbd',
  '--page-background-start': '#ebebeb',
  '--page-background-end': '#e3e3e3',
  '--page-grid-color': 'rgb(80 80 80 / 0.08)',
  '--app-background-start': '#e7e7e7',
  '--app-background-end': '#dfdfdf',
  '--app-effect-color': '#2f2f2f',
  '--app-effect-opacity': '0.28',
  '--card-decoration': '#000000',
  '--panel-border': '#bdbdbd',
  '--panel-dark-border': '#5f5f5f',
  '--panel-face-start': '#e4e4e4',
  '--panel-face-end': '#dadada',
  '--panel-dark-face-start': '#4b4b4b',
  '--panel-dark-face-end': '#383838',
  '--panel-base-border': '#d4d4d4',
  '--panel-base-surface': '#f5f5f5',
  '--panel-base-shadow': '#e0e0e0',
  '--panel-dark-base-border': '#8b8b8b',
  '--panel-dark-base-surface': '#d7d7d7',
  '--panel-dark-base-shadow': '#b6b6b6',
  '--button-primary-border': '#1b1b1b',
  '--button-primary-shadow': '#8c8c8c',
  '--button-primary-hover': '#3a3a3a',
  '--button-destructive-border': '#5f1f18',
  '--button-destructive-shadow': '#bda3a0',
  '--button-destructive-hover': '#8f372f',
  '--button-outline-border': '#7f7f7f',
  '--button-outline-surface': '#e5e5e5',
  '--button-outline-shadow': '#c7c7c7',
  '--button-outline-hover': '#d8d8d8',
  '--button-ghost-border': '#9a9a9a',
  '--button-ghost-hover': '#d8d8d8',
  '--admin-header-background': 'rgb(255 255 255 / 0.85)',
  '--admin-chrome-border': 'rgb(255 255 255 / 0.1)',
  '--admin-account-surface': 'rgb(255 255 255 / 0.05)',
  '--admin-account-muted': '#94a3b8',
  '--semantic-info': '#0e7490',
  '--semantic-info-soft': '#cffafe',
  '--semantic-info-border': '#67e8f9',
  '--semantic-success': '#047857',
  '--semantic-success-soft': '#d1fae5',
  '--semantic-success-border': '#6ee7b7',
  '--semantic-warning': '#b45309',
  '--semantic-warning-soft': '#fef3c7',
  '--semantic-warning-border': '#fcd34d',
  '--semantic-danger': '#be123c',
  '--semantic-danger-soft': '#ffe4e6',
  '--semantic-danger-border': '#fda4af',
  '--semantic-neutral': '#64748b',
  '--semantic-neutral-soft': '#e2e8f0',
  '--semantic-neutral-border': '#94a3b8',
  '--dialog-overlay': 'rgb(15 23 42 / 0.45)',
  '--dialog-surface': 'rgb(255 255 255 / 0.95)',
  '--cursor-color': '#ffffff',
  '--auth-border': '#8b8b8b',
  '--auth-surface': '#d9d9d9',
  '--auth-surface-strong': '#bfbfbf',
  '--auth-surface-muted': '#dcdcdc',
  '--auth-grid': 'rgb(70 70 70 / 0.16)',
  '--auth-grid-soft': 'rgb(70 70 70 / 0.1)',
  '--auth-background-start': '#dddddd',
  '--auth-background-end': '#d4d4d4',
  '--auth-foreground': '#1f1f1f',
  '--auth-accent': '#60a5fa',
  '--auth-accent-soft': '#bfdbfe',
  '--auth-muted': '#64748b',
  '--awdp-surface': '#ffffff',
  '--awdp-surface-muted': '#f1f5f9',
  '--awdp-surface-deep': '#0f172a',
  '--awdp-text': '#0f172a',
  '--awdp-text-muted': '#64748b',
  '--awdp-text-inverse': '#f8fafc',
  '--awdp-border': '#cbd5e1',
  '--awdp-star': '#64748b',
  '--awdp-nebula-start': '#cbd5e1',
  '--awdp-nebula-mid': '#e2e8f0',
  '--awdp-nebula-end': '#f8fafc',
  '--awdp-node-fill': '#f8fafc',
  '--awdp-node-stroke': '#64748b',
  '--awdp-category-web': '#0891b2',
  '--awdp-category-pwn': '#db2777',
  '--awdp-category-crypto': '#7c3aed',
  '--awdp-category-reverse': '#059669',
  '--awdp-category-misc': '#ca8a04',
  '--leaderboard-paper': '#fdfbf7',
  '--leaderboard-border': '#d7ccc8',
  '--leaderboard-line-1': '#e63946',
  '--leaderboard-line-2': '#1d3557',
  '--leaderboard-line-3': '#06d6a0',
  '--leaderboard-line-4': '#7b2cbf',
  '--leaderboard-line-5': '#f4a261',
  '--leaderboard-line-6': '#f72585',
  '--leaderboard-line-7': '#2a9d8f',
  '--leaderboard-line-8': '#e9c46a',
  '--leaderboard-line-9': '#457b9d',
  '--leaderboard-line-10': '#d62828',
  '--leaderboard-gold': '#ffd700',
  '--leaderboard-gold-foreground': '#5c4800',
  '--leaderboard-silver': '#c0c0c0',
  '--leaderboard-silver-foreground': '#3a3a3a',
  '--leaderboard-bronze': '#cd7f32',
}

assertThemeTokenCoverage(pixelTokens)

const neonCommandTokens = {
  ...pixelTokens,
  '--radius': '12px',
  '--background': '#e0e5ec',
  '--foreground': '#1f2937',
  '--card': '#e0e5ec',
  '--card-foreground': '#1f2937',
  '--popover': '#e0e5ec',
  '--popover-foreground': '#1f2937',
  '--primary': '#e0005f',
  '--primary-foreground': '#ffffff',
  '--secondary': '#dbe0e8',
  '--secondary-foreground': '#1f2937',
  '--muted': '#dbe0e8',
  '--muted-foreground': '#4b5563',
  '--accent': '#eceff4',
  '--accent-foreground': '#1f2937',
  '--destructive': '#c22433',
  '--border': '#d3d8e0',
  '--input': '#d3d8e0',
  '--ring': '#e0005f',
  '--app-background-start': '#e6eaf1',
  '--app-background-end': '#dde2ea',
  '--app-effect-color': '#e0005f',
  '--app-effect-opacity': '0.08',
  '--cursor-color': '#e0005f',
  '--card-shadow': '4px 4px 8px #b8bcc2, -4px -4px 8px #ffffff',
  '--panel-shadow': '6px 6px 12px #b8bcc2, -6px -6px 12px #ffffff',
  '--float-shadow': '8px 8px 16px #b8bcc2, -8px -8px 16px #ffffff',
  '--semantic-info': '#2b5fc7',
  '--semantic-success': '#0b7355',
  '--semantic-warning': '#8a5a00',
  '--semantic-danger': '#c22433',
  '--dialog-overlay': 'rgb(31 41 55 / 0.32)',
  '--dialog-surface': '#e0e5ec',
}

export const defaultThemeId = 'noctf-pixel'

export const builtInThemePackages: ThemePackage[] = [
  {
    id: defaultThemeId,
    name: 'NoCTF Pixel',
    description: 'The original monochrome pixel workstation used by the current UI.',
    version: '1.0.0',
    builtIn: true,
    uiPackage: 'v1',
    tokens: pixelTokens,
    preview: { background: '#e4e4e4', surface: '#eeeeee', primary: '#2f2f2f', accent: '#cdcdcd' },
  },
  {
    id: 'neon-command',
    name: 'Neon Command',
    description: 'Soft clay neumorphic workspace with dual-shadow depth and magenta signal accents.',
    version: '0.2.0',
    builtIn: true,
    uiPackage: 'v2',
    tokens: neonCommandTokens,
    preview: { background: '#e0e5ec', surface: '#eceff4', primary: '#e0005f', accent: '#0b7355' },
  },
  {
    id: 'terminal-amber',
    name: 'Terminal Amber',
    description: 'A restrained dark console package with warm amber signals.',
    version: '1.0.0',
    builtIn: true,
    uiPackage: 'v1',
    tokens: {
      ...pixelTokens,
      '--background': '#171714',
      '--foreground': '#f1ead6',
      '--card': '#24231d',
      '--card-foreground': '#f1ead6',
      '--popover': '#24231d',
      '--popover-foreground': '#f1ead6',
      '--primary': '#f3b44b',
      '--primary-foreground': '#1b1710',
      '--secondary': '#323027',
      '--secondary-foreground': '#f1ead6',
      '--muted': '#2b2a23',
      '--muted-foreground': '#b8ad91',
      '--accent': '#4b4026',
      '--accent-foreground': '#f8ecd1',
      '--destructive': '#d86655',
      '--border': '#74684b',
      '--input': '#5d563f',
      '--ring': '#f3b44b',
      '--chart-1': '#f3b44b',
      '--chart-2': '#f7d58c',
      '--chart-3': '#86efac',
      '--chart-4': '#d8b4fe',
      '--chart-5': '#fb923c',
      '--sidebar': '#1e1d18',
      '--sidebar-foreground': '#f1ead6',
      '--sidebar-primary': '#f3b44b',
      '--sidebar-primary-foreground': '#1b1710',
      '--sidebar-accent': '#373326',
      '--sidebar-accent-foreground': '#f8ecd1',
      '--sidebar-border': '#665d44',
      '--sidebar-ring': '#f3b44b',
      '--card-border-color': '#74684b',
      '--card-shadow': '2px 2px 0 #0e0e0c',
      '--panel-shadow': '4px 4px 0 #11110f',
      '--panel-shadow-dark': '6px 6px 0 #090908',
      '--float-shadow': '6px 6px 0 #0e0e0c',
      '--page-background-start': '#1d1c17',
      '--page-background-end': '#151510',
      '--page-grid-color': 'rgb(243 180 75 / 0.08)',
      '--app-background-start': '#242218',
      '--app-background-end': '#171610',
      '--app-effect-color': '#f3b44b',
      '--card-decoration': '#f3b44b',
      '--panel-border': '#74684b',
      '--panel-dark-border': '#9d8655',
      '--panel-face-start': '#2d2b22',
      '--panel-face-end': '#201f19',
      '--panel-dark-face-start': '#3a3424',
      '--panel-dark-face-end': '#252116',
      '--panel-base-border': '#3d392b',
      '--panel-base-surface': '#29271f',
      '--panel-base-shadow': '#11110f',
      '--panel-dark-base-border': '#655a3e',
      '--panel-dark-base-surface': '#332f23',
      '--panel-dark-base-shadow': '#11110f',
      '--button-primary-border': '#f7d58c',
      '--button-primary-shadow': '#734c16',
      '--button-primary-hover': '#ffd078',
      '--button-outline-border': '#74684b',
      '--button-outline-surface': '#2e2c22',
      '--button-outline-shadow': '#11110f',
      '--button-outline-hover': '#3b3728',
      '--button-ghost-border': '#74684b',
      '--button-ghost-hover': '#302d22',
      '--admin-header-background': 'rgb(30 29 24 / 0.88)',
      '--admin-chrome-border': 'rgb(243 180 75 / 0.15)',
      '--admin-account-surface': 'rgb(243 180 75 / 0.08)',
      '--admin-account-muted': '#b8ad91',
      '--semantic-info': '#67e8f9',
      '--semantic-info-soft': '#183b42',
      '--semantic-info-border': '#3b8191',
      '--semantic-success': '#86efac',
      '--semantic-success-soft': '#1f3b2b',
      '--semantic-success-border': '#4a8a61',
      '--semantic-warning': '#fcd34d',
      '--semantic-warning-soft': '#423418',
      '--semantic-warning-border': '#94752c',
      '--semantic-danger': '#fda4af',
      '--semantic-danger-soft': '#48242a',
      '--semantic-danger-border': '#92505b',
      '--semantic-neutral': '#b8ad91',
      '--semantic-neutral-soft': '#373326',
      '--semantic-neutral-border': '#665d44',
      '--dialog-overlay': 'rgb(5 5 4 / 0.72)',
      '--dialog-surface': 'rgb(36 35 29 / 0.97)',
      '--cursor-color': '#f3b44b',
      '--neon-web': '#67e8f9',
      '--neon-pwn': '#fca5a5',
      '--neon-misc': '#d8b4fe',
      '--neon-reverse': '#86efac',
      '--neon-mobile': '#f9a8d4',
      '--neon-crypto': '#fcd34d',
      '--neon-forensics': '#fb923c',
      '--neon-ai': '#67e8f9',
      '--neon-blockchain': '#f9a8d4',
      '--neon-hardware': '#f3b44b',
      '--neon-osint': '#f7d58c',
      '--neon-cloud': '#93c5fd',
      '--neon-default': 'var(--neon-misc)',
      '--neon-foreground': '#1b1710',
      '--auth-border': '#74684b',
      '--auth-surface': '#2d2b22',
      '--auth-surface-strong': '#3a3424',
      '--auth-surface-muted': '#29271f',
      '--auth-grid': 'rgb(243 180 75 / 0.14)',
      '--auth-grid-soft': 'rgb(243 180 75 / 0.08)',
      '--auth-background-start': '#242218',
      '--auth-background-end': '#171610',
      '--auth-foreground': '#f1ead6',
      '--auth-accent': '#f3b44b',
      '--auth-accent-soft': '#f7d58c',
      '--auth-muted': '#b8ad91',
      '--awdp-surface': '#252419',
      '--awdp-surface-muted': '#312f24',
      '--awdp-surface-deep': '#11110d',
      '--awdp-text': '#f1ead6',
      '--awdp-text-muted': '#b8ad91',
      '--awdp-text-inverse': '#f1ead6',
      '--awdp-border': '#74684b',
      '--awdp-star': '#b8ad91',
      '--awdp-nebula-start': '#755c31',
      '--awdp-nebula-mid': '#3a3020',
      '--awdp-nebula-end': '#1b1811',
      '--awdp-node-fill': '#24231d',
      '--awdp-node-stroke': '#b8ad91',
      '--awdp-category-web': '#67e8f9',
      '--awdp-category-pwn': '#f9a8d4',
      '--awdp-category-crypto': '#d8b4fe',
      '--awdp-category-reverse': '#86efac',
      '--awdp-category-misc': '#fcd34d',
      '--leaderboard-paper': '#24231d',
      '--leaderboard-border': '#74684b',
      '--leaderboard-line-1': '#f3b44b',
      '--leaderboard-line-2': '#f7d58c',
      '--leaderboard-line-3': '#86efac',
      '--leaderboard-line-4': '#d8b4fe',
      '--leaderboard-line-5': '#fb923c',
      '--leaderboard-line-6': '#f9a8d4',
      '--leaderboard-line-7': '#67e8f9',
      '--leaderboard-line-8': '#fde68a',
      '--leaderboard-line-9': '#93c5fd',
      '--leaderboard-line-10': '#fca5a5',
      '--leaderboard-gold': '#f3b44b',
      '--leaderboard-gold-foreground': '#1b1710',
      '--leaderboard-silver': '#c4b998',
      '--leaderboard-silver-foreground': '#1b1710',
      '--leaderboard-bronze': '#bd7b47',
    },
    preview: { background: '#171714', surface: '#24231d', primary: '#f3b44b', accent: '#4b4026' },
  },
  {
    id: 'signal-paper',
    name: 'Signal Paper',
    description: 'A high-contrast field notebook palette with green operational accents.',
    version: '1.0.0',
    builtIn: true,
    uiPackage: 'v1',
    tokens: {
      ...pixelTokens,
      '--background': '#edf2e7',
      '--foreground': '#18302b',
      '--card': '#f8faf4',
      '--card-foreground': '#18302b',
      '--popover': '#f8faf4',
      '--popover-foreground': '#18302b',
      '--primary': '#17594a',
      '--primary-foreground': '#f7fff7',
      '--secondary': '#dbe7d8',
      '--secondary-foreground': '#18302b',
      '--muted': '#e0e9dc',
      '--muted-foreground': '#4d625c',
      '--accent': '#c8e0ca',
      '--accent-foreground': '#18302b',
      '--destructive': '#b84b46',
      '--border': '#719086',
      '--input': '#97afa5',
      '--ring': '#17594a',
      '--chart-1': '#17594a',
      '--chart-2': '#0f766e',
      '--chart-3': '#15803d',
      '--chart-4': '#6d28d9',
      '--chart-5': '#a16207',
      '--sidebar': '#d7e6d5',
      '--sidebar-foreground': '#18302b',
      '--sidebar-primary': '#17594a',
      '--sidebar-primary-foreground': '#f7fff7',
      '--sidebar-accent': '#c5dcc8',
      '--sidebar-accent-foreground': '#18302b',
      '--sidebar-border': '#719086',
      '--sidebar-ring': '#17594a',
      '--card-border-color': '#719086',
      '--card-shadow': '2px 2px 0 #b8cfbd',
      '--panel-shadow': '4px 4px 0 #c4d8c7',
      '--panel-shadow-dark': '6px 6px 0 #739184',
      '--float-shadow': '6px 6px 0 #b8cfbd',
      '--page-background-start': '#f0f5ea',
      '--page-background-end': '#e3ece0',
      '--page-grid-color': 'rgb(23 89 74 / 0.08)',
      '--app-background-start': '#e8f0e1',
      '--app-background-end': '#dcebdc',
      '--app-effect-color': '#17594a',
      '--card-decoration': '#17594a',
      '--panel-border': '#a9c2ad',
      '--panel-dark-border': '#496d60',
      '--panel-face-start': '#f0f5ea',
      '--panel-face-end': '#e4ede1',
      '--panel-dark-face-start': '#497267',
      '--panel-dark-face-end': '#315b50',
      '--panel-base-border': '#c5d7c8',
      '--panel-base-surface': '#fbfdf8',
      '--panel-base-shadow': '#d8e4d8',
      '--panel-dark-base-border': '#719086',
      '--panel-dark-base-surface': '#cbdccb',
      '--panel-dark-base-shadow': '#aec7b2',
      '--button-primary-border': '#0f3c32',
      '--button-primary-shadow': '#8cad93',
      '--button-primary-hover': '#22715e',
      '--button-outline-border': '#719086',
      '--button-outline-surface': '#f0f5ea',
      '--button-outline-shadow': '#cad8ca',
      '--button-outline-hover': '#d9e9da',
      '--button-ghost-border': '#719086',
      '--button-ghost-hover': '#d7e7d7',
      '--admin-header-background': 'rgb(248 250 244 / 0.9)',
      '--admin-chrome-border': 'rgb(23 89 74 / 0.14)',
      '--admin-account-surface': 'rgb(23 89 74 / 0.07)',
      '--admin-account-muted': '#4d625c',
      '--semantic-info': '#0f766e',
      '--semantic-info-soft': '#ccfbf1',
      '--semantic-info-border': '#5eead4',
      '--semantic-success': '#15803d',
      '--semantic-success-soft': '#dcfce7',
      '--semantic-success-border': '#86efac',
      '--semantic-warning': '#a16207',
      '--semantic-warning-soft': '#fef9c3',
      '--semantic-warning-border': '#fde047',
      '--semantic-danger': '#be123c',
      '--semantic-danger-soft': '#ffe4e6',
      '--semantic-danger-border': '#fda4af',
      '--semantic-neutral': '#4d625c',
      '--semantic-neutral-soft': '#dce9dc',
      '--semantic-neutral-border': '#97afa5',
      '--dialog-overlay': 'rgb(24 48 43 / 0.45)',
      '--dialog-surface': 'rgb(248 250 244 / 0.96)',
      '--cursor-color': '#17594a',
      '--neon-web': '#0f766e',
      '--neon-pwn': '#be185d',
      '--neon-misc': '#6d28d9',
      '--neon-reverse': '#15803d',
      '--neon-mobile': '#c026d3',
      '--neon-crypto': '#a16207',
      '--neon-forensics': '#c2410c',
      '--neon-ai': '#0f766e',
      '--neon-blockchain': '#be185d',
      '--neon-hardware': '#b45309',
      '--neon-osint': '#9f1239',
      '--neon-cloud': '#2563eb',
      '--neon-default': 'var(--neon-misc)',
      '--neon-foreground': '#18302b',
      '--auth-border': '#719086',
      '--auth-surface': '#d7e6d5',
      '--auth-surface-strong': '#c5dcc8',
      '--auth-surface-muted': '#e4ede1',
      '--auth-grid': 'rgb(23 89 74 / 0.14)',
      '--auth-grid-soft': 'rgb(23 89 74 / 0.08)',
      '--auth-background-start': '#e8f0e1',
      '--auth-background-end': '#dcebdc',
      '--auth-foreground': '#18302b',
      '--auth-accent': '#17594a',
      '--auth-accent-soft': '#93c5b4',
      '--auth-muted': '#4d625c',
      '--awdp-surface': '#f8faf4',
      '--awdp-surface-muted': '#e4ede1',
      '--awdp-surface-deep': '#18302b',
      '--awdp-text': '#18302b',
      '--awdp-text-muted': '#4d625c',
      '--awdp-text-inverse': '#f8faf4',
      '--awdp-border': '#a9c2ad',
      '--awdp-star': '#719086',
      '--awdp-nebula-start': '#bdd9c3',
      '--awdp-nebula-mid': '#e0ede0',
      '--awdp-nebula-end': '#f8faf4',
      '--awdp-node-fill': '#f8faf4',
      '--awdp-node-stroke': '#719086',
      '--awdp-category-web': '#0f766e',
      '--awdp-category-pwn': '#be185d',
      '--awdp-category-crypto': '#6d28d9',
      '--awdp-category-reverse': '#15803d',
      '--awdp-category-misc': '#a16207',
      '--leaderboard-paper': '#f8faf4',
      '--leaderboard-border': '#a9c2ad',
      '--leaderboard-line-1': '#b84b46',
      '--leaderboard-line-2': '#17594a',
      '--leaderboard-line-3': '#15803d',
      '--leaderboard-line-4': '#6d28d9',
      '--leaderboard-line-5': '#a16207',
      '--leaderboard-line-6': '#be185d',
      '--leaderboard-line-7': '#0f766e',
      '--leaderboard-line-8': '#ca8a04',
      '--leaderboard-line-9': '#2563eb',
      '--leaderboard-line-10': '#dc2626',
      '--leaderboard-gold': '#eab308',
      '--leaderboard-gold-foreground': '#3f3510',
      '--leaderboard-silver': '#cbd5d1',
      '--leaderboard-silver-foreground': '#18302b',
      '--leaderboard-bronze': '#b77945',
    },
    preview: { background: '#edf2e7', surface: '#f8faf4', primary: '#17594a', accent: '#c8e0ca' },
  },
]
