/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAdministrationPlatformReplaceSsoProviderSecretRequest, serializeNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationPlatformReplaceSsoProviderSecretRequest, type NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse } from '../../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/platform/sso/providers/{providerId}/secret
 */
export interface SecretRequestBuilder extends BaseRequestBuilder<SecretRequestBuilder> {
    /**
     * Replaces an OIDC client secret without returning it.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     put(body: NoCTFAPIEndpointsAdministrationPlatformReplaceSsoProviderSecretRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse | undefined>;
    /**
     * Replaces an OIDC client secret without returning it.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: NoCTFAPIEndpointsAdministrationPlatformReplaceSsoProviderSecretRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SecretRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/platform/sso/providers/{providerId}/secret";
/**
 * Metadata for all the requests in the request builder.
 */
export const SecretRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: SecretRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAdministrationPlatformReplaceSsoProviderSecretRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
