/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AdjustmentsRequestBuilderRequestsMetadata, type AdjustmentsRequestBuilder } from './adjustments/index.js';
// @ts-ignore
import { ColumnsRequestBuilderNavigationMetadata, type ColumnsRequestBuilder } from './columns/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/leaderboard/teams/{teamId}
 */
export interface WithTeamItemRequestBuilder extends BaseRequestBuilder<WithTeamItemRequestBuilder> {
    /**
     * The adjustments property
     */
    get adjustments(): AdjustmentsRequestBuilder;
    /**
     * The columns property
     */
    get columns(): ColumnsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithTeamItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/leaderboard/teams/{teamId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTeamItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithTeamItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    adjustments: {
        requestsMetadata: AdjustmentsRequestBuilderRequestsMetadata,
    },
    columns: {
        navigationMetadata: ColumnsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
