/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RuntimesRequestBuilderNavigationMetadata, RuntimesRequestBuilderRequestsMetadata, type RuntimesRequestBuilder } from './runtimes/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/teams/{teamId}/challenges/{competitionChallengeId}
 */
export interface WithCompetitionChallengeItemRequestBuilder extends BaseRequestBuilder<WithCompetitionChallengeItemRequestBuilder> {
    /**
     * The runtimes property
     */
    get runtimes(): RuntimesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithCompetitionChallengeItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/teams/{teamId}/challenges/{competitionChallengeId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithCompetitionChallengeItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithCompetitionChallengeItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    runtimes: {
        requestsMetadata: RuntimesRequestBuilderRequestsMetadata,
        navigationMetadata: RuntimesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
