/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsChallengesChallengeResponseFromDiscriminatorValue, type NoCTFAPIEndpointsChallengesChallengeResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { AttachmentRequestBuilderRequestsMetadata, type AttachmentRequestBuilder } from './attachment/index.js';
// @ts-ignore
import { AttachmentsRequestBuilderNavigationMetadata, AttachmentsRequestBuilderRequestsMetadata, type AttachmentsRequestBuilder } from './attachments/index.js';
// @ts-ignore
import { AwdpBreakFlagJudgementRequestBuilderRequestsMetadata, type AwdpBreakFlagJudgementRequestBuilder } from './awdpBreakFlagJudgement/index.js';
// @ts-ignore
import { AwdpDefenseTargetsRequestBuilderNavigationMetadata, AwdpDefenseTargetsRequestBuilderRequestsMetadata, type AwdpDefenseTargetsRequestBuilder } from './awdpDefenseTargets/index.js';
// @ts-ignore
import { AwdpStateRequestBuilderRequestsMetadata, type AwdpStateRequestBuilder } from './awdpState/index.js';
// @ts-ignore
import { FlagSubmissionsRequestBuilderRequestsMetadata, type FlagSubmissionsRequestBuilder } from './flagSubmissions/index.js';
// @ts-ignore
import { HintsRequestBuilderNavigationMetadata, type HintsRequestBuilder } from './hints/index.js';
// @ts-ignore
import { PatchVerificationRequestBuilderRequestsMetadata, type PatchVerificationRequestBuilder } from './patchVerification/index.js';
// @ts-ignore
import { PatchVerificationTargetsRequestBuilderNavigationMetadata, PatchVerificationTargetsRequestBuilderRequestsMetadata, type PatchVerificationTargetsRequestBuilder } from './patchVerificationTargets/index.js';
// @ts-ignore
import { RuntimesRequestBuilderNavigationMetadata, RuntimesRequestBuilderRequestsMetadata, type RuntimesRequestBuilder } from './runtimes/index.js';
// @ts-ignore
import { StartRequestBuilderRequestsMetadata, type StartRequestBuilder } from './start/index.js';
// @ts-ignore
import { TargetsRequestBuilderRequestsMetadata, type TargetsRequestBuilder } from './targets/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}
 */
export interface WithCompetitionChallengeItemRequestBuilder extends BaseRequestBuilder<WithCompetitionChallengeItemRequestBuilder> {
    /**
     * The attachment property
     */
    get attachment(): AttachmentRequestBuilder;
    /**
     * The attachments property
     */
    get attachments(): AttachmentsRequestBuilder;
    /**
     * The awdpBreakFlagJudgement property
     */
    get awdpBreakFlagJudgement(): AwdpBreakFlagJudgementRequestBuilder;
    /**
     * The awdpDefenseTargets property
     */
    get awdpDefenseTargets(): AwdpDefenseTargetsRequestBuilder;
    /**
     * The awdpState property
     */
    get awdpState(): AwdpStateRequestBuilder;
    /**
     * The flagSubmissions property
     */
    get flagSubmissions(): FlagSubmissionsRequestBuilder;
    /**
     * The hints property
     */
    get hints(): HintsRequestBuilder;
    /**
     * The patchVerification property
     */
    get patchVerification(): PatchVerificationRequestBuilder;
    /**
     * The patchVerificationTargets property
     */
    get patchVerificationTargets(): PatchVerificationTargetsRequestBuilder;
    /**
     * The runtimes property
     */
    get runtimes(): RuntimesRequestBuilder;
    /**
     * The start property
     */
    get start(): StartRequestBuilder;
    /**
     * The targets property
     */
    get targets(): TargetsRequestBuilder;
    /**
     * Gets a published challenge.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsChallengesChallengeResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsChallengesChallengeResponse | undefined>;
    /**
     * Gets a published challenge.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithCompetitionChallengeItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithCompetitionChallengeItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithCompetitionChallengeItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    attachment: {
        requestsMetadata: AttachmentRequestBuilderRequestsMetadata,
    },
    attachments: {
        requestsMetadata: AttachmentsRequestBuilderRequestsMetadata,
        navigationMetadata: AttachmentsRequestBuilderNavigationMetadata,
    },
    awdpBreakFlagJudgement: {
        requestsMetadata: AwdpBreakFlagJudgementRequestBuilderRequestsMetadata,
    },
    awdpDefenseTargets: {
        requestsMetadata: AwdpDefenseTargetsRequestBuilderRequestsMetadata,
        navigationMetadata: AwdpDefenseTargetsRequestBuilderNavigationMetadata,
    },
    awdpState: {
        requestsMetadata: AwdpStateRequestBuilderRequestsMetadata,
    },
    flagSubmissions: {
        requestsMetadata: FlagSubmissionsRequestBuilderRequestsMetadata,
    },
    hints: {
        navigationMetadata: HintsRequestBuilderNavigationMetadata,
    },
    patchVerification: {
        requestsMetadata: PatchVerificationRequestBuilderRequestsMetadata,
    },
    patchVerificationTargets: {
        requestsMetadata: PatchVerificationTargetsRequestBuilderRequestsMetadata,
        navigationMetadata: PatchVerificationTargetsRequestBuilderNavigationMetadata,
    },
    runtimes: {
        requestsMetadata: RuntimesRequestBuilderRequestsMetadata,
        navigationMetadata: RuntimesRequestBuilderNavigationMetadata,
    },
    start: {
        requestsMetadata: StartRequestBuilderRequestsMetadata,
    },
    targets: {
        requestsMetadata: TargetsRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithCompetitionChallengeItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithCompetitionChallengeItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsChallengesChallengeResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
