apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- storageclass.yaml
patches:
- target:
    kind: Deployment
    name: backend
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: Deployment
    name: worker
  patch: '[{"op": "replace", "path": "/spec/replicas", "value": 2}]'
- target:
    kind: ConfigMap
    name: noctf-config
  patch: "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: noctf-config\n  namespace:\
    \ noctf\ndata:\n  Runtime__Kubernetes__ImagePullSecrets__0: challenge-registry\n\
    \  Runner__Admission__MainStartupConcurrency: '8'\n  Runner__Admission__AuxiliaryConcurrency:\
    \ '4'\n"
- target:
    kind: PersistentVolumeClaim
  patch: "- op: add\n  path: /spec/storageClassName\n  value: noctf-retain\n"
