/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsNotificationsNotificationListResponseFromDiscriminatorValue, NoCTFAPIEndpointsNotificationsNotificationListScopeProtocol, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsNotificationsNotificationListResponse } from '../../../models/index.js';
// @ts-ignore
import { FeedRequestBuilderRequestsMetadata, type FeedRequestBuilder } from './feed/index.js';
// @ts-ignore
import { type WithNotificationItemRequestBuilder, WithNotificationItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/notifications
 */
export interface NotificationsRequestBuilder extends BaseRequestBuilder<NotificationsRequestBuilder> {
    /**
     * The feed property
     */
    get feed(): FeedRequestBuilder;
    /**
     * Gets an item from the NoCTF.api.v1.notifications.item collection
     * @param notificationId Unique identifier of the item
     * @returns {WithNotificationItemRequestBuilder}
     */
     byNotificationId(notificationId: string) : WithNotificationItemRequestBuilder;
    /**
     * Returns the current user's immutable notification event stream.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsNotificationsNotificationListResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<NotificationsRequestBuilderGetQueryParameters> | undefined) : Promise<NoCTFAPIEndpointsNotificationsNotificationListResponse | undefined>;
    /**
     * Returns the current user's immutable notification event stream.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<NotificationsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns the current user's immutable notification event stream.
 */
export interface NotificationsRequestBuilderGetQueryParameters {
    competitionId?: Guid;
    desc?: boolean;
    limit?: number;
    offset?: number;
    scope?: NoCTFAPIEndpointsNotificationsNotificationListScopeProtocol;
}
/**
 * Uri template for the request builder.
 */
export const NotificationsRequestBuilderUriTemplate = "{+baseurl}/api/v1/notifications?desc={desc}&limit={limit}&offset={offset}&scope={scope}{&competitionId*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const NotificationsRequestBuilderNavigationMetadata: Record<Exclude<keyof NotificationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byNotificationId: {
        navigationMetadata: WithNotificationItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["notificationId"],
    },
    feed: {
        requestsMetadata: FeedRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const NotificationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: NotificationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsNotificationsNotificationListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
