/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue, createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsGameplayFactsUploadPatchFailureResponseFromDiscriminatorValue, createNoCTFAPIEndpointsGameplayFactsUploadPatchResponseFromDiscriminatorValue, type MicrosoftAspNetCoreMvcProblemDetails, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsGameplayFactsUploadPatchFailureResponse, type NoCTFAPIEndpointsGameplayFactsUploadPatchResponse } from '../../../../../../../../../models/index.js';
// @ts-ignore
import { MultipartBody, serializeMultipartBody, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/awdp-defense-targets/{runtimeInstanceId}/fix
 */
export interface FixRequestBuilder extends BaseRequestBuilder<FixRequestBuilder> {
    /**
     * Atomically binds one archive and one Fix attempt to the clean disposable target. Verification starts immediately when the target is running, or automatically after provisioning completes.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsGameplayFactsUploadPatchResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 403 status code
     * @throws {NoCTFAPIEndpointsGameplayFactsUploadPatchFailureResponse} error when the service returns a 409 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 413 status code
     * @throws {NoCTFAPIEndpointsGameplayFactsUploadPatchFailureResponse} error when the service returns a 422 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 503 status code
     */
     post(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsGameplayFactsUploadPatchResponse | undefined>;
    /**
     * Atomically binds one archive and one Fix attempt to the clean disposable target. Verification starts immediately when the target is running, or automatically after provisioning completes.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FixRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/awdp-defense-targets/{runtimeInstanceId}/fix";
/**
 * Metadata for all the requests in the request builder.
 */
export const FixRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: FixRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsGameplayFactsUploadPatchFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            413: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createNoCTFAPIEndpointsGameplayFactsUploadPatchFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            503: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsGameplayFactsUploadPatchResponseFromDiscriminatorValue,
        requestBodyContentType: "multipart/form-data",
        requestBodySerializer: serializeMultipartBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
