/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsRuntimeRuntimeAcceptedResponseFromDiscriminatorValue, createNoCTFAPIEndpointsRuntimeRuntimeConflictResponseFromDiscriminatorValue, type NoCTFAPIEndpointsRuntimeRuntimeAcceptedResponse, type NoCTFAPIEndpointsRuntimeRuntimeConflictResponse } from '../../../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/challenges/{competitionChallengeId}/runtimes/{runtimeInstanceId}
 */
export interface WithRuntimeInstanceItemRequestBuilder extends BaseRequestBuilder<WithRuntimeInstanceItemRequestBuilder> {
    /**
     * Stops the shared hill through the durable runtime cleanup state machine.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsRuntimeRuntimeAcceptedResponse>}
     * @throws {NoCTFAPIEndpointsRuntimeRuntimeConflictResponse} error when the service returns a 409 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsRuntimeRuntimeAcceptedResponse | undefined>;
    /**
     * Stops the shared hill through the durable runtime cleanup state machine.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithRuntimeInstanceItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/challenges/{competitionChallengeId}/runtimes/{runtimeInstanceId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithRuntimeInstanceItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithRuntimeInstanceItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            409: createNoCTFAPIEndpointsRuntimeRuntimeConflictResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsRuntimeRuntimeAcceptedResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
