/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithColumnIndexItemRequestBuilder, WithColumnIndexItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/leaderboard/teams/{teamId}/columns
 */
export interface ColumnsRequestBuilder extends BaseRequestBuilder<ColumnsRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.competitions.item.leaderboard.teams.item.columns.item collection
     * @param columnIndex Unique identifier of the item
     * @returns {WithColumnIndexItemRequestBuilder}
     */
     byColumnIndex(columnIndex: number) : WithColumnIndexItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ColumnsRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/leaderboard/teams/{teamId}/columns";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ColumnsRequestBuilderNavigationMetadata: Record<Exclude<keyof ColumnsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byColumnIndex: {
        requestsMetadata: WithColumnIndexItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["columnIndex"],
    },
};
/* tslint:enable */
/* eslint-enable */
