/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/traffic-captures/{runtimeInstanceId}/file
 */
export interface FileRequestBuilder extends BaseRequestBuilder<FileRequestBuilder> {
    /**
     * Downloads one Runtime PCAPNG capture.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Downloads one Runtime PCAPNG capture.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FileRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/traffic-captures/{runtimeInstanceId}/file";
/**
 * Metadata for all the requests in the request builder.
 */
export const FileRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FileRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.tcpdump.pcap",
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
