export const queryKeys = {
  platformConfiguration: ['platform-configuration'] as const,
  adminPlatformConfiguration: ['admin-platform-configuration'] as const,
  adminPlatformInformation: ['admin-platform-information'] as const,
  currentUser: ['current-user'] as const,
  notifications: ['notifications'] as const,
  competitions: ['competitions'] as const,
  competition: (id: string) => ['competition', id] as const,
  challenges: (competitionId: string) => ['challenges', competitionId] as const,
  challenge: (
    competitionId: string,
    competitionChallengeId: string,
  ) => ['challenge', competitionId, competitionChallengeId] as const,
  challengeAttachments: (
    competitionId: string,
    competitionChallengeId: string,
  ) => ['challenge-attachments', competitionId, competitionChallengeId] as const,
  submissions: (competitionId: string) => ['submissions', competitionId] as const,
  submission: (
    competitionId: string,
    submissionId: string,
  ) => ['submission', competitionId, submissionId] as const,
  leaderboard: (competitionId: string) => ['leaderboard', competitionId] as const,
  awdpState: (competitionId: string) => ['awdp-state', competitionId] as const,
  awdpScreen: (gameId: string) => ['awdp-screen', gameId] as const,
  teams: (competitionId: string) => ['teams', competitionId] as const,
  myTeams: ['my-teams'] as const,
  myCompetitionTeam: (competitionId: string) => ['my-competition-team', competitionId] as const,
  patchSubmissions: (competitionId: string) => ['patch-submissions', competitionId] as const,
  adminCompetitions: ['admin-competitions'] as const,
  adminCompetition: (id: string) => ['admin-competition', id] as const,
  adminCompetitionSummary: (id: string) => ['admin-competition-summary', id] as const,
  adminCompetitionChallenges: (id: string) => ['admin-competition-challenges', id] as const,
  adminCompetitionChallenge: (
    competitionId: string,
    competitionChallengeId: string,
    includeDeleted: boolean,
  ) => ['admin-competition-challenge', competitionId, competitionChallengeId, includeDeleted] as const,
  adminCompetitionPermissions: (id: string) => ['admin-competition-permissions', id] as const,
  adminCompetitionPermissionCandidates: (id: string) => ['admin-competition-permission-candidates', id] as const,
  adminCompetitionTeams: (id: string) => ['admin-competition-teams', id] as const,
  adminCompetitionRuntimes: (id: string) => ['admin-competition-runtimes', id] as const,
  adminCompetitionLogs: (id: string) => ['admin-competition-logs', id] as const,
  adminCompetitionCheatIncidents: (id: string) => ['admin-competition-cheat-incidents', id] as const,
  adminUsers: ['admin-users'] as const,
  adminTeams: ['admin-teams'] as const,
  adminChallenges: ['admin-challenges'] as const,
  adminChallenge: (id: string) => ['admin-challenge', id] as const,
  adminContainers: ['admin-containers'] as const,
  adminPlugins: ['admin-plugins'] as const,
  adminHealth: ['admin-health'] as const,
  adminLogs: ['admin-logs'] as const,
  adminAuditLogs: (page: number, filters: unknown) => ['admin-audit-logs', page, filters] as const,
}
