export const queryKeys = {
  competitions: ['competitions'] as const,
  competition: (id: string) => ['competition', id] as const,
  challenges: (competitionId: string) => ['challenges', competitionId] as const,
  submissions: (competitionId: string) => ['submissions', competitionId] as const,
  leaderboard: (competitionId: string) => ['leaderboard', competitionId] as const,
  awdDashboard: (competitionId: string) => ['awd-dashboard', competitionId] as const,
  awdpState: (competitionId: string) => ['awdp-state', competitionId] as const,
  awdpScreen: (gameId: string) => ['awdp-screen', gameId] as const,
  kohDashboard: (competitionId: string) => ['koh-dashboard', competitionId] as const,
  teams: (competitionId?: string) => competitionId ? ['teams', competitionId] as const : ['teams'] as const,
  myTeams: ['my-teams'] as const,
  myCompetitionTeams: (competitionId: string) => ['my-competition-teams', competitionId] as const,
  patchSubmissions: (competitionId: string) => ['patch-submissions', competitionId] as const,
  penetrationDetail: (competitionId: string, challengeId: string) => ['penetration-detail', competitionId, challengeId] as const,
  adminCompetitions: ['admin-competitions'] as const,
  adminCompetition: (id: string) => ['admin-competition', id] as const,
  adminCompetitionChallenges: (id: string) => ['admin-competition-challenges', id] as const,
  adminPenetrationTemplateTopology: (id: string) => ['admin-penetration-template-topology', id] as const,
  adminCompetitionPenetrationTopology: (competitionId: string, challengeId: string) => ['admin-competition-penetration-topology', competitionId, challengeId] as const,
  adminPenetrationInstances: (competitionId: string, filters?: unknown) => ['admin-penetration-instances', competitionId, filters ?? 'all'] as const,
  adminCompetitionTeams: (id: string) => ['admin-competition-teams', id] as const,
  adminCompetitionLogs: (id: string) => ['admin-competition-logs', id] as const,
  adminCompetitionCheatIncidents: (id: string) => ['admin-competition-cheat-incidents', id] as const,
  adminUsers: ['admin-users'] as const,
  adminTeams: ['admin-teams'] as const,
  adminChallenges: ['admin-challenges'] as const,
  adminCollaborators: (competitionId?: string) => ['admin-collaborators', competitionId ?? 'all'] as const,
  adminContainers: ['admin-containers'] as const,
  adminPlugins: ['admin-plugins'] as const,
  adminInfrastructure: ['admin-infrastructure'] as const,
  adminHealth: ['admin-health'] as const,
  adminLogs: ['admin-logs'] as const,
  adminAuditLogs: (page: number, filters: unknown) => ['admin-audit-logs', page, filters] as const,
}
