/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationCheatIncidentsCheatIncidentListResponseFromDiscriminatorValue, NoCTFAPIEndpointsAdministrationCheatIncidentsCheatIncidentStatusProtocol, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationCheatIncidentsCheatIncidentListResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type WithGameplayFactItemRequestBuilder, WithGameplayFactItemRequestBuilderNavigationMetadata, WithGameplayFactItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/cheat-incidents
 */
export interface CheatIncidentsRequestBuilder extends BaseRequestBuilder<CheatIncidentsRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.admin.competitions.item.cheatIncidents.item collection
     * @param gameplayFactId Unique identifier of the item
     * @returns {WithGameplayFactItemRequestBuilder}
     */
     byGameplayFactId(gameplayFactId: Guid) : WithGameplayFactItemRequestBuilder;
    /**
     * Observer and above may list redacted evidence. Only current scoring facts and immutable adjudication events are used.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationCheatIncidentsCheatIncidentListResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<CheatIncidentsRequestBuilderGetQueryParameters> | undefined) : Promise<NoCTFAPIEndpointsAdministrationCheatIncidentsCheatIncidentListResponse | undefined>;
    /**
     * Observer and above may list redacted evidence. Only current scoring facts and immutable adjudication events are used.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CheatIncidentsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Observer and above may list redacted evidence. Only current scoring facts and immutable adjudication events are used.
 */
export interface CheatIncidentsRequestBuilderGetQueryParameters {
    competitionChallengeId?: Guid;
    cursor?: string;
    from?: Date;
    limit?: number;
    ownerTeamId?: Guid;
    sourceTeamId?: Guid;
    status?: NoCTFAPIEndpointsAdministrationCheatIncidentsCheatIncidentStatusProtocol;
    to?: Date;
    userId?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const CheatIncidentsRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/cheat-incidents?from={from}&limit={limit}&to={to}{&competitionChallengeId*,cursor*,ownerTeamId*,sourceTeamId*,status*,userId*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CheatIncidentsRequestBuilderNavigationMetadata: Record<Exclude<keyof CheatIncidentsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byGameplayFactId: {
        requestsMetadata: WithGameplayFactItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithGameplayFactItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["gameplayFactId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CheatIncidentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CheatIncidentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationCheatIncidentsCheatIncidentListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
