/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAuthenticationMySsoBindingConfigurationResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAuthenticationMySsoBindingConfigurationResponse } from '../../../../../models/index.js';
// @ts-ignore
import { FlowsRequestBuilderNavigationMetadata, FlowsRequestBuilderRequestsMetadata, type FlowsRequestBuilder } from './flows/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/me/sso-binding
 */
export interface SsoBindingRequestBuilder extends BaseRequestBuilder<SsoBindingRequestBuilder> {
    /**
     * The flows property
     */
    get flows(): FlowsRequestBuilder;
    /**
     * Removes the authenticated user's external identity binding and revokes current sessions.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Returns the current user's external identity binding and bindable providers.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationMySsoBindingConfigurationResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationMySsoBindingConfigurationResponse | undefined>;
    /**
     * Removes the authenticated user's external identity binding and revokes current sessions.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Returns the current user's external identity binding and bindable providers.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SsoBindingRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/me/sso-binding";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SsoBindingRequestBuilderNavigationMetadata: Record<Exclude<keyof SsoBindingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    flows: {
        requestsMetadata: FlowsRequestBuilderRequestsMetadata,
        navigationMetadata: FlowsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SsoBindingRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: SsoBindingRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: SsoBindingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationMySsoBindingConfigurationResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
