<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../NoCTF.Application/NoCTF.Application.csproj" />
    <ProjectReference Include="../NoCTF.Domain/NoCTF.Domain.csproj" />
    <ProjectReference Include="../NoCTF.Infrastructure/NoCTF.Infrastructure.csproj" />
    <ProjectReference Include="../NoCTF.Hosting/NoCTF.Hosting.csproj" />
    <ProjectReference Include="../NoCTF.Runtime.Docker/NoCTF.Runtime.Docker.csproj" />
    <ProjectReference Include="../NoCTF.Runtime.Kubernetes/NoCTF.Runtime.Kubernetes.csproj" />
    <ProjectReference Include="../NoCTF.Runtime.Libvirt/NoCTF.Runtime.Libvirt.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AsyncKeyedLock" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.Postgresql" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>
</Project>
