/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithProviderItemRequestBuilder, WithProviderItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/sso/callback/cas
 */
export interface CasRequestBuilder extends BaseRequestBuilder<CasRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.auth.sso.callback.cas.item collection
     * @param providerId Unique identifier of the item
     * @returns {WithProviderItemRequestBuilder}
     */
     byProviderId(providerId: Guid) : WithProviderItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CasRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/sso/callback/cas";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CasRequestBuilderNavigationMetadata: Record<Exclude<keyof CasRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byProviderId: {
        requestsMetadata: WithProviderItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["providerId"],
    },
};
/* tslint:enable */
/* eslint-enable */
