<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>$(NoWarn);NU1608</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NoCTF.Application/NoCTF.Application.csproj" />
    <ProjectReference Include="../NoCTF.Domain/NoCTF.Domain.csproj" />
    <ProjectReference Include="../NoCTF.GameModes/NoCTF.GameModes.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.Postgresql" />
    <PackageReference Include="ZiggyCreatures.FusionCache" />
    <PackageReference Include="ZiggyCreatures.FusionCache.Backplane.StackExchangeRedis" />
    <PackageReference Include="ZiggyCreatures.FusionCache.Serialization.SystemTextJson" />
  </ItemGroup>
</Project>
