<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>$(NoWarn);NU1608</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NoCTF.Application/NoCTF.Application.csproj" />
    <ProjectReference Include="../NoCTF.Domain/NoCTF.Domain.csproj" />
    <ProjectReference Include="../NoCTF.GameModes/NoCTF.GameModes.csproj" />
    <ProjectReference Include="../NoCTF.Integrations.QQBot/NoCTF.Integrations.QQBot.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Marten" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.Marten" />
    <PackageReference Include="WolverineFx.Postgresql" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>
</Project>
