/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionFailureResponseFromDiscriminatorValue, createNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionListResponseFromDiscriminatorValue, createNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponseFromDiscriminatorValue, NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionStatusCode, NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionSubjectCode, serializeNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponse, serializeNoCTFAPIEndpointsChallengesQuestionsCreateCompetitionQuestionRequest, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionFailureResponse, type NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionListResponse, type NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponse, type NoCTFAPIEndpointsChallengesQuestionsCreateCompetitionQuestionRequest } from '../../../../../models/index.js';
// @ts-ignore
import { type WithThreadRootItemRequestBuilder, WithThreadRootItemRequestBuilderNavigationMetadata, WithThreadRootItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/questions
 */
export interface QuestionsRequestBuilder extends BaseRequestBuilder<QuestionsRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.competitions.item.questions.item collection
     * @param threadRootId Unique identifier of the item
     * @returns {WithThreadRootItemRequestBuilder}
     */
     byThreadRootId(threadRootId: string) : WithThreadRootItemRequestBuilder;
    /**
     * The asker receives their own threads; observers receive read-only projections and handlers receive their authorized queue.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionListResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<QuestionsRequestBuilderGetQueryParameters> | undefined) : Promise<NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionListResponse | undefined>;
    /**
     * Challenge questions target one published CompetitionChallenge; platform questions target competition management. Attachments are not accepted and an optional GameplayFact is referenced without copying its protected content.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionFailureResponse} error when the service returns a 409 status code
     * @throws {NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionFailureResponse} error when the service returns a 422 status code
     */
     post(body: NoCTFAPIEndpointsChallengesQuestionsCreateCompetitionQuestionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponse | undefined>;
    /**
     * The asker receives their own threads; observers receive read-only projections and handlers receive their authorized queue.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<QuestionsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Challenge questions target one published CompetitionChallenge; platform questions target competition management. Attachments are not accepted and an optional GameplayFact is referenced without copying its protected content.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsChallengesQuestionsCreateCompetitionQuestionRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * The asker receives their own threads; observers receive read-only projections and handlers receive their authorized queue.
 */
export interface QuestionsRequestBuilderGetQueryParameters {
    competitionChallengeId?: Guid;
    cursor?: string;
    limit?: number;
    status?: NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionStatusCode;
    subject?: NoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionSubjectCode;
}
/**
 * Uri template for the request builder.
 */
export const QuestionsRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/questions?limit={limit}{&competitionChallengeId*,cursor*,status*,subject*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const QuestionsRequestBuilderNavigationMetadata: Record<Exclude<keyof QuestionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byThreadRootId: {
        requestsMetadata: WithThreadRootItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithThreadRootItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["threadRootId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const QuestionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: QuestionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: QuestionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsChallengesQuestionsCompetitionQuestionResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsChallengesQuestionsCreateCompetitionQuestionRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
