/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAuthenticationBeginSsoLoginResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAuthenticationBeginSsoLoginResponse } from '../../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/platform/sso/providers/{providerId}/authentication-tests
 */
export interface AuthenticationTestsRequestBuilder extends BaseRequestBuilder<AuthenticationTestsRequestBuilder> {
    /**
     * Starts a browser authentication test without creating a binding or platform session.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationBeginSsoLoginResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationBeginSsoLoginResponse | undefined>;
    /**
     * Starts a browser authentication test without creating a binding or platform session.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AuthenticationTestsRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/platform/sso/providers/{providerId}/authentication-tests";
/**
 * Metadata for all the requests in the request builder.
 */
export const AuthenticationTestsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AuthenticationTestsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationBeginSsoLoginResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
