/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationChallengeBankChallengeTestRuntimeAcceptedResponseFromDiscriminatorValue, createNoCTFAPIEndpointsRuntimeRuntimeConflictResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAdministrationChallengeBankChallengeTestRuntimeAcceptedResponse, serializeNoCTFAPIEndpointsAdministrationChallengeBankCreateChallengeTestRuntimeRequest, type FastEndpointsErrorResponse, type NoCTFAPIEndpointsAdministrationChallengeBankChallengeTestRuntimeAcceptedResponse, type NoCTFAPIEndpointsAdministrationChallengeBankCreateChallengeTestRuntimeRequest, type NoCTFAPIEndpointsRuntimeRuntimeConflictResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { CurrentRequestBuilderRequestsMetadata, type CurrentRequestBuilder } from './current/index.js';
// @ts-ignore
import { type WithRuntimeInstanceItemRequestBuilder, WithRuntimeInstanceItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/challenges/{challengeId}/test-runtimes
 */
export interface TestRuntimesRequestBuilder extends BaseRequestBuilder<TestRuntimesRequestBuilder> {
    /**
     * The current property
     */
    get current(): CurrentRequestBuilder;
    /**
     * Gets an item from the NoCTF.api.v1.admin.challenges.item.testRuntimes.item collection
     * @param runtimeInstanceId Unique identifier of the item
     * @returns {WithRuntimeInstanceItemRequestBuilder}
     */
     byRuntimeInstanceId(runtimeInstanceId: string) : WithRuntimeInstanceItemRequestBuilder;
    /**
     * Creates or replaces a challenge-template test Runtime.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationChallengeBankChallengeTestRuntimeAcceptedResponse>}
     * @throws {NoCTFAPIEndpointsRuntimeRuntimeConflictResponse} error when the service returns a 409 status code
     * @throws {FastEndpointsErrorResponse} error when the service returns a 503 status code
     */
     post(body: NoCTFAPIEndpointsAdministrationChallengeBankCreateChallengeTestRuntimeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationChallengeBankChallengeTestRuntimeAcceptedResponse | undefined>;
    /**
     * Creates or replaces a challenge-template test Runtime.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsAdministrationChallengeBankCreateChallengeTestRuntimeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TestRuntimesRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/challenges/{challengeId}/test-runtimes";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TestRuntimesRequestBuilderNavigationMetadata: Record<Exclude<keyof TestRuntimesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byRuntimeInstanceId: {
        requestsMetadata: WithRuntimeInstanceItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["runtimeInstanceId"],
    },
    current: {
        requestsMetadata: CurrentRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TestRuntimesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TestRuntimesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            409: createNoCTFAPIEndpointsRuntimeRuntimeConflictResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            503: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationChallengeBankChallengeTestRuntimeAcceptedResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAdministrationChallengeBankCreateChallengeTestRuntimeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
