/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsRuntimeRuntimeAcceptedResponseFromDiscriminatorValue, createNoCTFAPIEndpointsRuntimeRuntimeConflictResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAdministrationRuntimeCreateForceTerminationRequest, serializeNoCTFAPIEndpointsRuntimeRuntimeAcceptedResponse, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationRuntimeCreateForceTerminationRequest, type NoCTFAPIEndpointsRuntimeRuntimeAcceptedResponse, type NoCTFAPIEndpointsRuntimeRuntimeConflictResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/runtimes/{runtimeInstanceId}/force-terminations
 */
export interface ForceTerminationsRequestBuilder extends BaseRequestBuilder<ForceTerminationsRequestBuilder> {
    /**
     * Creates a force-termination request for a stuck Runtime.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsRuntimeRuntimeAcceptedResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {NoCTFAPIEndpointsRuntimeRuntimeConflictResponse} error when the service returns a 409 status code
     */
     post(body: NoCTFAPIEndpointsAdministrationRuntimeCreateForceTerminationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsRuntimeRuntimeAcceptedResponse | undefined>;
    /**
     * Creates a force-termination request for a stuck Runtime.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsAdministrationRuntimeCreateForceTerminationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ForceTerminationsRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/runtimes/{runtimeInstanceId}/force-terminations";
/**
 * Metadata for all the requests in the request builder.
 */
export const ForceTerminationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ForceTerminationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsRuntimeRuntimeConflictResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsRuntimeRuntimeAcceptedResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAdministrationRuntimeCreateForceTerminationRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
