/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAuthenticationChangePasswordFailureResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAuthenticationChangePasswordRequest, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAuthenticationChangePasswordFailureResponse, type NoCTFAPIEndpointsAuthenticationChangePasswordRequest } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/password
 */
export interface PasswordRequestBuilder extends BaseRequestBuilder<PasswordRequestBuilder> {
    /**
     * Rehashes the password and invalidates all existing tokens.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {NoCTFAPIEndpointsAuthenticationChangePasswordFailureResponse} error when the service returns a 409 status code
     */
     put(body: NoCTFAPIEndpointsAuthenticationChangePasswordRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Rehashes the password and invalidates all existing tokens.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: NoCTFAPIEndpointsAuthenticationChangePasswordRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PasswordRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/password";
/**
 * Metadata for all the requests in the request builder.
 */
export const PasswordRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: PasswordRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, application/problem+json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsAuthenticationChangePasswordFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAuthenticationChangePasswordRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
