/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAdministrationRuntimeAdminRuntimeResponseFromDiscriminatorValue, createNoCTFAPIEndpointsRuntimeRuntimeAcceptedResponseFromDiscriminatorValue, createNoCTFAPIEndpointsRuntimeRuntimeConflictResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAdministrationRuntimeAdminRuntimeResponse, type NoCTFAPIEndpointsRuntimeRuntimeAcceptedResponse, type NoCTFAPIEndpointsRuntimeRuntimeConflictResponse } from '../../../../../models/index.js';
// @ts-ignore
import { FlagsRequestBuilderRequestsMetadata, type FlagsRequestBuilder } from './flags/index.js';
// @ts-ignore
import { ForceTerminationsRequestBuilderRequestsMetadata, type ForceTerminationsRequestBuilder } from './forceTerminations/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/runtimes/{runtimeInstanceId}
 */
export interface WithRuntimeInstanceItemRequestBuilder extends BaseRequestBuilder<WithRuntimeInstanceItemRequestBuilder> {
    /**
     * The flags property
     */
    get flags(): FlagsRequestBuilder;
    /**
     * The forceTerminations property
     */
    get forceTerminations(): ForceTerminationsRequestBuilder;
    /**
     * Terminates an authorized Runtime instance.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsRuntimeRuntimeAcceptedResponse>}
     * @throws {NoCTFAPIEndpointsRuntimeRuntimeConflictResponse} error when the service returns a 409 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsRuntimeRuntimeAcceptedResponse | undefined>;
    /**
     * Includes provider receipt and internal failure diagnostics hidden from players.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationRuntimeAdminRuntimeResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationRuntimeAdminRuntimeResponse | undefined>;
    /**
     * Terminates an authorized Runtime instance.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Includes provider receipt and internal failure diagnostics hidden from players.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithRuntimeInstanceItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/runtimes/{runtimeInstanceId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithRuntimeInstanceItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithRuntimeInstanceItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    flags: {
        requestsMetadata: FlagsRequestBuilderRequestsMetadata,
    },
    forceTerminations: {
        requestsMetadata: ForceTerminationsRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithRuntimeInstanceItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithRuntimeInstanceItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            409: createNoCTFAPIEndpointsRuntimeRuntimeConflictResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsRuntimeRuntimeAcceptedResponseFromDiscriminatorValue,
    },
    get: {
        uriTemplate: WithRuntimeInstanceItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationRuntimeAdminRuntimeResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
