/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionPermissionCandidateListResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAdministrationCompetitionsCompetitionPermissionCandidateListResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/permission-candidates
 */
export interface PermissionCandidatesRequestBuilder extends BaseRequestBuilder<PermissionCandidatesRequestBuilder> {
    /**
     * Returns a resource-scoped, minimal user projection only to the competition owner or a platform administrator.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionPermissionCandidateListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionPermissionCandidateListResponse | undefined>;
    /**
     * Returns a resource-scoped, minimal user projection only to the competition owner or a platform administrator.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PermissionCandidatesRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/permission-candidates";
/**
 * Metadata for all the requests in the request builder.
 */
export const PermissionCandidatesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PermissionCandidatesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionPermissionCandidateListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
