/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue, createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsGameplayFactsAwdpBreakFlagJudgementConflictResponseFromDiscriminatorValue, createNoCTFAPIEndpointsGameplayFactsAwdpBreakFlagJudgementResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsGameplayFactsAwdpBreakFlagJudgementResponse, serializeNoCTFAPIEndpointsGameplayFactsJudgeAwdpBreakFlagRequest, type MicrosoftAspNetCoreMvcProblemDetails, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsGameplayFactsAwdpBreakFlagJudgementConflictResponse, type NoCTFAPIEndpointsGameplayFactsAwdpBreakFlagJudgementResponse, type NoCTFAPIEndpointsGameplayFactsJudgeAwdpBreakFlagRequest } from '../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/awdp-break-flag-judgement
 */
export interface AwdpBreakFlagJudgementRequestBuilder extends BaseRequestBuilder<AwdpBreakFlagJudgementRequestBuilder> {
    /**
     * Returns only correctness. It never creates GameplayFact, score, event, notification, cheat incident or Runtime changes.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsGameplayFactsAwdpBreakFlagJudgementResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 403 status code
     * @throws {NoCTFAPIEndpointsGameplayFactsAwdpBreakFlagJudgementConflictResponse} error when the service returns a 409 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 503 status code
     */
     post(body: NoCTFAPIEndpointsGameplayFactsJudgeAwdpBreakFlagRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsGameplayFactsAwdpBreakFlagJudgementResponse | undefined>;
    /**
     * Returns only correctness. It never creates GameplayFact, score, event, notification, cheat incident or Runtime changes.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsGameplayFactsJudgeAwdpBreakFlagRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AwdpBreakFlagJudgementRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/awdp-break-flag-judgement";
/**
 * Metadata for all the requests in the request builder.
 */
export const AwdpBreakFlagJudgementRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AwdpBreakFlagJudgementRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsGameplayFactsAwdpBreakFlagJudgementConflictResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            503: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsGameplayFactsAwdpBreakFlagJudgementResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsGameplayFactsJudgeAwdpBreakFlagRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
