/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionHardDeletePreviewResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAdministrationCompetitionsCompetitionHardDeletePreviewResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/hard-delete
 */
export interface HardDeleteRequestBuilder extends BaseRequestBuilder<HardDeleteRequestBuilder> {
    /**
     * Historical competition events and all other reported references block physical deletion. Soft deletion is a separate operation and is not a prerequisite.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {NoCTFAPIEndpointsAdministrationCompetitionsCompetitionHardDeletePreviewResponse} error when the service returns a 409 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Historical competition events and all other reported references block physical deletion. Soft deletion is a separate operation and is not a prerequisite.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const HardDeleteRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/hard-delete";
/**
 * Metadata for all the requests in the request builder.
 */
export const HardDeleteRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: HardDeleteRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            409: createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionHardDeletePreviewResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
};
/* tslint:enable */
/* eslint-enable */
