/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, serializeNoCTFAPIEndpointsAdministrationCheatIncidentsUpdateCheatIncidentStatusRequest, type FastEndpointsErrorResponse, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationCheatIncidentsUpdateCheatIncidentStatusRequest } from '../../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/cheat-incidents/{gameplayFactId}/status
 */
export interface StatusRequestBuilder extends BaseRequestBuilder<StatusRequestBuilder> {
    /**
     * Updates a cheat incident status.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {FastEndpointsErrorResponse} error when the service returns a 409 status code
     */
     put(body: NoCTFAPIEndpointsAdministrationCheatIncidentsUpdateCheatIncidentStatusRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Updates a cheat incident status.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: NoCTFAPIEndpointsAdministrationCheatIncidentsUpdateCheatIncidentStatusRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StatusRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/cheat-incidents/{gameplayFactId}/status";
/**
 * Metadata for all the requests in the request builder.
 */
export const StatusRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: StatusRequestBuilderUriTemplate,
        responseBodyContentType: "application/problem+json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAdministrationCheatIncidentsUpdateCheatIncidentStatusRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
