/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTeamItemRequestBuilder, WithTeamItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/leaderboard/teams
 */
export interface TeamsRequestBuilder extends BaseRequestBuilder<TeamsRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.competitions.item.leaderboard.teams.item collection
     * @param teamId Unique identifier of the item
     * @returns {WithTeamItemRequestBuilder}
     */
     byTeamId(teamId: Guid) : WithTeamItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TeamsRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/leaderboard/teams";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TeamsRequestBuilderNavigationMetadata: Record<Exclude<keyof TeamsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTeamId: {
        navigationMetadata: WithTeamItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["teamId"],
    },
};
/* tslint:enable */
/* eslint-enable */
