/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTeamItemRequestBuilder, WithTeamItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/writeup-previews/{competitionId}
 */
export interface WithCompetitionItemRequestBuilder extends BaseRequestBuilder<WithCompetitionItemRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.writeupPreviews.item.item collection
     * @param teamId Unique identifier of the item
     * @returns {WithTeamItemRequestBuilder}
     */
     byTeamId(teamId: string) : WithTeamItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithCompetitionItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/writeup-previews/{competitionId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithCompetitionItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithCompetitionItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTeamId: {
        requestsMetadata: WithTeamItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["teamId"],
    },
};
/* tslint:enable */
/* eslint-enable */
