/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAuthenticationPublicSsoProviderListResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAuthenticationPublicSsoProviderListResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/sso/providers
 */
export interface ProvidersRequestBuilder extends BaseRequestBuilder<ProvidersRequestBuilder> {
    /**
     * Lists enabled SSO providers that allow platform login.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationPublicSsoProviderListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationPublicSsoProviderListResponse | undefined>;
    /**
     * Lists enabled SSO providers that allow platform login.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProvidersRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/sso/providers";
/**
 * Metadata for all the requests in the request builder.
 */
export const ProvidersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProvidersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationPublicSsoProviderListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
