/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/platform/users/{userId}/sso-binding
 */
export interface SsoBindingRequestBuilder extends BaseRequestBuilder<SsoBindingRequestBuilder> {
    /**
     * Removes a user's external identity binding and revokes their sessions.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Removes a user's external identity binding and revokes their sessions.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SsoBindingRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/platform/users/{userId}/sso-binding";
/**
 * Metadata for all the requests in the request builder.
 */
export const SsoBindingRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: SsoBindingRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
};
/* tslint:enable */
/* eslint-enable */
