/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsGameplayFactsAwdpDefenseTargetConflictResponseFromDiscriminatorValue, createNoCTFAPIEndpointsGameplayFactsRequestAwdpDefenseTargetResponseFromDiscriminatorValue, type MicrosoftAspNetCoreMvcProblemDetails, type NoCTFAPIEndpointsGameplayFactsAwdpDefenseTargetConflictResponse, type NoCTFAPIEndpointsGameplayFactsRequestAwdpDefenseTargetResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { type WithRuntimeInstanceItemRequestBuilder, WithRuntimeInstanceItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/awdp-defense-targets
 */
export interface AwdpDefenseTargetsRequestBuilder extends BaseRequestBuilder<AwdpDefenseTargetsRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.competitions.item.challenges.item.awdpDefenseTargets.item collection
     * @param runtimeInstanceId Unique identifier of the item
     * @returns {WithRuntimeInstanceItemRequestBuilder}
     */
     byRuntimeInstanceId(runtimeInstanceId: Guid) : WithRuntimeInstanceItemRequestBuilder;
    /**
     * Creates an isolated disposable target that accepts exactly one Fix archive.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsGameplayFactsRequestAwdpDefenseTargetResponse>}
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 403 status code
     * @throws {NoCTFAPIEndpointsGameplayFactsAwdpDefenseTargetConflictResponse} error when the service returns a 409 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 503 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsGameplayFactsRequestAwdpDefenseTargetResponse | undefined>;
    /**
     * Creates an isolated disposable target that accepts exactly one Fix archive.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AwdpDefenseTargetsRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/awdp-defense-targets";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AwdpDefenseTargetsRequestBuilderNavigationMetadata: Record<Exclude<keyof AwdpDefenseTargetsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byRuntimeInstanceId: {
        navigationMetadata: WithRuntimeInstanceItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["runtimeInstanceId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AwdpDefenseTargetsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AwdpDefenseTargetsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            403: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsGameplayFactsAwdpDefenseTargetConflictResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            503: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsGameplayFactsRequestAwdpDefenseTargetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
