/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsChallengesChallengeListResponseFromDiscriminatorValue, type NoCTFAPIEndpointsChallengesChallengeListResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type WithCompetitionChallengeItemRequestBuilder, WithCompetitionChallengeItemRequestBuilderNavigationMetadata, WithCompetitionChallengeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/challenges
 */
export interface ChallengesRequestBuilder extends BaseRequestBuilder<ChallengesRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.competitions.item.challenges.item collection
     * @param competitionChallengeId Unique identifier of the item
     * @returns {WithCompetitionChallengeItemRequestBuilder}
     */
     byCompetitionChallengeId(competitionChallengeId: Guid) : WithCompetitionChallengeItemRequestBuilder;
    /**
     * Lists published challenges for a competition.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsChallengesChallengeListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsChallengesChallengeListResponse | undefined>;
    /**
     * Lists published challenges for a competition.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ChallengesRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/challenges";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChallengesRequestBuilderNavigationMetadata: Record<Exclude<keyof ChallengesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCompetitionChallengeId: {
        requestsMetadata: WithCompetitionChallengeItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithCompetitionChallengeItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["competitionChallengeId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ChallengesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ChallengesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsChallengesChallengeListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
