<script setup lang="ts">
import { toRefs } from 'vue'
import type { LiveSoloPostgameWriteUpsState } from '~/features/live-solo/useLiveSoloPostgameWriteUps'
const props=defineProps<{state:LiveSoloPostgameWriteUpsState}>()
const {questionOptions,questionId,selectQuestion,mode,tab,staff,manager,loading,busy,error,listing,items,selected,select,root,version,stateKey,content,pdf,
  editor,official,format,chooseFormat,markdown,chooseFile,uploadKey,dirty,canSave,canSubmit,save,submit,reviewable,reviewOpen,setReview,reviewAction,reason,openReview,review,
  download,reload,back,leaveOpen,setLeave,leave,settingEnabled,enable}=toRefs(props.state)
</script>
<template>
  <div data-contained-workspace-page class="flex h-full min-h-0 flex-col gap-4 px-4 pb-6 pt-3 md:px-8">
    <header class="flex flex-wrap items-center gap-3"><Button variant="ghost" @click="back">{{ $t('liveSolo.back') }}</Button><h1 class="text-display text-2xl">{{ $t('liveSolo.postgame.title') }}</h1><Badge variant="secondary">{{ $t('liveSolo.postgame.free') }}</Badge><Button class="ml-auto" variant="ghost" :disabled="busy || dirty" @click="reload">{{ $t('common.label.refresh') }}</Button></header>
    <Alert v-if="error" variant="destructive"><AlertDescription>{{ $message(error) }}</AlertDescription></Alert>
    <Button v-if="manager&&!settingEnabled" :disabled="busy" @click="enable">{{ $t('liveSolo.postgame.enable') }}</Button>
    <ChoicePicker :items="questionOptions" :model-value="questionId" :label="$t('liveSolo.postgame.question')" :search-label="$t('liveSolo.groups.searchQuestion')" :empty-label="$t('liveSolo.postgame.noQuestion')" :disabled="busy" @update:model-value="selectQuestion" />
    <Card class="min-h-0 flex-1"><ScrollSurface axis="y" class="h-full" :aria-label="$t('liveSolo.postgame.title')"><CardContent class="flex flex-col gap-5 py-5">
      <Tabs :model-value="mode" @update:model-value="tab"><TabsList><TabsTrigger value="Public" :disabled="dirty || busy">{{ $t('liveSolo.postgame.public') }}</TabsTrigger><TabsTrigger value="Mine" :disabled="dirty || busy">{{ $t('challengeWriteUp.mine') }}</TabsTrigger><TabsTrigger v-if="manager" value="Official" :disabled="dirty || busy">{{ $t('liveSolo.postgame.official') }}</TabsTrigger><TabsTrigger v-if="staff" value="Review" :disabled="dirty || busy">{{ $t('liveSolo.postgame.review') }}</TabsTrigger></TabsList></Tabs>
      <Skeleton v-if="loading && !listing" class="h-64" />
      <template v-if="listing"><Alert v-if="!listing.access?.settings?.enabled"><AlertDescription>{{ $t('liveSolo.postgame.disabled') }}</AlertDescription></Alert>
        <template v-if="!editor"><ChoicePicker :items="items" :model-value="selected" :label="$t('liveSolo.postgame.selectWriteUp')" :search-label="$t('liveSolo.postgame.searchAuthor')" :empty-label="$t('liveSolo.postgame.noWriteUp')" :disabled="busy" @update:model-value="select" /><div v-if="root" class="flex flex-wrap gap-3"><Badge>{{ $t(stateKey) }}</Badge><span>{{ root.authorName }}</span><span v-if="version">{{ $t('challengeWriteUp.version',{number:version.number??1}) }}</span></div><MarkdownContent v-if="content?.format==='Markdown'" :source="content.markdown??''" class="max-w-[75ch]" /><PdfPreview v-if="content?.format==='Pdf'" :source="pdf" :accessible-label="$t('challengeWriteUp.preview')" :empty-label="$t('challengeWriteUp.previewEmpty')" /><Button v-if="content?.format==='Pdf'" :disabled="busy" @click="download">{{ $t('liveSolo.postgame.download') }}</Button><Empty v-if="!root"><EmptyHeader><EmptyTitle>{{ $t('liveSolo.postgame.noWriteUp') }}</EmptyTitle></EmptyHeader></Empty></template>
        <UiForm v-else validation="feature" class="flex flex-col gap-4" @submit="save"><div class="flex flex-wrap gap-3"><Badge>{{ $t(stateKey) }}</Badge><span v-if="listing.access?.settings?.deadlineAt">{{ $t('liveSolo.postgame.deadline',{time:formatDateTime(listing.access.settings.deadlineAt)}) }}</span></div><p v-if="root?.submitted?.reviewReason" class="whitespace-pre-wrap">{{ root.submitted.reviewReason }}</p><Field><FieldLabel for="postgame-format">{{ $t('challengeWriteUp.format') }}</FieldLabel><Select :model-value="format" :disabled="!canSave || busy" @update:model-value="chooseFormat"><SelectTrigger id="postgame-format"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Markdown">{{ $t('challengeWriteUp.markdown') }}</SelectItem><SelectItem value="Pdf">{{ $t('challengeWriteUp.pdf') }}</SelectItem></SelectContent></Select></Field><MarkdownEditor v-if="format==='Markdown'" v-model="markdown" :label="$t(official ? 'liveSolo.postgame.official' : 'challengeWriteUp.mine')" :disabled="!canSave || busy" @save="save" /><template v-else><FileUpload v-if="canSave" :key="uploadKey" accept="application/pdf,.pdf" :pending="busy" @change="chooseFile" /><PdfPreview :source="pdf" :accessible-label="$t('challengeWriteUp.preview')" :empty-label="$t('challengeWriteUp.previewEmpty')" /><Button v-if="pdf" type="button" variant="outline" :disabled="busy" @click="download">{{ $t('liveSolo.postgame.download') }}</Button></template><div class="flex justify-end gap-3"><Badge v-if="dirty" variant="secondary">{{ $t('liveSolo.settings.unsaved') }}</Badge><Button type="submit" :disabled="busy || !canSave || !dirty">{{ $t('liveSolo.postgame.saveDraft') }}</Button><Button type="button" variant="outline" :disabled="!canSubmit" @click="submit">{{ $t('liveSolo.postgame.submit') }}</Button></div></UiForm>
        <div v-if="reviewable && !dirty" class="flex flex-wrap gap-3"><Button v-if="manager && version?.state==='Submitted'" :disabled="busy" @click="openReview('Publish')">{{ $t('liveSolo.postgame.publish') }}</Button><Button v-if="version?.state==='Submitted'" variant="outline" :disabled="busy" @click="openReview('Reject')">{{ $t('liveSolo.postgame.reject') }}</Button><Button v-if="manager && root?.publishedVersionId" variant="outline" :disabled="busy" @click="openReview('Withdraw')">{{ $t('liveSolo.postgame.withdraw') }}</Button></div>
      </template>
    </CardContent></ScrollSurface></Card>
    <AlertDialog :open="reviewOpen" @update:open="setReview"><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{{ $t('liveSolo.postgame.reviewConfirm') }}</AlertDialogTitle><AlertDialogDescription>{{ $t('liveSolo.postgame.reviewHelp') }}</AlertDialogDescription></AlertDialogHeader><p>{{ root?.authorName }} · {{ version?.number }}</p><Field><FieldLabel for="postgame-review-reason">{{ $t('liveSolo.judge.reason') }}</FieldLabel><Textarea id="postgame-review-reason" v-model="reason" :disabled="busy" :maxlength="4000" /></Field><AlertDialogFooter><AlertDialogCancel :disabled="busy">{{ $t('common.action.cancel') }}</AlertDialogCancel><Button :disabled="busy || (reviewAction==='Reject'&&!reason.trim())" @click="review">{{ $t(reviewAction==='Publish'?'liveSolo.postgame.publish':reviewAction==='Reject'?'liveSolo.postgame.reject':'liveSolo.postgame.withdraw') }}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog :open="leaveOpen" @update:open="setLeave"><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{{ $t('liveSolo.groups.discardTitle') }}</AlertDialogTitle><AlertDialogDescription>{{ $t('liveSolo.postgame.unsaved') }}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{{ $t('common.action.cancel') }}</AlertDialogCancel><Button @click="leave">{{ $t('liveSolo.groups.discard') }}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>
</template>
