<script setup lang="ts">
import { toRefs } from 'vue'
import type { LiveSoloMatchState } from '~/features/live-solo/useLiveSoloMatch'
const props = defineProps<{ state: LiveSoloMatchState }>()
const { competitionId, match, round, configuration, loading, busy, error, myRoster, captain, onRoster,
  canLock, allLocked, rosterOptions, selectedRoster, toggleRoster, lockRoster, ready, prepareMedia, prepareRound, start,
  staff, readOnlyMedia, judge, canCorrect, correct, screens, myScreen, clock, stateKey, back, load, judgeOpen, judgeAction, judgeReason, forfeitingTeam,
  openDecision, confirmDecision, setJudgeOpen, leaveOpen, setLeaveOpen, confirmLeave, Workspace, connected, connecting,
  publishing, capturePending, eligible, connect, share, stopSharing, disconnect, mediaError, media,
  ProgramControl, Questions, canSubmit, questionsVisible, matchId, flagDock } = toRefs(props.state)
</script>
<template>
  <component :is="Workspace" :competition-id="competitionId" :show-challenge-navigator="false" :content-scroll="false">
    <div class="flex h-full min-h-0 flex-col gap-4">
      <header class="flex flex-wrap items-center gap-3"><Button variant="ghost" size="sm" @click="back">{{ $t('liveSolo.back') }}</Button><Badge>{{ $t(stateKey) }}</Badge><span v-if="round" class="text-sm">{{ $t('liveSolo.round', { number: round.number ?? 1 }) }}</span><span class="ml-auto font-mono text-xl tabular-nums" :aria-label="$t('liveSolo.clockEstimate')">{{ clock }}</span><Button variant="ghost" size="sm" :disabled="loading" @click="load">{{ $t('common.label.refresh') }}</Button></header>
      <Alert v-if="error || mediaError" variant="destructive"><AlertDescription>{{ $message(error || mediaError) }}</AlertDescription></Alert>
      <div v-if="match?.pendingCorrectionId || canCorrect" class="flex flex-wrap items-center gap-3"><Badge v-if="match?.pendingCorrectionId" variant="secondary">{{ $t('liveSolo.correction.pending') }}</Badge><Button v-if="canCorrect" variant="outline" size="sm" @click="correct">{{ $t('liveSolo.correction.title') }}</Button></div>
      <Card class="flex min-h-0 flex-1 flex-col">
        <CardHeader><Skeleton v-if="loading && !match" class="h-20" /><div v-else-if="match" class="grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center"><h1 class="min-w-0 break-words text-lg font-semibold">{{ match.leftTeamName || '—' }}</h1><div class="flex flex-col gap-1"><span class="font-mono text-3xl font-bold tabular-nums text-primary">{{ match.leftWins ?? 0 }} : {{ match.rightWins ?? 0 }}</span><span class="text-xs text-muted-foreground">{{ $t('liveSolo.firstTo', { wins: match.requiredWins ?? 2 }) }}</span></div><h2 class="min-w-0 break-words text-lg font-semibold">{{ match.rightTeamName || '—' }}</h2></div></CardHeader>
        <ScrollSurface axis="y" class="min-h-0 flex-1" :aria-label="$t('liveSolo.matches')"><CardContent class="flex flex-col gap-6">
          <section v-if="canLock || myRoster" class="flex flex-col gap-3"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="font-semibold">{{ $t('liveSolo.roster') }}</h2><Badge v-if="myRoster?.locked">{{ $t('liveSolo.rosterLocked') }}</Badge></div>
            <template v-if="canLock"><p class="text-sm text-muted-foreground">{{ $t('liveSolo.rosterHelp', { maximum: configuration?.maximumRosterMembers ?? 1 }) }}</p><div class="flex flex-wrap gap-4"><Field v-for="member in rosterOptions" :key="member.id" orientation="horizontal"><Checkbox :id="member.id" :model-value="member.selected" :disabled="busy || (!member.selected && selectedRoster.length >= (configuration?.maximumRosterMembers ?? 1))" @update:model-value="toggleRoster(member.id, $event)" /><FieldLabel :for="member.id">{{ member.name }}</FieldLabel></Field></div><div><Button :disabled="busy || !selectedRoster.length" @click="lockRoster">{{ $t('liveSolo.lockRoster') }}</Button></div></template>
            <div v-if="myRoster?.locked" class="flex flex-wrap items-center gap-3"><Badge :variant="myRoster.ready ? 'default' : 'secondary'">{{ $t(myRoster.ready ? 'liveSolo.ready' : 'liveSolo.notReady') }}</Badge><Button v-if="captain && !myRoster.ready" :disabled="busy" @click="ready">{{ $t('liveSolo.confirmReady') }}</Button></div>
          </section>
          <Separator />
          <component :is="Questions" v-if="questionsVisible && round" :key="round.id" :competition-id="competitionId" :match-id="matchId" :round="round" :can-submit="canSubmit" :dock-target="flagDock" />
          <section class="flex flex-col gap-4"><div class="flex flex-wrap items-center gap-3"><Badge :variant="connected ? 'default' : 'secondary'">{{ $t(connected ? 'liveSolo.media.connected' : 'liveSolo.media.disconnected') }}</Badge><Button v-if="!eligible && (judge || onRoster)" :disabled="busy || !allLocked" variant="outline" @click="prepareMedia">{{ $t('liveSolo.media.prepare') }}</Button><Button v-if="eligible && !connected && (staff || onRoster)" :disabled="connecting" variant="outline" @click="connect"><Spinner v-if="connecting" />{{ $t('liveSolo.media.connect') }}</Button><Button v-if="connected && !readOnlyMedia && !publishing" :disabled="capturePending" @click="share"><Spinner v-if="capturePending" />{{ $t('liveSolo.screen.share') }}</Button><Button v-if="publishing" variant="outline" @click="stopSharing">{{ $t('liveSolo.screen.stop') }}</Button><Button v-if="connected" variant="ghost" @click="disconnect">{{ $t('liveSolo.media.disconnect') }}</Button></div>
            <p class="text-sm text-muted-foreground">{{ $t(media?.participantsMayViewOpponents ? 'liveSolo.media.mutual' : 'liveSolo.media.privacy') }}</p>
            <div v-if="media" class="flex max-w-[70ch] flex-col gap-1 text-sm text-muted-foreground"><p>{{ $t('liveSolo.media.delayNotice', { seconds: media.publicDelaySeconds ?? 60 }) }}</p><p>{{ $t(media.recordingEnabled ? 'liveSolo.media.recordingOn' : 'liveSolo.media.recordingOff') }}</p></div>
            <p v-if="publishing && myScreen?.state !== 'Sharing'" class="text-sm text-warning" role="status">{{ $t('liveSolo.screen.confirming') }}</p>
            <div class="grid gap-4 md:grid-cols-2"><div v-for="member in screens" :key="member.key" class="flex min-w-0 flex-col gap-2"><div class="flex flex-wrap items-center justify-between gap-2"><span class="truncate font-medium">{{ member.teamName }} · {{ member.name }}</span><span class="text-xs text-muted-foreground">{{ $t(member.stateKey) }}</span></div><MediaStreamPreview v-if="member.mayView" :stream="member.stream" :label="member.name" :empty-label="$t('liveSolo.screen.waiting')" /></div></div>
          </section>
          <template v-if="judge"><Separator /><section class="flex flex-col gap-3"><h2 class="font-semibold">{{ $t('liveSolo.judge') }}</h2><p class="max-w-[70ch] text-sm text-muted-foreground">{{ $t('liveSolo.judge.screensRequired') }}</p><div class="flex flex-wrap gap-2"><Button v-if="!round || ['Won', 'TimedOut', 'Canceled'].includes(round.state ?? '')" :disabled="busy || !allLocked || !['Preparing', 'AwaitingAdjudication'].includes(match?.state ?? '')" variant="outline" @click="prepareRound">{{ $t('liveSolo.judge.prepare') }}</Button><Button v-if="round?.state === 'Preparing'" :disabled="busy" @click="start">{{ $t('liveSolo.judge.start') }}</Button><Button v-if="match?.state === 'Running' || match?.state === 'Countdown'" :disabled="busy" variant="outline" @click="openDecision('Pause')">{{ $t('liveSolo.judge.pause') }}</Button><Button v-if="match?.state === 'Paused'" :disabled="busy" variant="outline" @click="openDecision('Resume')">{{ $t('liveSolo.judge.resume') }}</Button><Button v-if="round && ['Preparing', 'Countdown', 'Running', 'ConfirmingResult'].includes(round.state ?? '')" :disabled="busy" variant="outline" @click="openDecision('VoidRound')">{{ $t('liveSolo.judge.void') }}</Button><Button v-if="match && !['Completed', 'Canceled', 'AwaitingOpponents'].includes(match.state ?? '')" :disabled="busy" variant="destructive" @click="openDecision('ForfeitMatch')">{{ $t('liveSolo.judge.forfeit') }}</Button></div></section></template>
          <component :is="ProgramControl" v-if="staff" />
          <p v-if="!staff && match?.state === 'Preparing'" class="text-sm text-muted-foreground">{{ $t('liveSolo.waitingJudge') }}</p>
        </CardContent></ScrollSurface><div v-if="questionsVisible" :id="flagDock" class="shrink-0 px-3 pb-3" />
      </Card>
    </div>
    <AlertDialog :open="leaveOpen" @update:open="setLeaveOpen"><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{{ $t('liveSolo.leave.title') }}</AlertDialogTitle><AlertDialogDescription>{{ $t('liveSolo.leave.description') }}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{{ $t('common.action.cancel') }}</AlertDialogCancel><Button @click="confirmLeave">{{ $t('liveSolo.leave.confirm') }}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Dialog :open="judgeOpen" @update:open="setJudgeOpen"><DialogContent><DialogHeader><DialogTitle>{{ $t('liveSolo.judge.confirmTitle') }}</DialogTitle><DialogDescription>{{ $t('liveSolo.judge.confirmDescription') }}</DialogDescription></DialogHeader><UiForm validation="feature" @submit="confirmDecision"><FieldGroup><Field v-if="judgeAction === 'ForfeitMatch'"><FieldLabel>{{ $t('liveSolo.judge.forfeitingTeam') }}</FieldLabel><Select v-model="forfeitingTeam"><SelectTrigger><SelectValue :placeholder="$t('liveSolo.judge.forfeitingTeam')" /></SelectTrigger><SelectContent><SelectItem v-if="match?.leftTeamId" :value="match.leftTeamId">{{ match.leftTeamName }}</SelectItem><SelectItem v-if="match?.rightTeamId" :value="match.rightTeamId">{{ match.rightTeamName }}</SelectItem></SelectContent></Select></Field><Field><FieldLabel for="live-solo-judge-reason">{{ $t('liveSolo.judge.reason') }}</FieldLabel><Textarea id="live-solo-judge-reason" v-model="judgeReason" :disabled="busy" /></Field></FieldGroup><DialogFooter class="mt-4"><Button variant="outline" type="button" @click="setJudgeOpen(false)">{{ $t('common.action.cancel') }}</Button><Button type="submit" :disabled="busy || !judgeReason.trim()">{{ $t('common.action.confirm') }}</Button></DialogFooter></UiForm></DialogContent></Dialog>
  </component>
</template>
