<script setup lang="ts">
import { toRefs } from 'vue'
import type { LiveSoloBracketState } from '~/features/live-solo/useLiveSoloBracket'
const props = defineProps<{ state: LiveSoloBracketState }>()
const { bracket, loading, busy, error, writable, options, addOptions, candidate, seeds, seedIds, left, right, wins, rows, seeded, champion,
  matchNumbers, confirmation, confirmationNames, load, add, remove, move, setWins, open, setOpen, confirm, enter, back } = toRefs(props.state)
</script>
<template>
  <div class="mx-auto flex w-full max-w-7xl min-w-0 flex-col gap-6 px-4 pb-8 pt-4 md:px-8">
    <div><Button variant="ghost" size="sm" @click="back"><LucideIcon name="arrow-left" data-icon="inline-start" />{{ $t('liveSolo.back') }}</Button></div>
    <header class="flex flex-wrap items-center gap-4"><h1 class="text-display text-2xl">{{ $t('liveSolo.bracket.title') }}</h1><Badge v-if="champion">{{ $t('liveSolo.bracket.champion',{team:champion}) }}</Badge><Button class="ml-auto" variant="ghost" :disabled="busy || confirmation !== null" @click="load">{{ $t('common.label.refresh') }}</Button></header>
    <Alert v-if="error" variant="destructive"><AlertDescription>{{ $message(error) }}</AlertDescription></Alert>
    <Card class="min-w-0"><CardContent class="flex min-w-0 flex-col gap-6">
      <Skeleton v-if="loading && !bracket" class="h-64" />
      <template v-if="writable && bracket && !seeded">
        <DefinitionSection v-if="!rows.length" :title="$t('liveSolo.bracket.seedTitle')" :collapsible="false"><div class="flex flex-col gap-4"><div class="flex min-w-0 flex-col gap-3 sm:flex-row"><div class="min-w-0 flex-1"><ChoicePicker v-model="candidate" :items="addOptions" :label="$t('liveSolo.bracket.chooseTeam')" :search-label="$t('liveSolo.bracket.searchTeam')" :empty-label="$t('liveSolo.bracket.noTeam')" :disabled="busy" /></div><Button class="shrink-0" :disabled="busy || !candidate" @click="add">{{ $t('liveSolo.bracket.add') }}</Button></div><div v-for="(team,index) in seeds" :key="team.id" class="flex flex-wrap items-center gap-3"><span class="w-8 font-mono tabular-nums">{{ team.number }}</span><span class="min-w-0 flex-1 break-words">{{ team.name }}</span><Button variant="ghost" :disabled="busy || index === 0" :aria-label="$t('liveSolo.bracket.up',{team:team.name})" @click="move(index,-1)">{{ $t('liveSolo.bracket.upShort') }}</Button><Button variant="ghost" :disabled="busy || index === seeds.length-1" :aria-label="$t('liveSolo.bracket.down',{team:team.name})" @click="move(index,1)">{{ $t('liveSolo.bracket.downShort') }}</Button><Button variant="ghost" :disabled="busy" @click="remove(index)">{{ $t('liveSolo.settings.remove') }}</Button></div><p class="text-sm text-muted-foreground">{{ $t('liveSolo.bracket.seedHelp') }}</p><div><Button :disabled="busy || seedIds.length < 2" @click="open('Generate')">{{ $t('liveSolo.bracket.generate') }}</Button></div></div></DefinitionSection>
        <DefinitionSection :title="$t('liveSolo.bracket.directTitle')" :collapsible="false"><FieldGroup class="grid min-w-0 items-start gap-5 md:grid-cols-2 xl:grid-cols-3"><Field><FieldLabel>{{ $t('liveSolo.bracket.left') }}</FieldLabel><ChoicePicker v-model="left" :items="options" :label="$t('liveSolo.bracket.left')" :search-label="$t('liveSolo.bracket.searchTeam')" :empty-label="$t('liveSolo.bracket.noTeam')" :disabled="busy" /></Field><Field><FieldLabel>{{ $t('liveSolo.bracket.right') }}</FieldLabel><ChoicePicker v-model="right" :items="options" :label="$t('liveSolo.bracket.right')" :search-label="$t('liveSolo.bracket.searchTeam')" :empty-label="$t('liveSolo.bracket.noTeam')" :disabled="busy" /></Field><Field><FieldLabel for="direct-required-wins">{{ $t('liveSolo.bracket.directWins') }}</FieldLabel><NumberInput id="direct-required-wins" :model-value="wins" :min="1" :max="1024" :disabled="busy" @update:model-value="setWins" /><FieldDescription>{{ $t('liveSolo.bracket.inheritWins') }}</FieldDescription></Field><Button class="justify-self-start md:col-span-2 xl:col-span-3" :disabled="busy || !left || !right || left === right" @click="open('Create')">{{ $t('liveSolo.bracket.create') }}</Button></FieldGroup></DefinitionSection><Separator />
      </template>
      <p v-if="seeded" class="text-sm text-muted-foreground">{{ $t('liveSolo.bracket.seededLocked') }}</p>
      <div v-if="rows.length" class="flex flex-col"><article v-for="item in rows" :key="item.id" class="flex min-w-0 flex-col gap-4 py-5 md:flex-row md:items-center"><div class="flex min-w-0 flex-1 flex-col gap-2"><div class="flex flex-wrap gap-2"><Badge variant="secondary">{{ $t(item.laneKey) }} · {{ $t('liveSolo.bracket.stage',{stage:item.row.stage ?? 1}) }}</Badge><Badge>{{ $t(item.stateKey) }}</Badge><Badge v-if="item.row.conditional" variant="outline">{{ $t('liveSolo.bracket.conditional') }}</Badge></div><p class="break-words font-semibold">#{{ item.number }} · {{ item.row.match?.leftTeamName || $t('liveSolo.bracket.awaitingSource') }} / {{ item.row.match?.rightTeamName || $t('liveSolo.bracket.awaitingSource') }}</p><div class="flex flex-wrap gap-3 text-sm text-muted-foreground"><span class="font-mono tabular-nums">{{ item.row.match?.leftWins ?? 0 }} : {{ item.row.match?.rightWins ?? 0 }}</span><span>{{ $t('liveSolo.firstTo',{wins:item.row.match?.requiredWins ?? 2}) }}</span><span v-for="source in item.row.sources" :key="source.side"><template v-if="source.sourceMatchId">{{ $t(source.source === 'Loser' ? 'liveSolo.bracket.fromLoser' : 'liveSolo.bracket.fromWinner',{match:matchNumbers.get(source.sourceMatchId) ?? '—'}) }}</template><template v-else-if="source.seed != null">{{ $t('liveSolo.bracket.seed',{seed:source.seed}) }}</template><template v-else-if="source.source === 'Bye'">{{ $t('liveSolo.bracket.bye') }}</template></span></div></div><Button variant="outline" class="self-start shrink-0 md:self-center" @click="enter(item.id)">{{ $t('liveSolo.enterMatch') }}</Button></article></div><Empty v-else-if="!loading"><EmptyHeader><EmptyTitle>{{ $t('liveSolo.noMatches') }}</EmptyTitle></EmptyHeader></Empty>
    </CardContent></Card>
    <AlertDialog :open="confirmation !== null" @update:open="setOpen"><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{{ $t(confirmation === 'Generate' ? 'liveSolo.bracket.confirmGenerate' : 'liveSolo.bracket.confirmCreate') }}</AlertDialogTitle><AlertDialogDescription>{{ $t('liveSolo.bracket.confirmHelp') }}</AlertDialogDescription></AlertDialogHeader><ScrollSurface axis="y" class="max-h-72"><ol class="flex flex-col gap-2"><li v-for="(name,index) in confirmationNames" :key="index">{{ index+1 }} · {{ name }}</li></ol></ScrollSurface><AlertDialogFooter><AlertDialogCancel :disabled="busy">{{ $t('common.action.cancel') }}</AlertDialogCancel><Button :disabled="busy" @click="confirm">{{ $t(confirmation === 'Generate' ? 'liveSolo.bracket.generate' : 'liveSolo.bracket.create') }}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>
</template>
