/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsCompetitionsTracksCompetitionTrackListResponseFromDiscriminatorValue, type NoCTFAPIEndpointsCompetitionsTracksCompetitionTrackListResponse } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/tracks
 */
export interface TracksRequestBuilder extends BaseRequestBuilder<TracksRequestBuilder> {
    /**
     * Returns public tracks and the authenticated participant team's own track.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsCompetitionsTracksCompetitionTrackListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsCompetitionsTracksCompetitionTrackListResponse | undefined>;
    /**
     * Returns public tracks and the authenticated participant team's own track.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TracksRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/tracks";
/**
 * Metadata for all the requests in the request builder.
 */
export const TracksRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TracksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsCompetitionsTracksCompetitionTrackListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
