/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue, createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAuthenticationRegisterResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAuthenticationRegisterRequest, serializeNoCTFAPIEndpointsAuthenticationRegisterResponse, type MicrosoftAspNetCoreMvcProblemDetails, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAuthenticationRegisterRequest, type NoCTFAPIEndpointsAuthenticationRegisterResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/register
 */
export interface RegisterRequestBuilder extends BaseRequestBuilder<RegisterRequestBuilder> {
    /**
     * Creates a local account with an Identity V3 password hash.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationRegisterResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 403 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 409 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 503 status code
     */
     post(body: NoCTFAPIEndpointsAuthenticationRegisterRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationRegisterResponse | undefined>;
    /**
     * Creates a local account with an Identity V3 password hash.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsAuthenticationRegisterRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RegisterRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/register";
/**
 * Metadata for all the requests in the request builder.
 */
export const RegisterRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RegisterRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            503: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationRegisterResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAuthenticationRegisterRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
