/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAuthenticationPublicUserProfileResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAuthenticationPublicUserProfileResponse } from '../../../../models/index.js';
// @ts-ignore
import { AvatarRequestBuilderRequestsMetadata, type AvatarRequestBuilder } from './avatar/index.js';
// @ts-ignore
import { ProfileCoverRequestBuilderRequestsMetadata, type ProfileCoverRequestBuilder } from './profileCover/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/users/{userId}
 */
export interface WithUserItemRequestBuilder extends BaseRequestBuilder<WithUserItemRequestBuilder> {
    /**
     * The avatar property
     */
    get avatar(): AvatarRequestBuilder;
    /**
     * The profileCover property
     */
    get profileCover(): ProfileCoverRequestBuilder;
    /**
     * Returns a user's public profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationPublicUserProfileResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationPublicUserProfileResponse | undefined>;
    /**
     * Returns a user's public profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithUserItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/users/{userId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithUserItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithUserItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    avatar: {
        requestsMetadata: AvatarRequestBuilderRequestsMetadata,
    },
    profileCover: {
        requestsMetadata: ProfileCoverRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithUserItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithUserItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationPublicUserProfileResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
