/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsTeamsTeamResponseFromDiscriminatorValue, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsTeamsTeamResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { ChallengesRequestBuilderNavigationMetadata, type ChallengesRequestBuilder } from './challenges/index.js';
// @ts-ignore
import { CorrectBanRequestBuilderRequestsMetadata, type CorrectBanRequestBuilder } from './correctBan/index.js';
// @ts-ignore
import { InvitationTokenRequestBuilderRequestsMetadata, type InvitationTokenRequestBuilder } from './invitationToken/index.js';
// @ts-ignore
import { MembersRequestBuilderNavigationMetadata, type MembersRequestBuilder } from './members/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/teams/{teamId}
 */
export interface WithTeamItemRequestBuilder extends BaseRequestBuilder<WithTeamItemRequestBuilder> {
    /**
     * The challenges property
     */
    get challenges(): ChallengesRequestBuilder;
    /**
     * The correctBan property
     */
    get correctBan(): CorrectBanRequestBuilder;
    /**
     * The invitationToken property
     */
    get invitationToken(): InvitationTokenRequestBuilder;
    /**
     * The members property
     */
    get members(): MembersRequestBuilder;
    /**
     * Loads one team by its competition-scoped identity for authorized observers without depending on list pagination or public visibility.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsTeamsTeamResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsTeamsTeamResponse | undefined>;
    /**
     * Loads one team by its competition-scoped identity for authorized observers without depending on list pagination or public visibility.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithTeamItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/teams/{teamId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTeamItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithTeamItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    challenges: {
        navigationMetadata: ChallengesRequestBuilderNavigationMetadata,
    },
    correctBan: {
        requestsMetadata: CorrectBanRequestBuilderRequestsMetadata,
    },
    invitationToken: {
        requestsMetadata: InvitationTokenRequestBuilderRequestsMetadata,
    },
    members: {
        navigationMetadata: MembersRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithTeamItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithTeamItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsTeamsTeamResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
