<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../NoCTF.Domain/NoCTF.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentStorage" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Competitions/Directions/lucide-icons.txt" />
  </ItemGroup>
</Project>
