/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAdministrationPlatformCreateSsoProviderRequest, serializeNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationPlatformCreateSsoProviderRequest, type NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type WithProviderItemRequestBuilder, WithProviderItemRequestBuilderNavigationMetadata, WithProviderItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/platform/sso/providers
 */
export interface ProvidersRequestBuilder extends BaseRequestBuilder<ProvidersRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.admin.platform.sso.providers.item collection
     * @param providerId Unique identifier of the item
     * @returns {WithProviderItemRequestBuilder}
     */
     byProviderId(providerId: Guid) : WithProviderItemRequestBuilder;
    /**
     * Creates a disabled or ready SSO provider definition.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: NoCTFAPIEndpointsAdministrationPlatformCreateSsoProviderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponse | undefined>;
    /**
     * Creates a disabled or ready SSO provider definition.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsAdministrationPlatformCreateSsoProviderRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProvidersRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/platform/sso/providers";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProvidersRequestBuilderNavigationMetadata: Record<Exclude<keyof ProvidersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byProviderId: {
        requestsMetadata: WithProviderItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithProviderItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["providerId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ProvidersRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ProvidersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationPlatformSsoConfigurationResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAdministrationPlatformCreateSsoProviderRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
