/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsCompetitionsScoreboardSlotDetailResponseFromDiscriminatorValue, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsCompetitionsScoreboardSlotDetailResponse } from '../../../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/leaderboard/teams/{teamId}/columns/{columnIndex}
 */
export interface WithColumnIndexItemRequestBuilder extends BaseRequestBuilder<WithColumnIndexItemRequestBuilder> {
    /**
     * Get one sparse scoreboard slot with signed cursor pagination.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsCompetitionsScoreboardSlotDetailResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<WithColumnIndexItemRequestBuilderGetQueryParameters> | undefined) : Promise<NoCTFAPIEndpointsCompetitionsScoreboardSlotDetailResponse | undefined>;
    /**
     * Get one sparse scoreboard slot with signed cursor pagination.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<WithColumnIndexItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Get one sparse scoreboard slot with signed cursor pagination.
 */
export interface WithColumnIndexItemRequestBuilderGetQueryParameters {
    cursor?: string;
    endingRound?: number;
    limit?: number;
}
/**
 * Uri template for the request builder.
 */
export const WithColumnIndexItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/leaderboard/teams/{teamId}/columns/{columnIndex}?limit={limit}{&cursor*,endingRound*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithColumnIndexItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithColumnIndexItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsCompetitionsScoreboardSlotDetailResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
