/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithCompetitionChallengeItemRequestBuilder, WithCompetitionChallengeItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/teams/{teamId}/challenges
 */
export interface ChallengesRequestBuilder extends BaseRequestBuilder<ChallengesRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.admin.competitions.item.teams.item.challenges.item collection
     * @param competitionChallengeId Unique identifier of the item
     * @returns {WithCompetitionChallengeItemRequestBuilder}
     */
     byCompetitionChallengeId(competitionChallengeId: string) : WithCompetitionChallengeItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ChallengesRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/teams/{teamId}/challenges";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ChallengesRequestBuilderNavigationMetadata: Record<Exclude<keyof ChallengesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCompetitionChallengeId: {
        navigationMetadata: WithCompetitionChallengeItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["competitionChallengeId"],
    },
};
/* tslint:enable */
/* eslint-enable */
