/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ConfigurationRequestBuilderRequestsMetadata, type ConfigurationRequestBuilder } from './configuration/index.js';
// @ts-ignore
import { LogoRequestBuilderRequestsMetadata, type LogoRequestBuilder } from './logo/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/platform
 */
export interface PlatformRequestBuilder extends BaseRequestBuilder<PlatformRequestBuilder> {
    /**
     * The configuration property
     */
    get configuration(): ConfigurationRequestBuilder;
    /**
     * The logo property
     */
    get logo(): LogoRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PlatformRequestBuilderUriTemplate = "{+baseurl}/api/v1/platform";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PlatformRequestBuilderNavigationMetadata: Record<Exclude<keyof PlatformRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    configuration: {
        requestsMetadata: ConfigurationRequestBuilderRequestsMetadata,
    },
    logo: {
        requestsMetadata: LogoRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
