/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CasRequestBuilderNavigationMetadata, type CasRequestBuilder } from './cas/index.js';
// @ts-ignore
import { OidcRequestBuilderNavigationMetadata, type OidcRequestBuilder } from './oidc/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/sso/callback
 */
export interface CallbackRequestBuilder extends BaseRequestBuilder<CallbackRequestBuilder> {
    /**
     * The cas property
     */
    get cas(): CasRequestBuilder;
    /**
     * The oidc property
     */
    get oidc(): OidcRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CallbackRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/sso/callback";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CallbackRequestBuilderNavigationMetadata: Record<Exclude<keyof CallbackRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    cas: {
        navigationMetadata: CasRequestBuilderNavigationMetadata,
    },
    oidc: {
        navigationMetadata: OidcRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
