/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue, createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsTeamsTeamAvatarResponseFromDiscriminatorValue, createNoCTFAPIEndpointsTeamsTeamRegistrationFailureResponseFromDiscriminatorValue, type MicrosoftAspNetCoreMvcProblemDetails, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsTeamsTeamAvatarResponse, type NoCTFAPIEndpointsTeamsTeamRegistrationFailureResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { MultipartBody, serializeMultipartBody, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/teams/{teamId}/avatar
 */
export interface AvatarRequestBuilder extends BaseRequestBuilder<AvatarRequestBuilder> {
    /**
     * Clears a team's avatar and queues unreferenced File cleanup.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {NoCTFAPIEndpointsTeamsTeamRegistrationFailureResponse} error when the service returns a 409 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Returns a team's current avatar.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Replaces a team's avatar with an immutable File reference.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsTeamsTeamAvatarResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {NoCTFAPIEndpointsTeamsTeamRegistrationFailureResponse} error when the service returns a 409 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 413 status code
     */
     put(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsTeamsTeamAvatarResponse | undefined>;
    /**
     * Clears a team's avatar and queues unreferenced File cleanup.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Returns a team's current avatar.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Replaces a team's avatar with an immutable File reference.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: MultipartBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AvatarRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/teams/{teamId}/avatar";
/**
 * Metadata for all the requests in the request builder.
 */
export const AvatarRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: AvatarRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            409: createNoCTFAPIEndpointsTeamsTeamRegistrationFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: AvatarRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    put: {
        uriTemplate: AvatarRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsTeamsTeamRegistrationFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            413: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsTeamsTeamAvatarResponseFromDiscriminatorValue,
        requestBodyContentType: "multipart/form-data",
        requestBodySerializer: serializeMultipartBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
