/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAuthenticationCurrentUserProfilePatchFailureResponseFromDiscriminatorValue, createNoCTFAPIEndpointsAuthenticationCurrentUserProfileResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAuthenticationCurrentUserProfileResponse, serializeNoCTFAPIEndpointsAuthenticationPatchMyProfileRequest, type NoCTFAPIEndpointsAuthenticationCurrentUserProfilePatchFailureResponse, type NoCTFAPIEndpointsAuthenticationCurrentUserProfileResponse, type NoCTFAPIEndpointsAuthenticationPatchMyProfileRequest } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/me/profile
 */
export interface ProfileRequestBuilder extends BaseRequestBuilder<ProfileRequestBuilder> {
    /**
     * Gets the current user's editable profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationCurrentUserProfileResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationCurrentUserProfileResponse | undefined>;
    /**
     * Updates selected current-user profile sections.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationCurrentUserProfileResponse>}
     * @throws {NoCTFAPIEndpointsAuthenticationCurrentUserProfilePatchFailureResponse} error when the service returns a 400 status code
     */
     patch(body: NoCTFAPIEndpointsAuthenticationPatchMyProfileRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationCurrentUserProfileResponse | undefined>;
    /**
     * Gets the current user's editable profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates selected current-user profile sections.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: NoCTFAPIEndpointsAuthenticationPatchMyProfileRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProfileRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/me/profile";
/**
 * Metadata for all the requests in the request builder.
 */
export const ProfileRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProfileRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationCurrentUserProfileResponseFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: ProfileRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createNoCTFAPIEndpointsAuthenticationCurrentUserProfilePatchFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationCurrentUserProfileResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAuthenticationPatchMyProfileRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
