/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTestAcceptedResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTestAcceptedResponse } from '../../../../../../../../models/index.js';
// @ts-ignore
import { type WithDeliveryItemRequestBuilder, WithDeliveryItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/webhooks/{targetId}/test-deliveries
 */
export interface TestDeliveriesRequestBuilder extends BaseRequestBuilder<TestDeliveriesRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.admin.competitions.item.webhooks.item.testDeliveries.item collection
     * @param deliveryId Unique identifier of the item
     * @returns {WithDeliveryItemRequestBuilder}
     */
     byDeliveryId(deliveryId: Guid) : WithDeliveryItemRequestBuilder;
    /**
     * Queues a test delivery for a configured competition webhook.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTestAcceptedResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTestAcceptedResponse | undefined>;
    /**
     * Queues a test delivery for a configured competition webhook.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TestDeliveriesRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/webhooks/{targetId}/test-deliveries";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TestDeliveriesRequestBuilderNavigationMetadata: Record<Exclude<keyof TestDeliveriesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byDeliveryId: {
        requestsMetadata: WithDeliveryItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["deliveryId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const TestDeliveriesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TestDeliveriesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTestAcceptedResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
