/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue, createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAuthenticationLoginResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAuthenticationLoginRequest, serializeNoCTFAPIEndpointsAuthenticationLoginResponse, type MicrosoftAspNetCoreMvcProblemDetails, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAuthenticationLoginRequest, type NoCTFAPIEndpointsAuthenticationLoginResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/login
 */
export interface LoginRequestBuilder extends BaseRequestBuilder<LoginRequestBuilder> {
    /**
     * Authenticates credentials and issues an access token and HttpOnly refresh cookie.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationLoginResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 403 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 503 status code
     */
     post(body: NoCTFAPIEndpointsAuthenticationLoginRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationLoginResponse | undefined>;
    /**
     * Authenticates credentials and issues an access token and HttpOnly refresh cookie.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsAuthenticationLoginRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LoginRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/login";
/**
 * Metadata for all the requests in the request builder.
 */
export const LoginRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: LoginRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            503: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationLoginResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAuthenticationLoginRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
