/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/sso/callback/cas/{providerId}
 */
export interface WithProviderItemRequestBuilder extends BaseRequestBuilder<WithProviderItemRequestBuilder> {
    /**
     * Consumes a CAS service ticket once.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<WithProviderItemRequestBuilderGetQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Consumes a CAS service ticket once.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<WithProviderItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Consumes a CAS service ticket once.
 */
export interface WithProviderItemRequestBuilderGetQueryParameters {
    flow?: string;
    ticket?: string;
}
/**
 * Uri template for the request builder.
 */
export const WithProviderItemRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/sso/callback/cas/{providerId}{?flow*,ticket*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithProviderItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithProviderItemRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
