/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue, createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsGameplayFactsFlagGameplayFactAcceptedResponseFromDiscriminatorValue, createNoCTFAPIEndpointsGameplayFactsGameplayFactAdmissionFailureResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsGameplayFactsFlagGameplayFactAcceptedResponse, serializeNoCTFAPIEndpointsGameplayFactsSubmitFlagRequest, type MicrosoftAspNetCoreMvcProblemDetails, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsGameplayFactsFlagGameplayFactAcceptedResponse, type NoCTFAPIEndpointsGameplayFactsGameplayFactAdmissionFailureResponse, type NoCTFAPIEndpointsGameplayFactsSubmitFlagRequest } from '../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/flag-submissions
 */
export interface FlagSubmissionsRequestBuilder extends BaseRequestBuilder<FlagSubmissionsRequestBuilder> {
    /**
     * Creates independent immutable attempts, including post-competition CTF practice attempts when enabled. The accepted response is not an evaluation result.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsGameplayFactsFlagGameplayFactAcceptedResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 403 status code
     * @throws {NoCTFAPIEndpointsGameplayFactsGameplayFactAdmissionFailureResponse} error when the service returns a 409 status code
     * @throws {MicrosoftAspNetCoreMvcProblemDetails} error when the service returns a 503 status code
     */
     post(body: NoCTFAPIEndpointsGameplayFactsSubmitFlagRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsGameplayFactsFlagGameplayFactAcceptedResponse | undefined>;
    /**
     * Creates independent immutable attempts, including post-competition CTF practice attempts when enabled. The accepted response is not an evaluation result.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsGameplayFactsSubmitFlagRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FlagSubmissionsRequestBuilderUriTemplate = "{+baseurl}/api/v1/competitions/{competitionId}/challenges/{competitionChallengeId}/flag-submissions";
/**
 * Metadata for all the requests in the request builder.
 */
export const FlagSubmissionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: FlagSubmissionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsGameplayFactsGameplayFactAdmissionFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            503: createMicrosoftAspNetCoreMvcProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsGameplayFactsFlagGameplayFactAcceptedResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsGameplayFactsSubmitFlagRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
