import { expect, test } from 'bun:test'

test('route transitions slide only the page content inside the persistent layout', async () => {
  const root = await Bun.file(new URL('../app/features/shell/useApplicationRoot.ts', import.meta.url)).text()
  const app = await Bun.file(new URL('../app/components/views/app/ApplicationRootView.vue', import.meta.url)).text()
  const layout = await Bun.file(new URL('../app/components/views/layout/DefaultLayoutView.vue', import.meta.url)).text()
  const competitions = await Bun.file(new URL('../app/components/views/page/competitions/CompetitionsIndexPageView.vue', import.meta.url)).text()
  const competitionWorkspace = await Bun.file(new URL('../app/components/views/page/competitions/CompetitionsByIdPageView.vue', import.meta.url)).text()
  const competitionRoute = await Bun.file(new URL('../app/pages/competitions/[id].vue', import.meta.url)).text()
  const platform = await Bun.file(new URL('../app/pages/admin/platform.vue', import.meta.url)).text()
  const notificationsPage = await Bun.file(new URL('../app/components/views/page/NotificationsPageView.vue', import.meta.url)).text()
  const notifications = await Bun.file(new URL('../app/components/views/notifications/NotificationCenterView.vue', import.meta.url)).text()
  const motion = await Bun.file(new URL('../app/motion/motion.css', import.meta.url)).text()
  const main = await Bun.file(new URL('../app/assets/css/main.css', import.meta.url)).text()

  expect(root).toContain("name: 'noctf-page-slide'")
  expect(root).toContain("mode: 'out-in' as const")
  expect(app).toContain('<NuxtPage :transition="pageTransition" />')
  expect(layout).toContain('<main data-slot="page-transition-viewport"')
  expect(layout).toContain('<div data-slot="default-layout"')
  expect(layout).not.toContain('containedWorkspace')
  expect(motion).toContain('.noctf-page-slide-enter-from { transform: translate3d(56px, 0, 0); }')
  expect(motion).toContain('.noctf-page-slide-leave-to { transform: translate3d(-56px, 0, 0); }')
  expect(competitions).not.toContain('data-page-transition="anchored-sidebar"')
  expect(competitions).toContain('<div data-contained-workspace-page class="competition-browser-page')
  expect(competitionWorkspace.match(/data-contained-workspace-page/g)?.length).toBe(2)
  expect(competitionRoute).toContain('<div data-slot="competition-page-route">')
  expect(notificationsPage).not.toContain('data-page-transition="anchored-sidebar"')
  expect(notifications).not.toContain('data-page-slide-content')
  expect(platform).toContain('<div data-slot="platform-admin-page"')
  expect(platform.indexOf('data-slot="platform-admin-page"')).toBeLessThan(platform.indexOf('<Feature>'))
  expect(main).toContain(":is(.competition-browser-layout, .notification-center-layout) [data-slot='floating-sidebar']")
  expect(main).toContain('position: relative; inset: auto; z-index: 20;')
  expect(main).toContain("[data-slot='default-layout']:has(> main [data-contained-workspace-page])")
  expect(main).toContain("[data-slot='default-layout'] > main:has([data-contained-workspace-page])")
  expect(main).toContain("> [data-slot='competition-page-route'] { height: 100%;")
  expect(main).not.toContain('.contained-workspace-shell')
  expect(motion).toContain('.noctf-page-slide-enter-active, .noctf-page-slide-leave-active { transition: none; }')
  expect(main).toContain("[data-slot='page-transition-viewport'] { min-width: 0; overflow-x: clip; }")
})
