import { expect, test } from 'bun:test'

const theme = await Bun.file(new URL('../app/composables/useTheme.ts', import.meta.url)).text()
const reveal = await Bun.file(new URL('../app/motion/reveal-transition.ts', import.meta.url)).text()
const toggle = await Bun.file(new URL('../app/components/views/ThemeToggleView.vue', import.meta.url)).text()
const motion = await Bun.file(new URL('../app/motion/motion.css', import.meta.url)).text()
const css = await Bun.file(new URL('../app/assets/css/main.css', import.meta.url)).text()

test('theme changes reveal from top to bottom without blending component colors', () => {
  expect(theme).toContain("runDownRevealTransition('theme'")
  expect(reveal).toContain('startViewTransition')
  expect(reveal).toContain('revealTransitionDeadlineMs = 1_500')
  expect(reveal).toContain('transition.skipTransition?.()')
  expect(reveal).toContain("layer === 'theme' ? 'themeTransition' : 'wallpaperTransition'")
  expect(reveal).toContain("matchMedia('(prefers-reduced-motion: reduce)')")
  expect(reveal).toContain('await nextTick()')
  expect(toggle).toContain(':disabled="themeTransitioning"')
  expect(motion).toContain("html[data-theme-transition='down']::view-transition-new(root)")
  expect(motion).not.toContain("html[data-theme-transition='down']::view-transition-new(noctf-page-wallpaper)")
  expect(motion).not.toContain("html[data-theme-transition='down']::view-transition-new(noctf-page-foreground)")
  expect(motion).toContain("html[data-wallpaper-transition='down']::view-transition-new(noctf-page-wallpaper)")
  expect(motion).toContain('animation: noctf-theme-cover-down 520ms')
  expect(motion).toContain('animation: noctf-wallpaper-cover-down 520ms')
  expect(motion).toContain("html[data-theme-transition='down'] *")
  expect(motion).toContain("html[data-theme-transition='down'] *::before")
  expect(motion).toContain('transition: none !important')
  expect(motion).toContain('pointer-events: none')
  expect(motion).toContain('clip-path: inset(0 0 100% 0)')
  expect(motion).toContain('to { clip-path: inset(0); }')
  expect(motion).toContain('#000 calc(100% - 5rem)')
  expect(motion).toContain('rgb(0 0 0 / 0.72) calc(100% - 3rem)')
  expect(motion).toContain('mask-size: 100% 0%')
  expect(motion).toContain('mask-size: 100% calc(100% + 5rem)')
  expect(css).not.toContain('view-transition-name:')
  expect(motion).toContain('@media (prefers-reduced-motion: reduce)')
})
