import { expect, test } from 'bun:test'

test('the top bar uses three content-sized capsules with the requested controls', async () => {
  const layout = await Bun.file(new URL('../app/components/views/layout/DefaultLayoutView.vue', import.meta.url)).text()
  const css = await Bun.file(new URL('../app/assets/css/main.css', import.meta.url)).text()
  const motion = await Bun.file(new URL('../app/motion/motion.css', import.meta.url)).text()
  const workspace = await Bun.file(new URL('../app/components/views/app/AppWorkspaceNavView.vue', import.meta.url)).text()

  expect(layout.match(/data-slot="topbar-capsule"/g)?.length).toBe(3)
  const left = layout.slice(layout.indexOf('data-position="left"'), layout.indexOf('data-position="center"'))
  const center = layout.slice(layout.indexOf('data-position="center"'), layout.indexOf('data-position="right"'))
  const right = layout.slice(layout.indexOf('data-position="right"'))
  expect(left).toContain('configuration?.logoUrl')
  expect(left).toContain('data-slot="topbar-brand-name"')
  expect(center).toContain('v-for="item in navItems.filter((i) => i.show)"')
  expect(center).toContain('to="/admin/platform"')
  expect(center).toContain('to="/notifications"')
  expect(center).toContain('<component :is="LanguageToggle" />')
  expect(right).toContain('<component :is="ThemePalettePanel" />')
  expect(right).toContain('<component :is="ThemeToggle" />')
  expect(right).toContain(':is="AccountPanel"')
  expect(right).toContain('<NuxtLink to="/auth/login">')
  expect(right).toContain('<NuxtLink to="/auth/register">')
  expect(layout).not.toContain(':is="AuthDialog"')
  expect(css).toContain("[data-slot='topbar-capsule'] {")
  expect(css).toContain('display: flex; width: max-content; max-width: 100%; min-height: 3rem;')
  expect(css).toContain('border-radius: 9999px;')
  expect(motion).toContain('[data-top-nav-item].noctf-motion-top-nav { transition: width 760ms var(--ui-ease)')
  expect(motion).toContain('opacity 520ms ease-out, transform 760ms var(--ui-ease)')
  expect(workspace).toContain('class="settings-workspace-page"')
  expect(workspace).toContain('<ChoiceSidebar')
  expect(css).toContain('.settings-workspace-page { width: 100%; min-height: calc(100svh - 5rem);')
})
