import { expect, test } from 'bun:test'

test('the top bar uses three content-sized capsules with the requested controls', async () => {
  const layout = await Bun.file(new URL('../app/components/views/layout/DefaultLayoutView.vue', import.meta.url)).text()
  const css = await Bun.file(new URL('../app/assets/css/main.css', import.meta.url)).text()
  const motion = await Bun.file(new URL('../app/motion/motion.css', import.meta.url)).text()
  const workspace = await Bun.file(new URL('../app/components/views/app/AppWorkspaceNavView.vue', import.meta.url)).text()
  const workspaceCss = await Bun.file(new URL('../app/components/views/app/settings-workspace.css', import.meta.url)).text()

  expect(layout.match(/data-slot="topbar-capsule"/g)?.length).toBe(3)
  const left = layout.slice(layout.indexOf('data-position="left"'), layout.indexOf('data-position="center"'))
  const center = layout.slice(layout.indexOf('data-position="center"'), layout.indexOf('data-position="right"'))
  const right = layout.slice(layout.indexOf('data-position="right"'))
  expect(left).toContain('configuration?.logoUrl')
  expect(left).toContain('data-slot="topbar-brand-name"')
  expect(center).toContain('v-for="item in navItems.filter((i) => i.show)"')
  expect(center).toContain('item.unread')
  expect(center).toContain('<component :is="LanguageToggle" />')
  expect(right).toContain('<component :is="ThemePalettePanel" />')
  expect(right).toContain('<component :is="ThemeToggle" />')
  expect(right).toContain(':is="AccountPanel"')
  expect(right).toContain('<NuxtLink to="/auth/login">')
  expect(right).toContain('<NuxtLink to="/auth/register">')
  expect(layout).not.toContain(':is="AuthDialog"')
  expect(css).toContain("[data-slot='topbar-capsule'] {")
  expect(css).toContain('display: flex; width: max-content; max-width: 100%; min-height: 3rem;')
  expect(css).toContain('border-radius: 9999px;')
  expect(css).toContain("[data-slot='topbar-capsule'] [data-slot='button']")
  expect(css).toContain('inset 0 0 18px')
  const topNavMotion = await Bun.file(new URL('../app/motion/top-nav-width.ts', import.meta.url)).text()
  expect(layout).toContain('v-top-nav-motion')
  expect(layout).toContain('data-top-nav-content')
  expect(motion).not.toContain('transition: width 760ms')
  expect(topNavMotion).toContain('topNavMotionDuration = 760')
  expect(topNavMotion).toContain('scaleX(${scaleX})')
  expect(topNavMotion).toContain('scaleX(${1 / scaleX})')
  expect(topNavMotion).toContain("matchMedia('(prefers-reduced-motion: reduce)')")
  expect(motion).toContain('opacity 520ms ease-out, transform 760ms var(--ui-ease)')
  expect(workspace).toContain('class="settings-workspace-page"')
  expect(workspace).toContain('<ChoiceSidebar')
  expect(workspace).toContain('<style src="./settings-workspace.css"></style>')
  expect(workspaceCss).toContain('.settings-workspace-page { width: 100%; min-height: calc(100svh - 5rem);')

  const controller = await Bun.file(new URL('../app/features/shell/useDefaultLayout.ts', import.meta.url)).text()
  expect(controller).toContain("to: '/admin/platform'")
  expect(controller).toContain("to: '/notifications'")
  expect(controller).toContain('unread: hasUnread.value')
})
