/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationPlatformAdminPlatformConfigurationResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAdministrationPlatformAdminPlatformConfigurationResponse, serializeNoCTFAPIEndpointsAdministrationPlatformPatchPlatformConfigurationRequest, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationPlatformAdminPlatformConfigurationResponse, type NoCTFAPIEndpointsAdministrationPlatformPatchPlatformConfigurationRequest } from '../../../../../models/index.js';
// @ts-ignore
import { LogoRequestBuilderRequestsMetadata, type LogoRequestBuilder } from './logo/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/platform/configuration
 */
export interface ConfigurationRequestBuilder extends BaseRequestBuilder<ConfigurationRequestBuilder> {
    /**
     * The logo property
     */
    get logo(): LogoRequestBuilder;
    /**
     * Returns branding, human verification, email delivery and experimental feature configuration without provider or delivery secrets.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationPlatformAdminPlatformConfigurationResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationPlatformAdminPlatformConfigurationResponse | undefined>;
    /**
     * Updates selected platform configuration sections.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationPlatformAdminPlatformConfigurationResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     patch(body: NoCTFAPIEndpointsAdministrationPlatformPatchPlatformConfigurationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationPlatformAdminPlatformConfigurationResponse | undefined>;
    /**
     * Returns branding, human verification, email delivery and experimental feature configuration without provider or delivery secrets.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates selected platform configuration sections.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: NoCTFAPIEndpointsAdministrationPlatformPatchPlatformConfigurationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ConfigurationRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/platform/configuration";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ConfigurationRequestBuilderNavigationMetadata: Record<Exclude<keyof ConfigurationRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    logo: {
        requestsMetadata: LogoRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ConfigurationRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ConfigurationRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationPlatformAdminPlatformConfigurationResponseFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: ConfigurationRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationPlatformAdminPlatformConfigurationResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAdministrationPlatformPatchPlatformConfigurationRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
