/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookCreatedResponseFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookFailureResponseFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTargetListResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookCreatedResponse, serializeNoCTFAPIEndpointsAdministrationCompetitionsCreateCompetitionWebhookRequest, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookCreatedResponse, type NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookFailureResponse, type NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTargetListResponse, type NoCTFAPIEndpointsAdministrationCompetitionsCreateCompetitionWebhookRequest } from '../../../../../../models/index.js';
// @ts-ignore
import { type WithTargetItemRequestBuilder, WithTargetItemRequestBuilderNavigationMetadata, WithTargetItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/webhooks
 */
export interface WebhooksRequestBuilder extends BaseRequestBuilder<WebhooksRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.admin.competitions.item.webhooks.item collection
     * @param targetId Unique identifier of the item
     * @returns {WithTargetItemRequestBuilder}
     */
     byTargetId(targetId: Guid) : WithTargetItemRequestBuilder;
    /**
     * Returns an offset page of targets with endpoint details redacted for read-only staff.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTargetListResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<WebhooksRequestBuilderGetQueryParameters> | undefined) : Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTargetListResponse | undefined>;
    /**
     * Creates an outbound competition webhook target.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookCreatedResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookFailureResponse} error when the service returns a 409 status code
     */
     post(body: NoCTFAPIEndpointsAdministrationCompetitionsCreateCompetitionWebhookRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookCreatedResponse | undefined>;
    /**
     * Returns an offset page of targets with endpoint details redacted for read-only staff.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<WebhooksRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Creates an outbound competition webhook target.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsAdministrationCompetitionsCreateCompetitionWebhookRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Returns an offset page of targets with endpoint details redacted for read-only staff.
 */
export interface WebhooksRequestBuilderGetQueryParameters {
    desc?: boolean;
    limit?: number;
    offset?: number;
}
/**
 * Uri template for the request builder.
 */
export const WebhooksRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/webhooks?desc={desc}&limit={limit}&offset={offset}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WebhooksRequestBuilderNavigationMetadata: Record<Exclude<keyof WebhooksRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTargetId: {
        requestsMetadata: WithTargetItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithTargetItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["targetId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WebhooksRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WebhooksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookTargetListResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: WebhooksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookFailureResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationCompetitionsCompetitionWebhookCreatedResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAdministrationCompetitionsCreateCompetitionWebhookRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
