/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsInternalInternalResultResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsInternalInternalResultResponse, serializeNoCTFAPIEndpointsInternalRecordAwdCheckResultRequest, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsInternalInternalResultResponse, type NoCTFAPIEndpointsInternalRecordAwdCheckResultRequest } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/internal/v1/awd/check-results
 */
export interface CheckResultsRequestBuilder extends BaseRequestBuilder<CheckResultsRequestBuilder> {
    /**
     * Records the result of one independently persisted AWD checker execution. Runtime and gameplay-fact identities come from the internal JWT.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsInternalInternalResultResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     * @throws {NoCTFAPIEndpointsInternalInternalResultResponse} error when the service returns a 409 status code
     */
     post(body: NoCTFAPIEndpointsInternalRecordAwdCheckResultRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsInternalInternalResultResponse | undefined>;
    /**
     * Records the result of one independently persisted AWD checker execution. Runtime and gameplay-fact identities come from the internal JWT.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsInternalRecordAwdCheckResultRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CheckResultsRequestBuilderUriTemplate = "{+baseurl}/api/internal/v1/awd/check-results";
/**
 * Metadata for all the requests in the request builder.
 */
export const CheckResultsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: CheckResultsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createNoCTFAPIEndpointsInternalInternalResultResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsInternalInternalResultResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsInternalRecordAwdCheckResultRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
