/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAdministrationPlatformSsoProviderConnectionTestResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAdministrationPlatformSsoProviderConnectionTestResponse } from '../../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/platform/sso/providers/{providerId}/connection-tests
 */
export interface ConnectionTestsRequestBuilder extends BaseRequestBuilder<ConnectionTestsRequestBuilder> {
    /**
     * Tests provider network, TLS and protocol metadata without authenticating a user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationPlatformSsoProviderConnectionTestResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationPlatformSsoProviderConnectionTestResponse | undefined>;
    /**
     * Tests provider network, TLS and protocol metadata without authenticating a user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ConnectionTestsRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/platform/sso/providers/{providerId}/connection-tests";
/**
 * Metadata for all the requests in the request builder.
 */
export const ConnectionTestsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ConnectionTestsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationPlatformSsoProviderConnectionTestResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
