/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithFlowItemRequestBuilder, WithFlowItemRequestBuilderNavigationMetadata, WithFlowItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/sso/flows
 */
export interface FlowsRequestBuilder extends BaseRequestBuilder<FlowsRequestBuilder> {
    /**
     * Gets an item from the NoCTF.api.v1.auth.sso.flows.item collection
     * @param flowId Unique identifier of the item
     * @returns {WithFlowItemRequestBuilder}
     */
     byFlowId(flowId: Guid) : WithFlowItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const FlowsRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/sso/flows";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FlowsRequestBuilderNavigationMetadata: Record<Exclude<keyof FlowsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byFlowId: {
        requestsMetadata: WithFlowItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithFlowItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["flowId"],
    },
};
/* tslint:enable */
/* eslint-enable */
