/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAdministrationPlatformPrivateAccountResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAdministrationPlatformPrivateAccountResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/platform/users/{userId}/activity
 */
export interface ActivityRequestBuilder extends BaseRequestBuilder<ActivityRequestBuilder> {
    /**
     * Platform administrators only. Returns at most 50 events within the configured retention window. Self-reported identity is not verified.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationPlatformPrivateAccountResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationPlatformPrivateAccountResponse | undefined>;
    /**
     * Platform administrators only. Returns at most 50 events within the configured retention window. Self-reported identity is not verified.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ActivityRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/platform/users/{userId}/activity";
/**
 * Metadata for all the requests in the request builder.
 */
export const ActivityRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ActivityRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationPlatformPrivateAccountResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
