/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ChallengesRequestBuilderNavigationMetadata, ChallengesRequestBuilderRequestsMetadata, type ChallengesRequestBuilder } from './challenges/index.js';
// @ts-ignore
import { CompetitionsRequestBuilderNavigationMetadata, CompetitionsRequestBuilderRequestsMetadata, type CompetitionsRequestBuilder } from './competitions/index.js';
// @ts-ignore
import { PlatformRequestBuilderNavigationMetadata, type PlatformRequestBuilder } from './platform/index.js';
// @ts-ignore
import { RuntimesRequestBuilderNavigationMetadata, type RuntimesRequestBuilder } from './runtimes/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin
 */
export interface AdminRequestBuilder extends BaseRequestBuilder<AdminRequestBuilder> {
    /**
     * The challenges property
     */
    get challenges(): ChallengesRequestBuilder;
    /**
     * The competitions property
     */
    get competitions(): CompetitionsRequestBuilder;
    /**
     * The platform property
     */
    get platform(): PlatformRequestBuilder;
    /**
     * The runtimes property
     */
    get runtimes(): RuntimesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AdminRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AdminRequestBuilderNavigationMetadata: Record<Exclude<keyof AdminRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    challenges: {
        requestsMetadata: ChallengesRequestBuilderRequestsMetadata,
        navigationMetadata: ChallengesRequestBuilderNavigationMetadata,
    },
    competitions: {
        requestsMetadata: CompetitionsRequestBuilderRequestsMetadata,
        navigationMetadata: CompetitionsRequestBuilderNavigationMetadata,
    },
    platform: {
        navigationMetadata: PlatformRequestBuilderNavigationMetadata,
    },
    runtimes: {
        navigationMetadata: RuntimesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
