<script setup lang="ts">
import { toRefs } from 'vue'
import type { ChallengeWriteUpReviewState } from '~/features/writeups/useChallengeWriteUpReview'
const props = defineProps<{ state: ChallengeWriteUpReviewState }>()
const { selected, loading, previewLoading, pending, error, previewError, search, filter, source, page, limit, total, canManage, canJudge,
  display, submittedContent, publishedContent, submittedPdf, publishedPdf, reason, confirmation, settingsOpen, officialOpen, officialChallengeId,
  challengeOptions, selectedId, selectedVersion, publishedVersion, statusKey, pageCount, options, load, select, changePage, changeLimit, requestPublish,
  requestWithdraw, setConfirmationOpen, confirmReview, reject, openOfficial, consultation, competitionId, Settings, Editor, setDisplay, setPanel, narrow, panel, enabled, publishVersion, canPublish, canReject, publicationLabel, publicationBlocked, publicationNotice, confirmationTarget, confirmationSettings, competitionStatus, bindOfficialEditor, setOfficialOpen, changeOfficialChallenge } = toRefs(props.state)
</script>
<template>
  <section class="flex min-h-0 flex-1 flex-col gap-4">
    <header class="flex flex-wrap items-center justify-between gap-3"><h2 class="text-lg font-semibold">{{ $t('challengeWriteUp.review') }}</h2><div class="flex flex-wrap gap-2"><Button v-if="canManage" variant="outline" @click="openOfficial">{{ $t('challengeWriteUp.official') }}</Button><Dialog v-model:open="settingsOpen"><DialogTrigger as-child><Button variant="outline">{{ $t('challengeWriteUp.settings') }}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{{ $t('challengeWriteUp.settings') }}</DialogTitle></DialogHeader><component :is="Settings" :competition-id="competitionId" :can-write="canManage" @saved="load" /></DialogContent></Dialog></div></header>
    <ToggleGroup v-if="narrow" type="single" :model-value="panel" :aria-label="$t('challengeWriteUp.review')" @update:model-value="setPanel"><ToggleGroupItem value="list">{{ $t('challengeWriteUp.submissions') }}</ToggleGroupItem><ToggleGroupItem value="preview" :disabled="!selected">{{ $t('challengeWriteUp.preview') }}</ToggleGroupItem><ToggleGroupItem value="actions" :disabled="!selected">{{ $t('challengeWriteUp.reviewActions') }}</ToggleGroupItem></ToggleGroup>
    <div class="grid min-h-0 flex-1 gap-5 xl:grid-cols-[15rem_minmax(0,1fr)_19rem]">
      <ChoiceSidebar v-if="!narrow || panel === 'list'" contained :items="options" :model-value="selectedId" :loading="loading" :label="$t('challengeWriteUp.review')" :loading-label="$t('challengeWriteUp.review')" :empty-label="$t('challengeWriteUp.noReview')" @update:model-value="select">
        <template #header><div class="space-y-3"><Input v-model="search" :placeholder="$t('challengeWriteUp.search')" :aria-label="$t('challengeWriteUp.search')" />
          <Select v-model="filter"><SelectTrigger :aria-label="$t('common.label.status')"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Submitted">{{ $t('challengeWriteUp.pending') }}</SelectItem><SelectItem value="Published">{{ $t('challengeWriteUp.published') }}</SelectItem><SelectItem value="Rejected">{{ $t('challengeWriteUp.rejected') }}</SelectItem><SelectItem value="Draft">{{ $t('challengeWriteUp.draft') }}</SelectItem><SelectItem value="All">{{ $t('challengeWriteUp.all') }}</SelectItem></SelectContent></Select>
          <Select v-model="source"><SelectTrigger :aria-label="$t('challengeWriteUp.source')"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="All">{{ $t('challengeWriteUp.all') }}</SelectItem><SelectItem value="Official">{{ $t('challengeWriteUp.official') }}</SelectItem><SelectItem value="Team">{{ $t('challengeWriteUp.teams') }}</SelectItem></SelectContent></Select>
        </div></template>
        <template #item="{ item }"><span class="flex min-w-0 flex-col gap-1"><span class="truncate font-medium">{{ item.row.challengeTitle }}</span><span class="truncate text-xs text-muted-foreground">{{ item.row.source === 'Official' ? $t('challengeWriteUp.official') : item.row.authorName }} · {{ $t(item.statusKey) }}</span></span></template>
        <template #footer><OffsetPagination :page="page" :page-count="pageCount" :limit="limit" :total="total" :loading="loading" @update:page="changePage" @update:limit="changeLimit" /></template>
      </ChoiceSidebar>
      <Card v-if="!narrow || panel === 'preview'" class="flex min-h-0 min-w-0 flex-col"><CardHeader v-if="selected"><CardTitle>{{ selected.challengeTitle }}</CardTitle><div class="flex flex-wrap gap-2"><Badge>{{ $t(statusKey) }}</Badge><Badge v-if="display !== 'published' && selectedVersion" variant="secondary">{{ $t('challengeWriteUp.submissionVersion') }} · {{ $t('challengeWriteUp.version', { number: selectedVersion.number ?? 1 }) }}</Badge><Badge v-if="display !== 'submitted' && publishedVersion" variant="secondary">{{ $t('challengeWriteUp.publishedVersion') }} · {{ $t('challengeWriteUp.version', { number: publishedVersion.number ?? 1 }) }}</Badge><span class="text-xs text-muted-foreground">{{ $t('challengeWriteUp.reviewedBy', { name: selectedVersion?.actorDisplayName ?? $t('challengeWriteUp.deletedUser'), time: formatDateTime(selectedVersion?.submittedAt ?? selectedVersion?.updatedAt) }) }}</span></div>
        <ToggleGroup type="single" :model-value="display" :aria-label="$t('challengeWriteUp.preview')" @update:model-value="setDisplay"><ToggleGroupItem value="submitted">{{ $t('challengeWriteUp.submissionVersion') }}</ToggleGroupItem><ToggleGroupItem value="published" :disabled="!publishedVersion">{{ $t('challengeWriteUp.publishedVersion') }}</ToggleGroupItem><ToggleGroupItem value="compare" :disabled="!publishedVersion">{{ $t('challengeWriteUp.compare') }}</ToggleGroupItem></ToggleGroup>
      </CardHeader><CardContent class="min-h-0 flex-1">
        <Alert v-if="previewError" variant="destructive"><AlertDescription>{{ $message(previewError) }}</AlertDescription></Alert>
        <Skeleton v-if="previewLoading" class="h-80 w-full" />
        <MarkdownDiff v-else-if="display === 'compare' && submittedContent?.format === 'Markdown' && publishedContent?.format === 'Markdown'" :original="publishedContent.markdown ?? ''" :updated="submittedContent.markdown ?? ''" :original-label="$t('challengeWriteUp.publishedVersion')" :updated-label="$t('challengeWriteUp.submissionVersion')" />
        <div v-else-if="selected" class="grid h-full min-h-0 gap-4" :class="display === 'compare' ? 'lg:grid-cols-2' : ''">
          <div v-if="display !== 'published'" class="h-full min-h-0 min-w-0"><ScrollSurface v-if="submittedContent?.format === 'Markdown'" axis="both" class="h-full min-h-0"><MarkdownContent v-if="submittedContent?.format === 'Markdown'" :source="submittedContent.markdown ?? ''" class="max-w-[75ch] leading-7" /></ScrollSurface><PdfPreview v-else-if="submittedContent?.format === 'Pdf'" fill :source="submittedPdf" :accessible-label="$t('challengeWriteUp.submissionVersion')" :empty-label="$t('challengeWriteUp.previewEmpty')" /></div>
          <div v-if="display !== 'submitted'" class="h-full min-h-0 min-w-0"><ScrollSurface v-if="publishedContent?.format === 'Markdown'" axis="both" class="h-full min-h-0"><MarkdownContent v-if="publishedContent?.format === 'Markdown'" :source="publishedContent.markdown ?? ''" class="max-w-[75ch] leading-7" /></ScrollSurface><PdfPreview v-else-if="publishedContent?.format === 'Pdf'" fill :source="publishedPdf" :accessible-label="$t('challengeWriteUp.publishedVersion')" :empty-label="$t('challengeWriteUp.previewEmpty')" /></div>
        </div><Empty v-else><EmptyHeader><EmptyTitle>{{ $t('challengeWriteUp.reviewEmpty') }}</EmptyTitle></EmptyHeader></Empty>
      </CardContent></Card>
      <Card v-if="selected && (!narrow || panel === 'actions')" size="sm" class="flex min-h-0 flex-col"><CardHeader><CardTitle>{{ $t('challengeWriteUp.review') }}</CardTitle></CardHeader><CardContent class="min-h-0 flex-1"><ScrollSurface class="h-full"><div class="space-y-4">
        <Alert v-if="error" variant="destructive"><AlertDescription>{{ $message(error) }}</AlertDescription></Alert>
        <p v-if="!enabled" class="text-sm text-muted-foreground">{{ $t('challengeWriteUp.disabled') }}</p><p class="text-sm text-muted-foreground">{{ $t('challengeWriteUp.viewedTeams', { count: selected.viewedTeamCount ?? 0 }) }}</p>
        <component :is="Settings" :key="selected.competitionChallengeId" :competition-id="competitionId" :competition-challenge-id="selected.competitionChallengeId" :can-write="canManage" />
        <FieldDescription v-if="publicationNotice">{{ $t('challengeWriteUp.submittedPublishFailed') }}</FieldDescription>
        <FieldDescription v-if="canManage && publicationBlocked">{{ $t(publicationBlocked) }}</FieldDescription>
        <Separator /><Field v-if="canJudge"><FieldLabel>{{ $t('challengeWriteUp.returnReason') }}</FieldLabel><Textarea v-model="reason" :disabled="pending" :placeholder="$t('challengeWriteUp.returnReasonPlaceholder')" /></Field>
      </div></ScrollSurface></CardContent><CardFooter class="shrink-0"><div class="flex w-full flex-col gap-2"><Button v-if="canJudge" variant="outline" :disabled="!canReject" @click="reject">{{ $t('challengeWriteUp.return') }}</Button><Button v-if="canManage" :disabled="!canPublish" @click="requestPublish">{{ publishVersion ? $t(publicationLabel, { number: publishVersion.number ?? 1 }) : $t('challengeWriteUp.publish') }}</Button><Button v-if="canManage && selected.publishedVersionId" variant="destructive" :disabled="pending" @click="requestWithdraw">{{ $t('challengeWriteUp.withdraw') }}</Button><Button v-if="canJudge && selected.teamId" variant="ghost" :disabled="pending" @click="consultation">{{ $t('challengeWriteUp.consultation') }}</Button></div>
      </CardFooter></Card>
    </div>
    <AlertDialog :open="confirmation !== null" @update:open="setConfirmationOpen"><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{{ confirmation === 'Withdraw' ? $t('challengeWriteUp.withdrawTitle') : $t('challengeWriteUp.publishTitle') }}</AlertDialogTitle><AlertDialogDescription>{{ confirmation === 'Withdraw' ? $t('challengeWriteUp.withdrawDescription') : $t('challengeWriteUp.publishDescription') }}</AlertDialogDescription></AlertDialogHeader><p class="text-sm">{{ confirmationTarget?.challengeTitle }} · {{ confirmationTarget?.authorName || $t('challengeWriteUp.official') }} · {{ $t('challengeWriteUp.version', { number: confirmationTarget?.number ?? 1 }) }}</p><p v-if="confirmation === 'Publish'" class="text-sm">{{ $t('challengeWriteUp.deduction', { percent: confirmationSettings?.deductionPercent ?? 20, retained: 100 - (confirmationSettings?.deductionPercent ?? 20) }) }}</p><p v-if="competitionStatus" class="text-sm">{{ $t('common.label.status') }}: {{ enumLabel(CompetitionStatusLabel, competitionStatus) }}</p><AlertDialogFooter><AlertDialogCancel :disabled="pending">{{ $t('common.action.cancel') }}</AlertDialogCancel><Button :disabled="pending" @click="confirmReview"><Spinner v-if="pending" />{{ confirmation === 'Withdraw' ? $t('challengeWriteUp.withdraw') : $t(confirmationTarget?.state === 'Draft' ? 'challengeWriteUp.publishDraft' : confirmationTarget?.state === 'Approved' ? 'challengeWriteUp.republishVersion' : 'challengeWriteUp.publishSubmitted', { number: confirmationTarget?.number ?? 1 }) }}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Dialog :open="officialOpen" @update:open="setOfficialOpen"><DialogContent class="flex h-[calc(100dvh-2rem)] w-[calc(100%-2rem)] min-h-0 flex-col sm:max-w-5xl" :aria-describedby="undefined"><DialogHeader class="shrink-0 pr-8"><DialogTitle>{{ $t('challengeWriteUp.officialEditor') }}</DialogTitle></DialogHeader><Select :model-value="officialChallengeId" @update:model-value="changeOfficialChallenge"><SelectTrigger class="shrink-0" :aria-label="$t('challengeWriteUp.pickChallenge')"><SelectValue /></SelectTrigger><SelectContent><SelectItem v-for="item in challengeOptions" :key="item.value" :value="item.value">{{ item.label }}</SelectItem></SelectContent></Select><component :is="Editor" :ref="bindOfficialEditor" v-if="officialChallengeId" :key="officialChallengeId" :competition-id="competitionId" :competition-challenge-id="officialChallengeId" official embedded @saved="load" @close="setOfficialOpen(false)" /></DialogContent></Dialog>
  </section>
</template>
