/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationRuntimeRuntimeFlagListResponseFromDiscriminatorValue, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationRuntimeRuntimeFlagListResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/runtimes/{runtimeInstanceId}/flags
 */
export interface FlagsRequestBuilder extends BaseRequestBuilder<FlagsRequestBuilder> {
    /**
     * Returns paginated protected flag records and their typed scope and validity to authorized administrators or template managers. Responses must not be cached.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationRuntimeRuntimeFlagListResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<FlagsRequestBuilderGetQueryParameters> | undefined) : Promise<NoCTFAPIEndpointsAdministrationRuntimeRuntimeFlagListResponse | undefined>;
    /**
     * Returns paginated protected flag records and their typed scope and validity to authorized administrators or template managers. Responses must not be cached.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<FlagsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns paginated protected flag records and their typed scope and validity to authorized administrators or template managers. Responses must not be cached.
 */
export interface FlagsRequestBuilderGetQueryParameters {
    desc?: boolean;
    includeHistory?: boolean;
    limit?: number;
    offset?: number;
}
/**
 * Uri template for the request builder.
 */
export const FlagsRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/runtimes/{runtimeInstanceId}/flags?desc={desc}&includeHistory={includeHistory}&limit={limit}&offset={offset}";
/**
 * Metadata for all the requests in the request builder.
 */
export const FlagsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FlagsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationRuntimeRuntimeFlagListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
