apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: noctf-non-runtime-allow
spec:
  endpointSelector:
    matchExpressions:
      - key: io.kubernetes.pod.namespace
        operator: Exists
      - key: io.cilium.k8s.namespace.labels.noctf.io/purpose
        operator: NotIn
        values:
          - challenge-runtime
  ingress:
    - fromEntities:
        - all
  egress:
    - toEntities:
        - all
