/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAuthenticationCurrentUserResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAuthenticationCurrentUserResponse } from '../../../../models/index.js';
// @ts-ignore
import { AvatarRequestBuilderRequestsMetadata, type AvatarRequestBuilder } from './avatar/index.js';
// @ts-ignore
import { ProfileRequestBuilderRequestsMetadata, type ProfileRequestBuilder } from './profile/index.js';
// @ts-ignore
import { ProfileCoverRequestBuilderRequestsMetadata, type ProfileCoverRequestBuilder } from './profileCover/index.js';
// @ts-ignore
import { SsoBindingRequestBuilderNavigationMetadata, SsoBindingRequestBuilderRequestsMetadata, type SsoBindingRequestBuilder } from './ssoBinding/index.js';
// @ts-ignore
import { type WallpaperRequestBuilder, WallpaperRequestBuilderRequestsMetadata } from './wallpaper/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/auth/me
 */
export interface MeRequestBuilder extends BaseRequestBuilder<MeRequestBuilder> {
    /**
     * The avatar property
     */
    get avatar(): AvatarRequestBuilder;
    /**
     * The profile property
     */
    get profile(): ProfileRequestBuilder;
    /**
     * The profileCover property
     */
    get profileCover(): ProfileCoverRequestBuilder;
    /**
     * The ssoBinding property
     */
    get ssoBinding(): SsoBindingRequestBuilder;
    /**
     * The wallpaper property
     */
    get wallpaper(): WallpaperRequestBuilder;
    /**
     * Returns the authenticated account profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAuthenticationCurrentUserResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAuthenticationCurrentUserResponse | undefined>;
    /**
     * Returns the authenticated account profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MeRequestBuilderUriTemplate = "{+baseurl}/api/v1/auth/me";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MeRequestBuilderNavigationMetadata: Record<Exclude<keyof MeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    avatar: {
        requestsMetadata: AvatarRequestBuilderRequestsMetadata,
    },
    profile: {
        requestsMetadata: ProfileRequestBuilderRequestsMetadata,
    },
    profileCover: {
        requestsMetadata: ProfileCoverRequestBuilderRequestsMetadata,
    },
    ssoBinding: {
        requestsMetadata: SsoBindingRequestBuilderRequestsMetadata,
        navigationMetadata: SsoBindingRequestBuilderNavigationMetadata,
    },
    wallpaper: {
        requestsMetadata: WallpaperRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MeRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAuthenticationCurrentUserResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
