/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue, createNoCTFAPIEndpointsAdministrationGameplayFactsQueueGameplayFactWorkResponseFromDiscriminatorValue, serializeNoCTFAPIEndpointsAdministrationGameplayFactsQueueGameplayFactWorkRequest, serializeNoCTFAPIEndpointsAdministrationGameplayFactsQueueGameplayFactWorkResponse, type MicrosoftAspNetCoreMvcValidationProblemDetails, type NoCTFAPIEndpointsAdministrationGameplayFactsQueueGameplayFactWorkRequest, type NoCTFAPIEndpointsAdministrationGameplayFactsQueueGameplayFactWorkResponse } from '../../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/gameplay-facts/queue-evaluation
 */
export interface QueueEvaluationRequestBuilder extends BaseRequestBuilder<QueueEvaluationRequestBuilder> {
    /**
     * Creates cutoff-bounded durable work for eligible ManualBatch or first-failure gameplay facts.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationGameplayFactsQueueGameplayFactWorkResponse>}
     * @throws {MicrosoftAspNetCoreMvcValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: NoCTFAPIEndpointsAdministrationGameplayFactsQueueGameplayFactWorkRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationGameplayFactsQueueGameplayFactWorkResponse | undefined>;
    /**
     * Creates cutoff-bounded durable work for eligible ManualBatch or first-failure gameplay facts.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: NoCTFAPIEndpointsAdministrationGameplayFactsQueueGameplayFactWorkRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QueueEvaluationRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/gameplay-facts/queue-evaluation";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueueEvaluationRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: QueueEvaluationRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createMicrosoftAspNetCoreMvcValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationGameplayFactsQueueGameplayFactWorkResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeNoCTFAPIEndpointsAdministrationGameplayFactsQueueGameplayFactWorkRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
