// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoCTF.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NoCTF.Infrastructure.Migrations
{
    [DbContext(typeof(NoCtfDbContext))]
    partial class NoCtfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NoCTF.Domain.Challenges.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("definition_json");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("direction");

                    b.PrimitiveCollection<Guid[]>("ManagerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("manager_ids");

                    b.Property<short>("Mode")
                        .HasColumnType("smallint")
                        .HasColumnName("mode");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<short>("Visibility")
                        .HasColumnType("smallint")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_challenges");

                    b.HasIndex("ManagerIds")
                        .HasDatabaseName("ix_challenges_manager_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ManagerIds"), "gin");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_challenges_owner_id");

                    b.ToTable("challenges", null, t =>
                        {
                            t.HasCheckConstraint("ck_challenges_owner_not_manager", "NOT (owner_id = ANY(manager_ids))");
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Challenges.ChallengeAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.HasKey("Id")
                        .HasName("pk_challenge_attachments");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_challenge_attachments_challenge_id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_challenge_attachments_file_id");

                    b.ToTable("challenge_attachments", (string)null);
                });

            modelBuilder.Entity("NoCTF.Domain.Challenges.ChallengeFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id");

                    b.Property<Guid?>("CompetitionChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_challenge_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flag");

                    b.Property<byte[]>("FlagSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("flag_sha256");

                    b.Property<short>("MatchKind")
                        .HasColumnType("smallint")
                        .HasColumnName("match_kind");

                    b.Property<Guid?>("SpecificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("specification_id");

                    b.Property<short?>("SpecificationKind")
                        .HasColumnType("smallint")
                        .HasColumnName("specification_kind");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset?>("ValidStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_start");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_challenge_flags");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_challenge_flags_team_id");

                    b.HasIndex("ChallengeId", "FlagSha256")
                        .HasDatabaseName("ix_challenge_flags_challenge_id_flag_sha256")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("CompetitionChallengeId", "FlagSha256")
                        .HasDatabaseName("ix_challenge_flags_competition_challenge_id_flag_sha256")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("SpecificationKind", "SpecificationId")
                        .IsUnique()
                        .HasDatabaseName("ix_challenge_flags_specification_kind_specification_id")
                        .HasFilter("specification_kind = 4 AND deleted_at IS NULL");

                    b.HasIndex("CompetitionChallengeId", "TeamId", "SpecificationKind", "SpecificationId")
                        .HasDatabaseName("ix_challenge_flags_competition_challenge_id_team_id_specificat");

                    b.ToTable("challenge_flags", null, t =>
                        {
                            t.HasCheckConstraint("ck_challenge_flags_scope", "(challenge_id IS NULL) <> (competition_challenge_id IS NULL)");

                            t.HasCheckConstraint("ck_challenge_flags_specification", "(specification_kind IS NULL) = (specification_id IS NULL)");
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Challenges.CompetitionChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<string>("CustomTitle")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("custom_title");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rules_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_competition_challenges");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_competition_challenges_challenge_id");

                    b.HasIndex("CompetitionId", "ChallengeId")
                        .IsUnique()
                        .HasDatabaseName("ix_competition_challenges_competition_id_challenge_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("CompetitionId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_competition_challenges_competition_id_order")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("competition_challenges", (string)null);
                });

            modelBuilder.Entity("NoCTF.Domain.Competitions.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowChallengeOwnersToHandleQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_challenge_owners_to_handle_questions");

                    b.Property<bool>("AllowTeamRegistrationWhileRunning")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_team_registration_while_running");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<byte[]>("FlagDerivationSecret")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("flag_derivation_secret");

                    b.Property<DateTimeOffset?>("FrozenStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("frozen_start_at");

                    b.Property<DateTimeOffset?>("HiddenStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_start_at");

                    b.PrimitiveCollection<Guid[]>("JudgeIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("judge_ids");

                    b.PrimitiveCollection<Guid[]>("ManagerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("manager_ids");

                    b.Property<int>("MaxActiveQuestionsPerTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_active_questions_per_team");

                    b.Property<int>("MaxConcurrentRuntimeInstancesPerTeam")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_runtime_instances_per_team");

                    b.Property<int>("MaxParticipantMessagesBeforeHandlerReply")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_participant_messages_before_handler_reply");

                    b.Property<int>("MaxTeamMembers")
                        .HasColumnType("integer")
                        .HasColumnName("max_team_members");

                    b.Property<short>("Mode")
                        .HasColumnType("smallint")
                        .HasColumnName("mode");

                    b.PrimitiveCollection<Guid[]>("ObserverIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("observer_ids");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("PosterFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("poster_file_id");

                    b.Property<bool>("PracticeModeEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("practice_mode_enabled");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<bool>("TeamRegistrationAutoApprove")
                        .HasColumnType("boolean")
                        .HasColumnName("team_registration_auto_approve");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<string>("TrackConfigurationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("track_configuration_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.HasIndex("JudgeIds")
                        .HasDatabaseName("ix_competitions_judge_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("JudgeIds"), "gin");

                    b.HasIndex("ManagerIds")
                        .HasDatabaseName("ix_competitions_manager_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ManagerIds"), "gin");

                    b.HasIndex("ObserverIds")
                        .HasDatabaseName("ix_competitions_observer_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ObserverIds"), "gin");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_competitions_owner_id");

                    b.HasIndex("PosterFileId")
                        .HasDatabaseName("ix_competitions_poster_file_id");

                    b.HasIndex("FrozenStartAt", "HiddenStartAt")
                        .HasDatabaseName("ix_competitions_frozen_start_at_hidden_start_at");

                    b.HasIndex("Status", "StartAt")
                        .HasDatabaseName("ix_competitions_status_start_at");

                    b.ToTable("competitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_competitions_flag_secret_length", "octet_length(flag_derivation_secret) = 32");

                            t.HasCheckConstraint("ck_competitions_owner_not_permission", "NOT (owner_id = ANY(manager_ids)) AND NOT (owner_id = ANY(judge_ids)) AND NOT (owner_id = ANY(observer_ids))");

                            t.HasCheckConstraint("ck_competitions_permission_roles_exclusive", "NOT (manager_ids && judge_ids) AND NOT (manager_ids && observer_ids) AND NOT (judge_ids && observer_ids)");

                            t.HasCheckConstraint("ck_competitions_question_limits", "max_active_questions_per_team > 0 AND max_participant_messages_before_handler_reply > 0");

                            t.HasCheckConstraint("ck_competitions_schedule", "start_at < end_at");
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Competitions.Events.CompetitionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("ParentEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_event_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("RelatedId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_id");

                    b.Property<short?>("RelatedType")
                        .HasColumnType("smallint")
                        .HasColumnName("related_type");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<short>("SubjectType")
                        .HasColumnType("smallint")
                        .HasColumnName("subject_type");

                    b.Property<short>("Visibility")
                        .HasColumnType("smallint")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_competition_events");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_competition_events_actor_user_id");

                    b.HasIndex("CompetitionId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_competition_events_competition_id_occurred_at_id");

                    b.HasIndex("ParentEventId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_competition_events_parent_event_id_occurred_at_id");

                    b.HasIndex("CompetitionId", "Kind", "OccurredAt", "Id")
                        .HasDatabaseName("ix_competition_events_competition_id_kind_occurred_at_id");

                    b.HasIndex("CompetitionId", "Level", "OccurredAt", "Id")
                        .HasDatabaseName("ix_competition_events_competition_id_level_occurred_at_id");

                    b.HasIndex("CompetitionId", "Visibility", "OccurredAt", "Id")
                        .HasDatabaseName("ix_competition_events_competition_id_visibility_occurred_at_id");

                    b.HasIndex("CompetitionId", "RelatedType", "RelatedId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_competition_events_competition_id_related_type_related_id_o")
                        .HasFilter("related_type IS NOT NULL");

                    b.HasIndex("CompetitionId", "SubjectType", "SubjectId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_competition_events_competition_id_subject_type_subject_id_o");

                    b.ToTable("competition_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_competition_events_payload", "jsonb_typeof(payload_json) = 'object' AND payload_json ? 'schemaVersion'");

                            t.HasCheckConstraint("ck_competition_events_related_reference", "(related_type IS NULL) = (related_id IS NULL)");
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Gameplay.GameplayFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CompetitionChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_challenge_id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<short?>("FailureCode")
                        .HasColumnType("smallint")
                        .HasColumnName("failure_code");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<short?>("ReferenceKind")
                        .HasColumnType("smallint")
                        .HasColumnName("reference_kind");

                    b.Property<short?>("Result")
                        .HasColumnType("smallint")
                        .HasColumnName("result");

                    b.Property<string>("SourceIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("source_ip_address");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<byte[]>("ValueSha256")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("value_sha256");

                    b.Property<Guid?>("VictimTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("victim_team_id");

                    b.HasKey("Id")
                        .HasName("pk_gameplay_facts");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_gameplay_facts_actor_user_id");

                    b.HasIndex("CompetitionChallengeId")
                        .HasDatabaseName("ix_gameplay_facts_competition_challenge_id");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_gameplay_facts_reference_id")
                        .HasFilter("reference_kind = 0");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_gameplay_facts_team_id");

                    b.HasIndex("VictimTeamId")
                        .HasDatabaseName("ix_gameplay_facts_victim_team_id");

                    b.HasIndex("CompetitionId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_gameplay_facts_competition_id_occurred_at_id");

                    b.HasIndex("CompetitionId", "TeamId", "CompetitionChallengeId", "Kind", "OccurredAt", "Id")
                        .HasDatabaseName("ix_gameplay_facts_competition_id_team_id_competition_challenge");

                    b.ToTable("gameplay_facts", null, t =>
                        {
                            t.HasCheckConstraint("ck_gameplay_facts_koh_team", "kind <> 6 OR (result = 9 AND team_id IS NOT NULL) OR (result IS DISTINCT FROM 9 AND team_id IS NULL)");

                            t.HasCheckConstraint("ck_gameplay_facts_reference", "(reference_kind IS NULL) = (reference_id IS NULL)");

                            t.HasCheckConstraint("ck_gameplay_facts_result", "result IS NULL OR (kind IN (0, 1) AND result IN (0, 1, 2, 3, 4)) OR (kind = 2 AND result IN (0, 1, 3, 4)) OR (kind = 3 AND result IN (2, 4, 5)) OR (kind = 4 AND result = 6) OR (kind = 5 AND result IN (7, 8)) OR (kind = 6 AND result IN (9, 10))");

                            t.HasCheckConstraint("ck_gameplay_facts_shape", "(kind = 0 AND team_id IS NOT NULL AND actor_user_id IS NOT NULL AND value IS NOT NULL AND octet_length(value_sha256) = 32 AND (reference_kind IS NULL OR reference_kind = 2)) OR (kind = 1 AND team_id IS NOT NULL AND actor_user_id IS NOT NULL AND value IS NOT NULL AND octet_length(value_sha256) = 32 AND reference_kind IS NULL) OR (kind = 2 AND team_id IS NOT NULL AND actor_user_id IS NOT NULL AND value IS NULL AND value_sha256 IS NULL AND reference_kind = 0) OR (kind = 3 AND team_id IS NOT NULL AND actor_user_id IS NOT NULL AND value IS NULL AND value_sha256 IS NULL AND reference_kind = 1) OR (kind = 4 AND team_id IS NOT NULL AND actor_user_id IS NOT NULL AND value ~ '^-?(0|[1-9][0-9]*)$' AND value <> '0' AND value <> '-0' AND value::bigint BETWEEN -2147483648 AND 2147483647 AND value_sha256 IS NULL AND reference_kind IS NULL) OR (kind = 5 AND team_id IS NOT NULL AND actor_user_id IS NULL AND value IS NULL AND value_sha256 IS NULL AND reference_kind IS NULL AND victim_team_id IS NULL) OR (kind = 6 AND actor_user_id IS NULL AND value IS NULL AND value_sha256 IS NULL AND reference_kind IS NULL AND victim_team_id IS NULL)");

                            t.HasCheckConstraint("ck_gameplay_facts_state_result", "state <> 3 OR result IS NOT NULL");

                            t.HasCheckConstraint("ck_gameplay_facts_victim", "victim_team_id IS NULL OR kind IN (0, 1)");
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Gameplay.PatchUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_challenge_id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<Guid?>("RuntimeInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("runtime_instance_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_patch_uploads");

                    b.HasIndex("CompetitionChallengeId")
                        .HasDatabaseName("ix_patch_uploads_competition_challenge_id");

                    b.HasIndex("CompetitionId")
                        .HasDatabaseName("ix_patch_uploads_competition_id");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("ix_patch_uploads_file_id");

                    b.HasIndex("RuntimeInstanceId")
                        .IsUnique()
                        .HasDatabaseName("ix_patch_uploads_runtime_instance_id")
                        .HasFilter("runtime_instance_id IS NOT NULL");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_patch_uploads_uploaded_by_user_id");

                    b.HasIndex("TeamId", "CompetitionChallengeId")
                        .HasDatabaseName("ix_patch_uploads_team_id_competition_challenge_id");

                    b.ToTable("patch_uploads", (string)null);
                });

            modelBuilder.Entity("NoCTF.Domain.Identity.AccountToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<byte[]>("TokenSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_sha256");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_account_tokens");

                    b.HasIndex("TokenSha256")
                        .IsUnique()
                        .HasDatabaseName("ix_account_tokens_token_sha256");

                    b.HasIndex("UserId", "Kind", "CreatedAt")
                        .HasDatabaseName("ix_account_tokens_user_id_kind_created_at");

                    b.ToTable("account_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_account_tokens_consumed_at", "consumed_at IS NULL OR consumed_at >= created_at");

                            t.HasCheckConstraint("ck_account_tokens_email_not_invalidated", "kind <> 0 OR invalidated_at IS NULL");

                            t.HasCheckConstraint("ck_account_tokens_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_account_tokens_hash_length", "octet_length(token_sha256) = 32");

                            t.HasCheckConstraint("ck_account_tokens_invalidated_at", "invalidated_at IS NULL OR invalidated_at >= created_at");

                            t.HasCheckConstraint("ck_account_tokens_terminal_state", "consumed_at IS NULL OR invalidated_at IS NULL");
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AccountStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("account_status");

                    b.Property<Guid?>("AvatarFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_file_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<string>("SchoolFullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("school_full_name");

                    b.Property<string>("SchoolStudentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("school_student_number");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("integer")
                        .HasColumnName("token_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_name");

                    b.Property<bool>("WallpaperEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("wallpaper_enabled");

                    b.Property<Guid?>("WallpaperFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallpaper_file_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AvatarFileId")
                        .HasDatabaseName("ix_users_avatar_file_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("email <> ''");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_user_name");

                    b.HasIndex("WallpaperFileId")
                        .HasDatabaseName("ix_users_wallpaper_file_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_bot_role", "\"kind\" <> 1 OR \"role\" IN (0, 1)");

                            t.HasCheckConstraint("ck_users_wallpaper_enabled", "NOT \"wallpaper_enabled\" OR \"wallpaper_file_id\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid?>("RelatedId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_id");

                    b.Property<short?>("RelatedType")
                        .HasColumnType("smallint")
                        .HasColumnName("related_type");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_to_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<short>("SourceType")
                        .HasColumnType("smallint")
                        .HasColumnName("source_type");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<short>("TargetType")
                        .HasColumnType("smallint")
                        .HasColumnName("target_type");

                    b.Property<Guid?>("ThreadRootId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_root_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("ReplyToId")
                        .HasDatabaseName("ix_notifications_reply_to_id")
                        .HasFilter("reply_to_id IS NOT NULL");

                    b.HasIndex("ThreadRootId", "SentAt", "Id")
                        .HasDatabaseName("ix_notifications_thread_root_id_sent_at_id")
                        .HasFilter("thread_root_id IS NOT NULL");

                    b.HasIndex("RelatedType", "RelatedId", "SentAt", "Id")
                        .HasDatabaseName("ix_notifications_related_type_related_id_sent_at_id")
                        .HasFilter("related_type IS NOT NULL");

                    b.HasIndex("SourceType", "SourceId", "SentAt", "Id")
                        .HasDatabaseName("ix_notifications_source_type_source_id_sent_at_id")
                        .HasFilter("source_id IS NOT NULL");

                    b.HasIndex("TargetType", "TargetId", "SentAt", "Id")
                        .HasDatabaseName("ix_notifications_target_type_target_id_sent_at_id");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_content", "jsonb_typeof(content_json) = 'object' AND content_json ? 'schemaVersion'");

                            t.HasCheckConstraint("ck_notifications_platform_administrators_target", "target_type <> 4 OR target_id = 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid");

                            t.HasCheckConstraint("ck_notifications_related_reference", "(related_type IS NULL) = (related_id IS NULL)");

                            t.HasCheckConstraint("ck_notifications_source", "(source_type IN (0, 4) AND source_id IS NULL) OR (source_type IN (1, 2, 3) AND source_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_notifications_thread_root", "thread_root_id IS NULL OR thread_root_id <> id");
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Platform.PlatformSettings", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("EmailPasswordResetCooldownSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("email_password_reset_cooldown_seconds");

                    b.Property<int>("EmailPasswordResetMaxRequestsPerHour")
                        .HasColumnType("integer")
                        .HasColumnName("email_password_reset_max_requests_per_hour");

                    b.Property<int>("EmailPasswordResetTokenLifetimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("email_password_reset_token_lifetime_minutes");

                    b.Property<string>("EmailPublicBaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("email_public_base_url");

                    b.Property<string>("EmailSmtpFromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_smtp_from_address");

                    b.Property<string>("EmailSmtpFromName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_smtp_from_name");

                    b.Property<string>("EmailSmtpHost")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("email_smtp_host");

                    b.Property<byte[]>("EmailSmtpPasswordCiphertext")
                        .HasMaxLength(2048)
                        .HasColumnType("bytea")
                        .HasColumnName("email_smtp_password_ciphertext");

                    b.Property<int>("EmailSmtpPort")
                        .HasColumnType("integer")
                        .HasColumnName("email_smtp_port");

                    b.Property<short?>("EmailSmtpSecurityMode")
                        .HasColumnType("smallint")
                        .HasColumnName("email_smtp_security_mode");

                    b.Property<int>("EmailSmtpTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("email_smtp_timeout_seconds");

                    b.Property<string>("EmailSmtpUserName")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_smtp_user_name");

                    b.Property<bool>("EmailVerificationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verification_enabled");

                    b.Property<int>("EmailVerificationResendCooldownSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("email_verification_resend_cooldown_seconds");

                    b.Property<int>("EmailVerificationTokenLifetimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("email_verification_token_lifetime_minutes");

                    b.Property<Guid?>("LogoFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_file_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PublicGatewayConnectorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("public_gateway_connector_id");

                    b.Property<string>("PublicGatewayDirectHostOverride")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("public_gateway_direct_host_override");

                    b.PrimitiveCollection<string[]>("PublicGatewayDirectOrigins")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("public_gateway_direct_origins");

                    b.Property<bool>("PublicGatewayEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("public_gateway_enabled");

                    b.Property<int>("PublicGatewayMaxPorts")
                        .HasColumnType("integer")
                        .HasColumnName("public_gateway_max_ports");

                    b.Property<string>("PublicGatewayOrigin")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("public_gateway_origin");

                    b.Property<string>("PublicGatewayRuntimeHost")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("public_gateway_runtime_host");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_platform_settings");

                    b.HasIndex("LogoFileId")
                        .HasDatabaseName("ix_platform_settings_logo_file_id");

                    b.ToTable("platform_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_platform_settings_singleton", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            EmailPasswordResetCooldownSeconds = 60,
                            EmailPasswordResetMaxRequestsPerHour = 5,
                            EmailPasswordResetTokenLifetimeMinutes = 30,
                            EmailPublicBaseUrl = "http://localhost:5000",
                            EmailSmtpFromAddress = "",
                            EmailSmtpFromName = "NoCTF",
                            EmailSmtpHost = "",
                            EmailSmtpPort = 587,
                            EmailSmtpTimeoutSeconds = 30,
                            EmailSmtpUserName = "",
                            EmailVerificationEnabled = false,
                            EmailVerificationResendCooldownSeconds = 60,
                            EmailVerificationTokenLifetimeMinutes = 1440,
                            Name = "NoCTF",
                            PublicGatewayConnectorId = "",
                            PublicGatewayDirectOrigins = new string[0],
                            PublicGatewayEnabled = false,
                            PublicGatewayMaxPorts = 0,
                            PublicGatewayOrigin = "",
                            PublicGatewayRuntimeHost = "",
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Runtime.RuntimeInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id");

                    b.Property<Guid?>("CompetitionChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_challenge_id");

                    b.Property<Guid?>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<short?>("FailureCode")
                        .HasColumnType("smallint")
                        .HasColumnName("failure_code");

                    b.Property<Guid?>("GameplayFactId")
                        .HasColumnType("uuid")
                        .HasColumnName("gameplay_fact_id");

                    b.Property<string>("ProviderReceiptJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_receipt_json");

                    b.Property<short>("Purpose")
                        .HasColumnType("smallint")
                        .HasColumnName("purpose");

                    b.Property<string>("RunnerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("runner_id");

                    b.Property<DateTimeOffset?>("RunningAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("running_at");

                    b.Property<short>("RuntimeKind")
                        .HasColumnType("smallint")
                        .HasColumnName("runtime_kind");

                    b.Property<short>("RuntimeProvider")
                        .HasColumnType("smallint")
                        .HasColumnName("runtime_provider");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<short?>("TestFlagDelivery")
                        .HasColumnType("smallint")
                        .HasColumnName("test_flag_delivery");

                    b.Property<short?>("TestFlagState")
                        .HasColumnType("smallint")
                        .HasColumnName("test_flag_state");

                    b.PrimitiveCollection<string[]>("Urls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("urls");

                    b.HasKey("Id")
                        .HasName("pk_runtime_instances");

                    b.HasIndex("ChallengeId")
                        .IsUnique()
                        .HasDatabaseName("ix_runtime_instances_challenge_id")
                        .HasFilter("purpose = 4 AND state IN (0, 1, 2)");

                    b.HasIndex("CompetitionId")
                        .HasDatabaseName("ix_runtime_instances_competition_id");

                    b.HasIndex("GameplayFactId")
                        .IsUnique()
                        .HasDatabaseName("ix_runtime_instances_gameplay_fact_id")
                        .HasFilter("purpose = 1 AND gameplay_fact_id IS NOT NULL AND state IN (0, 1, 2, 3)");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_runtime_instances_team_id");

                    b.HasIndex("CompetitionChallengeId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_runtime_instances_competition_challenge_id_team_id")
                        .HasFilter("purpose IN (0, 2, 3) AND state IN (0, 1, 2)");

                    b.HasIndex("RunnerId", "State", "CreatedAt", "Id")
                        .HasDatabaseName("ix_runtime_instances_runner_id_state_created_at_id");

                    b.HasIndex("CompetitionChallengeId", "TeamId", "Purpose", "CreatedAt", "Id")
                        .HasDatabaseName("ix_runtime_instances_competition_challenge_id_team_id_purpose_");

                    b.ToTable("runtime_instances", null, t =>
                        {
                            t.HasCheckConstraint("ck_runtime_instances_awdp_gameplay_fact", "gameplay_fact_id IS NULL OR purpose = 1");

                            t.HasCheckConstraint("ck_runtime_instances_failure", "(state = 5) = (failure_code IS NOT NULL)");

                            t.HasCheckConstraint("ck_runtime_instances_scope", "(purpose = 4 AND challenge_id IS NOT NULL AND competition_id IS NULL AND competition_challenge_id IS NULL AND team_id IS NULL AND gameplay_fact_id IS NULL) OR (purpose <> 4 AND challenge_id IS NULL AND competition_id IS NOT NULL AND competition_challenge_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_runtime_instances_test_flag", "(purpose = 4) = (test_flag_delivery IS NOT NULL AND test_flag_state IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Storage.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_files_object_key");

                    b.ToTable("files", null, t =>
                        {
                            t.HasCheckConstraint("ck_files_byte_length", "byte_length >= 0");

                            t.HasCheckConstraint("ck_files_sha256_length", "octet_length(sha256) = 32");
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_file_id");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<Guid?>("BannedById")
                        .HasColumnType("uuid")
                        .HasColumnName("banned_by_id");

                    b.Property<Guid>("CaptainId")
                        .HasColumnType("uuid")
                        .HasColumnName("captain_id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("invitation_token");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<bool>("IsPracticeTeam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_practice_team");

                    b.PrimitiveCollection<Guid[]>("MemberIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("member_ids");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<short>("RegistrationStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("registration_status");

                    b.Property<string>("TrackKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("default")
                        .HasColumnName("track_key");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("AvatarFileId")
                        .HasDatabaseName("ix_teams_avatar_file_id");

                    b.HasIndex("CaptainId")
                        .HasDatabaseName("ix_teams_captain_id");

                    b.HasIndex("InvitationToken")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_invitation_token");

                    b.HasIndex("MemberIds")
                        .HasDatabaseName("ix_teams_member_ids");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MemberIds"), "gin");

                    b.HasIndex("CompetitionId", "RegistrationStatus")
                        .HasDatabaseName("ix_teams_competition_id_registration_status");

                    b.HasIndex("CompetitionId", "TrackKey")
                        .HasDatabaseName("ix_teams_competition_id_track_key");

                    b.ToTable("teams", null, t =>
                        {
                            t.HasCheckConstraint("ck_teams_captain_is_member", "captain_id = ANY(member_ids)");

                            t.HasCheckConstraint("ck_teams_invitation_token_length", "char_length(invitation_token) = 32");

                            t.HasCheckConstraint("ck_teams_members_not_empty", "cardinality(member_ids) > 0");
                        });
                });

            modelBuilder.Entity("NoCTF.Domain.Challenges.Challenge", b =>
                {
                    b.HasOne("NoCTF.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_challenges_users_owner_id");
                });

            modelBuilder.Entity("NoCTF.Domain.Challenges.ChallengeAttachment", b =>
                {
                    b.HasOne("NoCTF.Domain.Challenges.Challenge", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_attachments_challenges_challenge_id");

                    b.HasOne("NoCTF.Domain.Storage.StoredFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_attachments_files_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("NoCTF.Domain.Challenges.ChallengeFlag", b =>
                {
                    b.HasOne("NoCTF.Domain.Challenges.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_challenge_flags_challenges_challenge_id");

                    b.HasOne("NoCTF.Domain.Challenges.CompetitionChallenge", null)
                        .WithMany()
                        .HasForeignKey("CompetitionChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_challenge_flags_competition_challenges_competition_challeng");

                    b.HasOne("NoCTF.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_challenge_flags_teams_team_id");
                });

            modelBuilder.Entity("NoCTF.Domain.Challenges.CompetitionChallenge", b =>
                {
                    b.HasOne("NoCTF.Domain.Challenges.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competition_challenges_challenges_challenge_id");

                    b.HasOne("NoCTF.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competition_challenges_competitions_competition_id");

                    b.OwnsMany("NoCTF.Domain.Challenges.CompetitionChallengeHint", "Hints", b1 =>
                        {
                            b1.Property<Guid>("CompetitionChallengeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Content")
                                .IsRequired();

                            b1.Property<long>("Cost");

                            b1.Property<DateTimeOffset?>("HiddenAt");

                            b1.Property<Guid>("Id");

                            b1.Property<DateTimeOffset?>("PublishedAt");

                            b1.HasKey("CompetitionChallengeId", "__synthesizedOrdinal")
                                .HasName("pk_competition_challenges");

                            b1.ToTable("competition_challenges");

                            b1
                                .ToJson("hints_json")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CompetitionChallengeId")
                                .HasConstraintName("fk_competition_challenges_competition_challenges_competition_ch");
                        });

                    b.Navigation("Hints");
                });

            modelBuilder.Entity("NoCTF.Domain.Competitions.Competition", b =>
                {
                    b.HasOne("NoCTF.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competitions_users_owner_id");

                    b.HasOne("NoCTF.Domain.Storage.StoredFile", "PosterFile")
                        .WithMany()
                        .HasForeignKey("PosterFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_competitions_files_poster_file_id");

                    b.Navigation("PosterFile");
                });

            modelBuilder.Entity("NoCTF.Domain.Competitions.Events.CompetitionEvent", b =>
                {
                    b.HasOne("NoCTF.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_competition_events_users_actor_user_id");

                    b.HasOne("NoCTF.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competition_events_competitions_competition_id");

                    b.HasOne("NoCTF.Domain.Competitions.Events.CompetitionEvent", null)
                        .WithMany()
                        .HasForeignKey("ParentEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_competition_events_competition_events_parent_event_id");
                });

            modelBuilder.Entity("NoCTF.Domain.Gameplay.GameplayFact", b =>
                {
                    b.HasOne("NoCTF.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_gameplay_facts_users_actor_user_id");

                    b.HasOne("NoCTF.Domain.Challenges.CompetitionChallenge", null)
                        .WithMany()
                        .HasForeignKey("CompetitionChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gameplay_facts_competition_challenges_competition_challenge");

                    b.HasOne("NoCTF.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gameplay_facts_competitions_competition_id");

                    b.HasOne("NoCTF.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_gameplay_facts_teams_team_id");

                    b.HasOne("NoCTF.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("VictimTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_gameplay_facts_teams_victim_team_id");
                });

            modelBuilder.Entity("NoCTF.Domain.Gameplay.PatchUpload", b =>
                {
                    b.HasOne("NoCTF.Domain.Challenges.CompetitionChallenge", null)
                        .WithMany()
                        .HasForeignKey("CompetitionChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patch_uploads_competition_challenges_competition_challenge_");

                    b.HasOne("NoCTF.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patch_uploads_competitions_competition_id");

                    b.HasOne("NoCTF.Domain.Storage.StoredFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patch_uploads_files_file_id");

                    b.HasOne("NoCTF.Domain.Runtime.RuntimeInstance", null)
                        .WithMany()
                        .HasForeignKey("RuntimeInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_patch_uploads_runtime_instances_runtime_instance_id");

                    b.HasOne("NoCTF.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patch_uploads_teams_team_id");

                    b.HasOne("NoCTF.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patch_uploads_users_uploaded_by_user_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("NoCTF.Domain.Identity.AccountToken", b =>
                {
                    b.HasOne("NoCTF.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_tokens_users_user_id");
                });

            modelBuilder.Entity("NoCTF.Domain.Identity.User", b =>
                {
                    b.HasOne("NoCTF.Domain.Storage.StoredFile", "AvatarFile")
                        .WithMany()
                        .HasForeignKey("AvatarFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_files_avatar_file_id");

                    b.HasOne("NoCTF.Domain.Storage.StoredFile", "WallpaperFile")
                        .WithMany()
                        .HasForeignKey("WallpaperFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_files_wallpaper_file_id");

                    b.Navigation("AvatarFile");

                    b.Navigation("WallpaperFile");
                });

            modelBuilder.Entity("NoCTF.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("NoCTF.Domain.Notifications.Notification", null)
                        .WithMany()
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notifications_notifications_reply_to_id");

                    b.HasOne("NoCTF.Domain.Notifications.Notification", null)
                        .WithMany()
                        .HasForeignKey("ThreadRootId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notifications_notifications_thread_root_id");
                });

            modelBuilder.Entity("NoCTF.Domain.Platform.PlatformSettings", b =>
                {
                    b.HasOne("NoCTF.Domain.Storage.StoredFile", "LogoFile")
                        .WithMany()
                        .HasForeignKey("LogoFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_platform_settings_files_logo_file_id");

                    b.Navigation("LogoFile");
                });

            modelBuilder.Entity("NoCTF.Domain.Runtime.RuntimeInstance", b =>
                {
                    b.HasOne("NoCTF.Domain.Challenges.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_runtime_instances_challenges_challenge_id");

                    b.HasOne("NoCTF.Domain.Challenges.CompetitionChallenge", null)
                        .WithMany()
                        .HasForeignKey("CompetitionChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_runtime_instances_competition_challenges_competition_challe");

                    b.HasOne("NoCTF.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_runtime_instances_competitions_competition_id");

                    b.HasOne("NoCTF.Domain.Gameplay.GameplayFact", null)
                        .WithMany()
                        .HasForeignKey("GameplayFactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_runtime_instances_gameplay_facts_gameplay_fact_id");

                    b.HasOne("NoCTF.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_runtime_instances_teams_team_id");

                    b.OwnsMany("NoCTF.Domain.Runtime.RuntimePublishedPort", "PublishedPorts", b1 =>
                        {
                            b1.Property<Guid>("RuntimeInstanceId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("ContainerPort");

                            b1.Property<int>("HostPort");

                            b1.Property<string>("ServiceName")
                                .HasMaxLength(63);

                            b1.HasKey("RuntimeInstanceId", "__synthesizedOrdinal")
                                .HasName("pk_runtime_instances");

                            b1.ToTable("runtime_instances");

                            b1
                                .ToJson("published_ports_json")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RuntimeInstanceId")
                                .HasConstraintName("fk_runtime_instances_runtime_instances_runtime_instance_id");
                        });

                    b.Navigation("PublishedPorts");
                });

            modelBuilder.Entity("NoCTF.Domain.Teams.Team", b =>
                {
                    b.HasOne("NoCTF.Domain.Storage.StoredFile", "AvatarFile")
                        .WithMany()
                        .HasForeignKey("AvatarFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_teams_files_avatar_file_id");

                    b.HasOne("NoCTF.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CaptainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_users_captain_id");

                    b.HasOne("NoCTF.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_competitions_competition_id");

                    b.Navigation("AvatarFile");
                });

            modelBuilder.Entity("NoCTF.Domain.Challenges.Challenge", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
