/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createNoCTFAPIEndpointsAdministrationCompetitionsStartValidationResponseFromDiscriminatorValue, type NoCTFAPIEndpointsAdministrationCompetitionsStartValidationResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/admin/competitions/{competitionId}/start-validation
 */
export interface StartValidationRequestBuilder extends BaseRequestBuilder<StartValidationRequestBuilder> {
    /**
     * Returns every current stable, deduplicated start error without changing state.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NoCTFAPIEndpointsAdministrationCompetitionsStartValidationResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<NoCTFAPIEndpointsAdministrationCompetitionsStartValidationResponse | undefined>;
    /**
     * Returns every current stable, deduplicated start error without changing state.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StartValidationRequestBuilderUriTemplate = "{+baseurl}/api/v1/admin/competitions/{competitionId}/start-validation";
/**
 * Metadata for all the requests in the request builder.
 */
export const StartValidationRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StartValidationRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createNoCTFAPIEndpointsAdministrationCompetitionsStartValidationResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
