apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: loki-config
  namespace: noctf
  files: [loki/loki.yml]
- name: prometheus-rules
  namespace: noctf
  files: [prometheus/rules/recording-rules.yml, prometheus/rules/alerts.yml]
- name: grafana-dashboard-files
  namespace: noctf
  files:
  - grafana/dashboards/noctf-overview.json
  - grafana/dashboards/noctf-performance.json
  - grafana/dashboards/noctf-logs.json
